{{- if .Values.superglue.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "valeo-erp.fullname" . }}-superglue-config
  namespace: {{ .Values.superglue.namespace | quote }}
  labels:
    {{- include "valeo-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: superglue
data:
  API_PORT: "3002"
  API_ENDPOINT: {{ .Values.superglue.config.apiEndpoint | quote }}
  WEB_PORT: "3001"
  SUPERGLUE_APP_URL: {{ .Values.superglue.config.appUrl | quote }}
  START_SCHEDULER_SERVER: {{ ternary "true" "false" .Values.superglue.config.schedulerEnabled | quote }}
  DATASTORE_TYPE: "postgres"
  SUPERGLUE_SYNC_ENABLED: {{ ternary "true" "false" .Values.superglue.config.syncEnabled | quote }}
  SUPERGLUE_EXECUTION_ENABLED: {{ ternary "true" "false" .Values.superglue.config.executionEnabled | quote }}
  POSTGRES_HOST: {{ printf "%s-superglue-db" (include "valeo-erp.fullname" .) | quote }}
  POSTGRES_PORT: "5432"
  POSTGRES_SSL: "false"
  POSTGRES_DB: {{ .Values.superglue.database.name | quote }}
  FILE_STORAGE_PROVIDER: "minio"
  S3_ENDPOINT: {{ printf "http://%s-superglue-minio:9000" (include "valeo-erp.fullname" .) | quote }}
  S3_PUBLIC_ENDPOINT: {{ printf "https://%s" .Values.superglue.ingress.hosts.minio | quote }}
  MINIO_BUCKET_NAME: {{ .Values.superglue.minio.bucket | quote }}
  MINIO_BUCKET_PREFIX: "raw"
  MINIO_WEBHOOK_ENDPOINT: {{ printf "http://%s-superglue:3002/v1/file-references/process" (include "valeo-erp.fullname" .) | quote }}
{{- end }}

