{{- if and .Values.superglue.enabled .Values.superglue.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-superglue" (include "valeo-erp.fullname" .)) .Values.superglue.serviceAccount.name }}
  namespace: {{ .Values.superglue.namespace | quote }}
  labels:
    {{- include "valeo-erp.labels" . | nindent 4 }}
    app.kubernetes.io/component: superglue
{{- end }}

