apiVersion: v1
kind: Service
metadata:
  name: superglue-db
  labels:
    app.kubernetes.io/name: superglue-db
    app.kubernetes.io/part-of: valeo-neuroerp
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: superglue-db
    app.kubernetes.io/part-of: valeo-neuroerp

