apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: superglue
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: superglue
      app.kubernetes.io/part-of: valeo-neuroerp
  namespaceSelector:
    matchNames:
      - valeo-integrations
  endpoints:
    - port: http
      path: /health
      interval: 30s
      scrapeTimeout: 10s
