import type { PageModuleGlob } from '@/app/page-module-groups/types'

export const PAGE_MODULES = import.meta.glob([
  '../../pages/agrar/**/*.tsx',
  '../../pages/agribusiness/**/*.tsx',
  '../../pages/annahme/**/*.tsx',
  '../../pages/artikel/**/*.tsx',
  '../../pages/charge/**/*.tsx',
  '../../pages/disposition/**/*.tsx',
  '../../pages/dokumente/**/*.tsx',
  '../../pages/einkauf/**/*.tsx',
  '../../pages/energie/**/*.tsx',
  '../../pages/etiketten/**/*.tsx',
  '../../pages/foerderung/**/*.tsx',
  '../../pages/fuhrpark/**/*.tsx',
  '../../pages/futter/**/*.tsx',
  '../../pages/futtermittel/**/*.tsx',
  '../../pages/inbox/**/*.tsx',
  '../../pages/inventory/**/*.tsx',
  '../../pages/labor/**/*.tsx',
  '../../pages/lager/**/*.tsx',
  '../../pages/logistik/**/*.tsx',
  '../../pages/mobile/**/*.tsx',
  '../../pages/nachhaltigkeit/**/*.tsx',
  '../../pages/nawaro/**/*.tsx',
  '../../pages/produktion/**/*.tsx',
  '../../pages/projekte/**/*.tsx',
  '../../pages/qualitaet/**/*.tsx',
  '../../pages/rezepte/**/*.tsx',
  '../../pages/schaeden/**/*.tsx',
  '../../pages/schichtplan/**/*.tsx',
  '../../pages/silo/**/*.tsx',
  '../../pages/statistik/**/*.tsx',
  '../../pages/strecke/**/*.tsx',
  '../../pages/subventionen/**/*.tsx',
  '../../pages/tankstelle/**/*.tsx',
  '../../pages/transporte/**/*.tsx',
  '../../pages/verladung/**/*.tsx',
  '../../pages/versand/**/*.tsx',
  '../../pages/versicherungen/**/*.tsx',
  '../../pages/vertrag/**/*.tsx',
  '../../pages/waage/**/*.tsx',
  '../../pages/wartung/**/*.tsx',
  '../../pages/zertifikate/**/*.tsx',
  '../../pages/inventory.tsx',
]) as PageModuleGlob
