***REMOVED*** A generic, single database configuration.

[alembic]
***REMOVED*** path to migration scripts
***REMOVED*** Use forward slashes (/) also on windows to provide an os agnostic path
script_location = alembic
sqlalchemy.url = postgresql://valeo_dev:REDACTED_PASSWORD@localhost:5435/valeo_neuro_erp

***REMOVED*** template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
***REMOVED*** Uncomment the line below if you want the files to be prepended with date and time
***REMOVED*** see https://alembic.sqlalchemy.org/en/latest/tutorial.html***REMOVED***editing-the-ini-file
***REMOVED*** for all available tokens
***REMOVED*** file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

***REMOVED*** sys.path path, will be prepended to sys.path if present.
***REMOVED*** defaults to the current working directory.
prepend_sys_path = .

***REMOVED*** timezone to use when rendering the date within the migration file
***REMOVED*** as well as the filename.
***REMOVED*** If specified, requires the python>=3.9 or backports.zoneinfo library and tzdata library.
***REMOVED*** Any required deps can installed by adding `alembic[tz]` to the pip requirements
***REMOVED*** string value is passed to ZoneInfo()
***REMOVED*** leave blank for localtime
***REMOVED*** timezone =

***REMOVED*** max length of characters to apply to the "slug" field
***REMOVED*** truncate_slug_length = 40

***REMOVED*** set to 'true' to run the environment during
***REMOVED*** the 'revision' command, regardless of autogenerate
***REMOVED*** revision_environment = false

***REMOVED*** set to 'true' to allow .pyc and .pyo files without
***REMOVED*** a source .py file to be detected as revisions in the
***REMOVED*** versions/ directory
***REMOVED*** sourceless = false

***REMOVED*** version location specification; This defaults
***REMOVED*** to alembic/versions.  When using multiple version
***REMOVED*** directories, initial revisions must be specified with --version-path.
***REMOVED*** The path separator used here should be the separator specified by "version_path_separator" below.
***REMOVED*** version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

***REMOVED*** version path separator; As mentioned above, this is the character used to split
***REMOVED*** version_locations. The default within new alembic.ini files is "os", which uses os.pathsep.
***REMOVED*** If this key is omitted entirely, it falls back to the legacy behavior of splitting on spaces and/or commas.
***REMOVED*** Valid values for version_path_separator are:
***REMOVED***
***REMOVED*** version_path_separator = :
***REMOVED*** version_path_separator = ;
***REMOVED*** version_path_separator = space
***REMOVED*** version_path_separator = newline
***REMOVED***
***REMOVED*** Use os.pathsep. Default configuration used for new projects.
version_path_separator = os

***REMOVED*** set to 'true' to search source files recursively
***REMOVED*** in each "version_locations" directory
***REMOVED*** new in Alembic version 1.10
***REMOVED*** recursive_version_locations = false

***REMOVED*** the output encoding used when revision files
***REMOVED*** are written from script.py.mako
***REMOVED*** output_encoding = utf-8

[post_write_hooks]
***REMOVED*** post_write_hooks defines scripts or Python functions that are run
***REMOVED*** on newly generated revision scripts.  See the documentation for further
***REMOVED*** detail and examples

***REMOVED*** format using "black" - use the console_scripts runner, against the "black" entrypoint
***REMOVED*** hooks = black
***REMOVED*** black.type = console_scripts
***REMOVED*** black.entrypoint = black
***REMOVED*** black.options = -l 79 REVISION_SCRIPT_FILENAME

***REMOVED*** lint with attempts to fix using "ruff" - use the exec runner, execute a binary
***REMOVED*** hooks = ruff
***REMOVED*** ruff.type = exec
***REMOVED*** ruff.executable = %(here)s/.venv/bin/ruff
***REMOVED*** ruff.options = check --fix REVISION_SCRIPT_FILENAME

***REMOVED*** Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
