ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS analytics_gap_ref_year SMALLINT,
  ADD COLUMN IF NOT EXISTS analytics_gap_direct_total_eur NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS analytics_gap_estimated_area_ha NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS analytics_potential_total_eur NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS analytics_potential_seed_eur NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS analytics_potential_fertilizer_eur NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS analytics_potential_psm_eur NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS analytics_turnover_total_last_year_eur NUMERIC(14,2),
  ADD COLUMN IF NOT EXISTS analytics_share_of_wallet_total_pct NUMERIC(5,2),
  ADD COLUMN IF NOT EXISTS analytics_segment VARCHAR(1),
  ADD COLUMN IF NOT EXISTS analytics_gap_last_sync_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS analytics_gap_last_sync_status VARCHAR(32),
  ADD COLUMN IF NOT EXISTS analytics_gap_matching_key TEXT,
  ADD COLUMN IF NOT EXISTS analytics_is_core_customer BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS analytics_block_auto_potential_update BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS analytics_last_manual_review_year SMALLINT,
  ADD COLUMN IF NOT EXISTS analytics_potential_notes TEXT,
  ADD COLUMN IF NOT EXISTS analytics_owner UUID;
