/**
 * Anzeigetexte fuer Belegstatus. Backends liefern Status als Schluessel
 * (`open`, `in_delivery`, ...); die Maske zeigt nie den Schluessel, sondern den
 * fachlichen Begriff. Unbekannte Werte bleiben stehen, damit nichts verschluckt wird.
 */
const STATUS_LABELS: Record<string, string> = {
  new: 'Neu',
  draft: 'Entwurf',
  open: 'Offen',
  pending: 'Ausstehend',
  planned: 'Geplant',
  in_progress: 'In Bearbeitung',
  confirmed: 'Bestaetigt',
  validated: 'Geprueft',
  approved: 'Genehmigt',
  released: 'Freigegeben',
  rejected: 'Abgelehnt',
  blocked: 'Gesperrt',
  ordered: 'Bestellt',
  bestellt: 'Bestellt',
  in_delivery: 'In Lieferung',
  shipped: 'Versendet',
  delivered: 'Geliefert',
  partially_delivered: 'Teilgeliefert',
  invoiced: 'Fakturiert',
  posted: 'Gebucht',
  sent: 'Versendet',
  queued: 'In Warteschlange',
  paid: 'Bezahlt',
  partially_paid: 'Teilbezahlt',
  overdue: 'Ueberfaellig',
  completed: 'Abgeschlossen',
  done: 'Erledigt',
  closed: 'Geschlossen',
  cancelled: 'Storniert',
  canceled: 'Storniert',
  archived: 'Archiviert',
  active: 'Aktiv',
  inactive: 'Inaktiv',
  error: 'Fehler',
  failed: 'Fehlgeschlagen',
  created: 'Angelegt',
  requested: 'Angefordert',
  proposed: 'Vorgeschlagen',
  prepared: 'Vorbereitet',
  ready: 'Bereit',
  accepted: 'Angenommen',
  pending_approval: 'Genehmigung ausstehend',
  review_due: 'Pruefung faellig',
  qualified: 'Qualifiziert',
  partially_allocated: 'Teilweise zugeordnet',
  reversed: 'Gegengebucht',
  superseded: 'Ersetzt',
  retired: 'Ausgemustert',
  quarantined: 'Quarantaene',
  unread: 'Ungelesen',
  published_temp: 'Vorlaeufig veroeffentlicht',
  dial_req: 'Anruf angefordert',
  optimal: 'Optimal',
  infeasible: 'Nicht loesbar',
  // Einige Domaenen speichern deutsche Schluessel in Kleinschreibung.
  entwurf: 'Entwurf',
  offen: 'Offen',
  erfasst: 'Erfasst',
  erstellt: 'Erstellt',
  eingang: 'Eingang',
  eingereicht: 'Eingereicht',
  vorauswahl: 'Vorauswahl',
  geplant: 'Geplant',
  in_bearbeitung: 'In Bearbeitung',
  geparst: 'Eingelesen',
  verarbeitet: 'Verarbeitet',
  uebernommen: 'Uebernommen',
  kein_treffer: 'Kein Treffer',
  angenommen: 'Angenommen',
  bestaetigt: 'Bestaetigt',
  bewilligt: 'Bewilligt',
  freigegeben: 'Freigegeben',
  gueltig: 'Gueltig',
  aktiv: 'Aktiv',
  sperren: 'Gesperrt',
  gesendet: 'Gesendet',
  teilgeliefert: 'Teilgeliefert',
  geliefert: 'Geliefert',
  berechnet: 'Berechnet',
  gebucht: 'Gebucht',
  bezahlt: 'Bezahlt',
  fertig: 'Fertig',
  erledigt: 'Erledigt',
  beendet: 'Beendet',
  abgeschlossen: 'Abgeschlossen',
  ablaufend: 'Laeuft ab',
  auslaufend: 'Laeuft aus',
  stillgelegt: 'Stillgelegt',
  storniert: 'Storniert',
}

export function statusLabel(value: string): string {
  return STATUS_LABELS[value.trim().toLowerCase().replace(/[\s-]+/g, '_')] ?? value
}
