export type FieldPriority = "core" | "optional" | "legacy";

export interface CustomerFieldDef {
  key: string;
  label: string;
  tab: string;
  section: string;
  priority: FieldPriority;
}

export const CUSTOMER_FIELDS: CustomerFieldDef[
  {
    key: "customer.customer_number",
    label: "Kundennr.",
    tab: "masterdata",
    section: "masterdata_basic",
    priority: "core",
  },
  {
    key: "customer.search_key",
    label: "Suchbegriff",
    tab: "masterdata",
    section: "masterdata_basic",
    priority: "core",
  },
  {
    key: "customer.name1",
    label: "Name 1",
    tab: "masterdata",
    section: "masterdata_basic",
    priority: "core",
  },
  {
    key: "customer.name2",
    label: "Name 2",
    tab: "masterdata",
    section: "masterdata_basic",
    priority: "optional",
  },
  {
    key: "customer.name3",
    label: "Name 3",
    tab: "masterdata",
    section: "masterdata_basic",
    priority: "optional",
  },
  {
    key: "customer.country",
    label: "Staat",
    tab: "masterdata",
    section: "masterdata_general",
    priority: "core",
  },
  {
    key: "customer.state",
    label: "Bundesland",
    tab: "masterdata",
    section: "masterdata_general",
    priority: "optional",
  },
  {
    key: "customer.since",
    label: "Kunde seit",
    tab: "masterdata",
    section: "masterdata_general",
    priority: "optional",
  },
  {
    key: "customer.group",
    label: "Kunden-Gruppe",
    tab: "masterdata",
    section: "masterdata_classification",
    priority: "core",
  },
  {
    key: "customer.abc_status",
    label: "ABC-/Umsatzstatus",
    tab: "masterdata",
    section: "masterdata_classification",
    priority: "optional",
  },
  {
    key: "customer.fax_blocked",
    label: "Fax-Sperre",
    tab: "masterdata",
    section: "masterdata_classification",
    priority: "optional",
  },
  {
    key: "customer.dispatcher",
    label: "Disponent",
    tab: "masterdata",
    section: "masterdata_responsibility",
    priority: "optional",
  },
  {
    key: "customer.sales_rep",
    label: "VB (Außendienst)",
    tab: "masterdata",
    section: "masterdata_responsibility",
    priority: "core",
  },
  {
    key: "address.street",
    label: "Straße",
    tab: "address",
    section: "address_main",
    priority: "core",
  },
  {
    key: "address.zip",
    label: "PLZ",
    tab: "address",
    section: "address_main",
    priority: "core",
  },
  {
    key: "address.city",
    label: "Ort",
    tab: "address",
    section: "address_main",
    priority: "core",
  },
  {
    key: "address.country",
    label: "Land",
    tab: "address",
    section: "address_main",
    priority: "core",
  },
  {
    key: "address.po_box",
    label: "Postfach",
    tab: "address",
    section: "address_main",
    priority: "optional",
  },
  {
    key: "address.po_box_zip",
    label: "Postf.-PLZ",
    tab: "address",
    section: "address_main",
    priority: "optional",
  },
  {
    key: "address.po_box_city",
    label: "Postf.-Ort",
    tab: "address",
    section: "address_main",
    priority: "optional",
  },
  {
    key: "contact.phone1",
    label: "Tel. 1",
    tab: "address",
    section: "address_communication",
    priority: "core",
  },
  {
    key: "contact.phone2",
    label: "Tel. 2",
    tab: "address",
    section: "address_communication",
    priority: "optional",
  },
  {
    key: "contact.fax",
    label: "Telefax",
    tab: "address",
    section: "address_communication",
    priority: "optional",
  },
  {
    key: "contact.email",
    label: "E-Mail",
    tab: "address",
    section: "address_communication",
    priority: "core",
  },
  {
    key: "contact.website",
    label: "Homepage",
    tab: "address",
    section: "address_communication",
    priority: "optional",
  },
  {
    key: "contact.salutation",
    label: "Anrede",
    tab: "address",
    section: "address_communication",
    priority: "optional",
  },
  {
    key: "contact.letter_salutation",
    label: "Briefanrede",
    tab: "address",
    section: "address_communication",
    priority: "optional",
  },
  {
    key: "custom.free1",
    label: "Frei 1",
    tab: "masterdata",
    section: "masterdata_basic",
    priority: "optional",
  },
  {
    key: "custom.free2",
    label: "Frei 2",
    tab: "masterdata",
    section: "masterdata_basic",
    priority: "optional",
  },
  {
    key: "custom.free3",
    label: "Frei 3",
    tab: "masterdata",
    section: "masterdata_basic",
    priority: "optional",
  },
  {
    key: "system.created_at",
    label: "Erstanlage",
    tab: "system",
    section: "system_metadata",
    priority: "core",
  },
  {
    key: "system.created_by",
    label: "Erstanlage von",
    tab: "system",
    section: "system_metadata",
    priority: "optional",
  },
  {
    key: "system.branch",
    label: "Niederlassung",
    tab: "system",
    section: "system_metadata",
    priority: "core",
  },
  {
    key: "system.cost_center",
    label: "Kostenstelle",
    tab: "system",
    section: "system_metadata",
    priority: "optional",
  },
  {
    key: "system.block_reason",
    label: "Sperre-Grund",
    tab: "system",
    section: "system_blocking",
    priority: "optional",
  },
  {
    key: "tax.vat_id",
    label: "UST-ID-Nr.",
    tab: "tax",
    section: "tax_flags",
    priority: "core",
  },
  {
    key: "tax.tax_number",
    label: "Steuer-Nr.",
    tab: "tax",
    section: "tax_flags",
    priority: "optional",
  },
  {
    key: "quality.vvvo_number",
    label: "Betriebs-Nr. (VVVO)",
    tab: "quality_compliance",
    section: "quality_farm_ids",
    priority: "core",
  },
  {
    key: "finance.invoice.account_usage",
    label: "Kontonutzung für Rechnung",
    tab: "finance",
    section: "finance_invoice_account",
    priority: "optional",
  },
  {
    key: "finance.invoice.account_statement_requested",
    label: "Kontoauszug gewünscht",
    tab: "finance",
    section: "finance_invoice_account",
    priority: "optional",
  },
  {
    key: "finance.invoice.single_or_collect",
    label: "Einzel-/Sammel-Abrechnung",
    tab: "finance",
    section: "finance_invoice_account",
    priority: "core",
  },
  {
    key: "finance.invoice.bonus_recipient",
    label: "Bonus-/Rechnungsempfänger",
    tab: "finance",
    section: "finance_invoice_account",
    priority: "optional",
  },
  {
    key: "finance.invoice.self_billing",
    label: "Selbstabrechnung durch Kunden",
    tab: "finance",
    section: "finance_invoice_account",
    priority: "optional",
  },
  {
    key: "finance.terms.default",
    label: "Zahlungsbedingungen (Tage / Skonto / netto)",
    tab: "finance",
    section: "finance_payment_terms",
    priority: "core",
  },
  {
    key: "finance.dunning.enabled",
    label: "Mahnwesen",
    tab: "finance",
    section: "finance_payment_terms",
    priority: "optional",
  },
  {
    key: "bank.iban",
    label: "IBAN",
    tab: "bank",
    section: "bank_accounts",
    priority: "core",
  },
  {
    key: "bank.bic",
    label: "BIC",
    tab: "bank",
    section: "bank_accounts",
    priority: "core",
  },
  {
    key: "bank.name",
    label: "Bank",
    tab: "bank",
    section: "bank_accounts",
    priority: "optional",
  },
  {
    key: "profile.industry_code",
    label: "Branche (mit Schlüssel)",
    tab: "marketing",
    section: "marketing_customer_profile",
    priority: "core",
  },
  {
    key: "profile.annual_turnover",
    label: "Jahresumsatz",
    tab: "marketing",
    section: "marketing_customer_profile",
    priority: "optional",
  },
  {
    key: "profile.employee_count",
    label: "Anzahl Mitarbeiter/innen",
    tab: "marketing",
    section: "marketing_customer_profile",
    priority: "optional",
  },
  {
    key: "profile.founded_at",
    label: "Gründung",
    tab: "marketing",
    section: "marketing_customer_profile",
    priority: "optional",
  },
  {
    key: "cooperative.member_number",
    label: "Mitglieds-Nr.",
    tab: "cooperative",
    section: "cooperative_shares",
    priority: "optional",
  },
  {
    key: "cooperative.share_account",
    label: "Geschäftsguthaben-Konto",
    tab: "cooperative",
    section: "cooperative_shares",
    priority: "optional",
  },
  {
    key: "cooperative_group.code",
    label: "Verb.-Nr.",
    tab: "cooperative",
    section: "cooperative_farming_groups",
    priority: "optional",
  },
  {
    key: "cooperative_group.name",
    label: "Bezeichnung Betriebsgemeinschaft",
    tab: "cooperative",
    section: "cooperative_farming_groups",
    priority: "optional",
  },
  {
    key: "contacts.primary.priority",
    label: "Priorität (Ansprechpartner)",
    tab: "contacts",
    section: "contacts_list",
    priority: "optional",
  },
  {
    key: "contacts.primary.name",
    label: "Name Ansprechpartner",
    tab: "contacts",
    section: "contacts_list",
    priority: "core",
  },
  {
    key: "contacts.primary.email",
    label: "E-Mail Ansprechpartner",
    tab: "contacts",
    section: "contacts_list",
    priority: "optional",
  },
  {
    key: "output.invoice.delivery_method",
    label: "Versandart Rechnung",
    tab: "output",
    section: "output_document_delivery",
    priority: "core",
  },
  {
    key: "output.dunning.delivery_method",
    label: "Versandart Mahnung",
    tab: "output",
    section: "output_document_delivery",
    priority: "optional",
  },
  {
    key: "output.contact_bundle.delivery_method",
    label: "Versandart Kontaktzusammenstellung",
    tab: "output",
    section: "output_document_delivery",
    priority: "optional",
  },
  {
    key: "output.dispatch_number",
    label: "Dispo-Nummer",
    tab: "output",
    section: "output_document_delivery",
    priority: "optional",
  },
  {
    key: "output.initialisation_instruction",
    label: "Initialisierungsweisung",
    tab: "output",
    section: "output_document_delivery",
    priority: "optional",
  },
  {
    key: "output.invoice.channel",
    label: "Versandmedium Rechnung (Brief/E-Mail)",
    tab: "output",
    section: "output_document_delivery",
    priority: "core",
  },
  {
    key: "output.dunning.channel",
    label: "Versandmedium Mahnung (Brief/E-Mail)",
    tab: "output",
    section: "output_document_delivery",
    priority: "optional",
  },
  {
    key: "output.zugferd.profile",
    label: "ZUGFeRD Auswahl",
    tab: "output",
    section: "output_document_delivery",
    priority: "optional",
  },
  {
    key: "output.delivery.condition",
    label: "Liefer-Bedingung",
    tab: "output",
    section: "output_delivery_payment_terms",
    priority: "optional",
  },
  {
    key: "output.payment.condition_override",
    label: "Zahlungsbedingung (spezifisch Kunde / Lieferung)",
    tab: "output",
    section: "output_delivery_payment_terms",
    priority: "optional",
  },
  {
    key: "output.payment.due_from",
    label: "Faelligkeit ab (Rechnungsdatum/Termin/Valuta)",
    tab: "output",
    section: "output_delivery_payment_terms",
    priority: "optional",
  },
  {
    key: "output.proforma.enabled",
    label: "Pro-Forma-Rechnung",
    tab: "output",
    section: "output_delivery_payment_terms",
    priority: "optional",
  },
  {
    key: "output.proforma.discount1",
    label: "Pro-Forma-Rabatt 1",
    tab: "output",
    section: "output_delivery_payment_terms",
    priority: "optional",
  },
  {
    key: "output.proforma.discount2",
    label: "Pro-Forma-Rabatt 2",
    tab: "output",
    section: "output_delivery_payment_terms",
    priority: "optional",
  },
  {
    key: "output.despatch_advice.mode",
    label: "Einzel-/Sammelversand-Avis",
    tab: "output",
    section: "output_delivery_payment_terms",
    priority: "optional",
  },
  {
    key: "output.despatch_advice.to_rep",
    label: "Versand-Avis an Vertreter/Beauftragte",
    tab: "output",
    section: "output_delivery_payment_terms",
    priority: "optional",
  },
  {
    key: "privacy.consent_until",
    label: "Einwilligung gültig bis",
    tab: "quality_compliance",
    section: "privacy_consent",
    priority: "optional",
  },
  {
    key: "privacy.consent_flag",
    label: "Einwilligung erteilt",
    tab: "quality_compliance",
    section: "privacy_consent",
    priority: "core",
  },
  {
    key: "privacy.created_at",
    label: "Anlagedatum (Datenschutz)",
    tab: "quality_compliance",
    section: "privacy_consent",
    priority: "optional",
  },
  {
    key: "privacy.created_by",
    label: "Anlagebearbeiter (Datenschutz)",
    tab: "quality_compliance",
    section: "privacy_consent",
    priority: "optional",
  },
  {
    key: "privacy.comment",
    label: "Zusatzbemerkung (Datenschutz)",
    tab: "quality_compliance",
    section: "privacy_consent",
    priority: "optional",
  },
  {
    key: "marketing.mailing_list.name",
    label: "Verteiler-Name",
    tab: "marketing",
    section: "marketing_mailing_lists",
    priority: "optional",
  },
  {
    key: "marketing.mailing_list.description",
    label: "Bezeichnung",
    tab: "marketing",
    section: "marketing_mailing_lists",
    priority: "optional",
  },
  {
    key: "marketing.mailing_list.email",
    label: "E-Mail-Adresse (Verteiler)",
    tab: "marketing",
    section: "marketing_mailing_lists",
    priority: "optional",
  },
  {
    key: "system.notes.longtext",
    label: "Langtext",
    tab: "system",
    section: "system_notes",
    priority: "optional",
  },
  {
    key: "system.notes.management_instruction",
    label: "Chef-Anweisung",
    tab: "system",
    section: "system_notes",
    priority: "optional",
  },
  {
    key: "system.posting.disable_open_items",
    label: "Offene Posten nicht aufrufen",
    tab: "system",
    section: "system_misc",
    priority: "optional",
  },
  {
    key: "system.recalculation.enabled",
    label: "Nachkalkulation",
    tab: "system",
    section: "system_misc",
    priority: "optional",
  },
  {
    key: "system.form.profile",
    label: "Formular(e)",
    tab: "system",
    section: "system_misc",
    priority: "optional",
  },
  {
    key: "system.insurance.flag",
    label: "Versicherung",
    tab: "system",
    section: "system_misc",
    priority: "optional",
  },
  {
    key: "system.language.key",
    label: "Sprachschl?ssel",
    tab: "system",
    section: "system_misc",
    priority: "optional",
  },
  {
    key: "system.statistics.flag",
    label: "Statistik-Kennzeichen",
    tab: "system",
    section: "system_misc",
    priority: "optional",
  },
  {
    key: "quality.farm_office_number",
    label: "Landwirtschaftsamt / Betriebsnummer",
    tab: "quality_compliance",
    section: "quality_farm_ids",
    priority: "optional",
  },
  {
    key: "system.market_price_evaluation.enabled",
    label: "Marktpreis-Auswertung",
    tab: "system",
    section: "system_misc",
    priority: "optional",
  },
  {
    key: "system.threshold.value",
    label: "Schwellenwert (Threshold)",
    tab: "system",
    section: "system_misc",
    priority: "optional",
  },
  {
    key: "marketing.webshop.customer_flag",
    label: "Webshop-Kunde",
    tab: "marketing",
    section: "marketing_mailing_lists",
    priority: "optional",
  },
  {
    key: "system.selection.key",
    label: "Selektions-Schl?ssel",
    tab: "system",
    section: "system_selections",
    priority: "optional",
  },
  {
    key: "system.selection.expression",
    label: "Selektions-Berechnung",
    tab: "system",
    section: "system_selections",
    priority: "optional",
  },
  {
    key: "interfaces.tank_card.code",
    label: "Tankkarte / EAN-Code",
    tab: "interfaces",
    section: "interfaces_integration",
    priority: "optional",
  },
  {
    key: "interfaces.customer_card.flag",
    label: "Kundenkarten-Kennzeichen",
    tab: "interfaces",
    section: "interfaces_integration",
    priority: "optional",
  },
  {
    key: "interfaces.edifact.invoic_enabled",
    label: "EDIFACT INVOIC",
    tab: "interfaces",
    section: "interfaces_integration",
    priority: "optional",
  },
  {
    key: "interfaces.edifact.orders_enabled",
    label: "EDIFACT ORDERS",
    tab: "interfaces",
    section: "interfaces_integration",
    priority: "optional",
  },
  {
    key: "interfaces.edifact.desadv_enabled",
    label: "EDIFACT DESADV",
    tab: "interfaces",
    section: "interfaces_integration",
    priority: "optional",
  },
  {
    key: "interfaces.invoice.batch_print",
    label: "Rechnungs-Sammeldruck",
    tab: "interfaces",
    section: "interfaces_integration",
    priority: "optional",
  },
  {
    key: "interfaces.webshop.customer_number",
    label: "Webshop Kunden-Nr.",
    tab: "interfaces",
    section: "interfaces_integration",
    priority: "optional",
  },
  {
    key: "interfaces.webshop.display_name",
    label: "Webshop Bezeichnung",
    tab: "interfaces",
    section: "interfaces_integration",
    priority: "optional",
  },
  {
    key: "finance.discounts.item.article_number",
    label: "Rabatt Artikel-Nr.",
    tab: "finance",
    section: "finance_customer_discounts",
    priority: "optional",
  },
  {
    key: "finance.discounts.item.description",
    label: "Rabatt Bezeichnung",
    tab: "finance",
    section: "finance_customer_discounts",
    priority: "optional",
  },
  {
    key: "finance.discounts.item.discount_percent",
    label: "Rabatt %",
    tab: "finance",
    section: "finance_customer_discounts",
    priority: "optional",
  },
  {
    key: "finance.discounts.item.valid_until",
    label: "Rabatt g?ltig bis",
    tab: "finance",
    section: "finance_customer_discounts",
    priority: "optional",
  },
  {
    key: "finance.discounts.list.source_number",
    label: "Rabatt-Liste ?bernehmen aus Liste-Nr.",
    tab: "finance",
    section: "finance_customer_discounts",
    priority: "legacy",
  },
  {
    key: "finance.discounts.list.save_action",
    label: "Rabatt-Liste speichern",
    tab: "finance",
    section: "finance_customer_discounts",
    priority: "legacy",
  },
  {
    key: "finance.prices.item.article_number",
    label: "Preisvereinbarung Artikel-Nr.",
    tab: "finance",
    section: "finance_agreed_prices",
    priority: "optional",
  },
  {
    key: "finance.prices.item.description",
    label: "Preisvereinbarung Bezeichnung",
    tab: "finance",
    section: "finance_agreed_prices",
    priority: "optional",
  },
  {
    key: "finance.prices.item.valid_from",
    label: "G?ltig ab",
    tab: "finance",
    section: "finance_agreed_prices",
    priority: "optional",
  },
  {
    key: "finance.prices.item.valid_until",
    label: "G?ltig bis",
    tab: "finance",
    section: "finance_agreed_prices",
    priority: "optional",
  },
  {
    key: "finance.prices.item.price_net",
    label: "Preis netto",
    tab: "finance",
    section: "finance_agreed_prices",
    priority: "optional",
  },
  {
    key: "finance.prices.item.price_incl_freight",
    label: "Preis inkl. Fracht",
    tab: "finance",
    section: "finance_agreed_prices",
    priority: "optional",
  },
  {
    key: "finance.prices.item.price_unit",
    label: "Preis-Einheit",
    tab: "finance",
    section: "finance_agreed_prices",
    priority: "optional",
  },
  {
    key: "finance.prices.item.discount_allowed",
    label: "Rabatt erlaubt",
    tab: "finance",
    section: "finance_agreed_prices",
    priority: "optional",
  },
  {
    key: "finance.prices.item.extra_freight",
    label: "Sonderfracht",
    tab: "finance",
    section: "finance_agreed_prices",
    priority: "optional",
  },
  {
    key: "finance.prices.item.payment_condition",
    label: "Zahlungsbedingung (Preisvereinbarung)",
    tab: "finance",
    section: "finance_agreed_prices",
    priority: "optional",
  },
  {
    key: "finance.prices.item.operator",
    label: "Bediener",
    tab: "finance",
    section: "finance_agreed_prices",
    priority: "optional",
  },
  {
    key: "finance.prices.item.operator_date",
    label: "Bediener Datum",
    tab: "finance",
    section: "finance_agreed_prices",
    priority: "optional",
  },
  {
    key: "finance.global.direct_account",
    label: "Direktes Konto",
    tab: "finance",
    section: "finance_pricing_global",
    priority: "optional",
  },
  {
    key: "finance.global.discount_settlement",
    label: "Rabatt-Verrechnung",
    tab: "finance",
    section: "finance_pricing_global",
    priority: "optional",
  },
  {
    key: "finance.global.self_collector_discount",
    label: "Selbstabholer-Rabatt",
    tab: "finance",
    section: "finance_pricing_global",
    priority: "optional",
  },
  {
    key: "finance.global.price_determination_mode",
    label: "Preisermittlung/Sorten",
    tab: "finance",
    section: "finance_pricing_global",
    priority: "optional",
  },
  {
    key: "finance.global.direct_deduction",
    label: "Direktabzug",
    tab: "finance",
    section: "finance_pricing_global",
    priority: "optional",
  },
  {
    key: "finance.global.week_price_ec",
    label: "Wochenpreis auf EC Basis",
    tab: "finance",
    section: "finance_pricing_global",
    priority: "optional",
  },
  {
    key: "finance.global.valid_from",
    label: "Global g?ltig ab",
    tab: "finance",
    section: "finance_pricing_global",
    priority: "optional",
  },
  {
    key: "finance.global.valid_until",
    label: "Global g?ltig bis",
    tab: "finance",
    section: "finance_pricing_global",
    priority: "optional",
  }
];
