import { FastifyRequest, FastifyReply } from 'fastify';

export async function requestIdMiddleware(request: FastifyRequest, reply: FastifyReply) {
  // Request ID is already generated by Fastify with genReqId
  // This middleware can be used for additional request ID processing if needed

  // Add request ID to response headers for client tracking
  reply.header('x-request-id', request.id);

  // Continue to next middleware
}