"""add zahlungslauf kreditoren table

Revision ID: f49745206879
Revises: 59b4fa8420f2
Create Date: 2025-11-17 21:00:31.149768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49745206879'
down_revision: Union[str, None] = '59b4fa8420f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zahlungslauf_kreditoren',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('lauf_nummer', sa.String(), nullable=True),
    sa.Column('ausfuehrungs_datum', sa.String(), nullable=True),
    sa.Column('gesamt_betrag', sa.Float(), nullable=True),
    sa.Column('anzahl_zahlungen', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('freigegeben_am', sa.DateTime(), nullable=True),
    sa.Column('freigegeben_durch', sa.String(), nullable=True),
    sa.Column('ausgefuehrt_am', sa.DateTime(), nullable=True),
    sa.Column('auftraggeber_name', sa.String(), nullable=True),
    sa.Column('auftraggeber_iban', sa.String(), nullable=True),
    sa.Column('auftraggeber_bic', sa.String(), nullable=True),
    sa.Column('zahlungen', sa.JSON(), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('ix_zahlungslauf_kreditoren_lauf_nummer', 'lauf_nummer', unique=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zahlungslauf_kreditoren')
    # ### end Alembic commands ###
