import { useState, useEffect } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { ObjectPage } from '@/components/mask-builder'
import { useMaskData, useMaskValidation, useMaskActions } from '@/components/mask-builder/hooks'
import { MaskConfig } from '@/components/mask-builder/types'
import { z } from 'zod'
import { getEntityTypeLabel, getDetailTitle, getSuccessMessage, getErrorMessage, getStatusLabel } from '@/features/crud/utils/i18n-helpers'
import { createApiClient } from '@/components/mask-builder/utils/api'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { formatDate, formatCurrency } from '@/components/mask-builder/utils/formatting'
import { toast } from '@/hooks/use-toast'
import { ArrowLeft, History, FileText, TrendingUp } from 'lucide-react'

// API Client
const apiClient = createApiClient('/api/crm-sales')

// Zod-Schema für Opportunities
const createOpportunitySchema = (t: any) => z.object({
  number: z.string().optional(),
  name: z.string().min(1, t('crud.messages.validationError')),
  description: z.string().optional(),
  amount: z.number().min(0).optional(),
  currency: z.string().length(3).default('EUR'),
  probability: z.number().min(0).max(100).optional(),
  expected_revenue: z.number().min(0).optional(),
  expected_close_date: z.string().optional(),
  actual_close_date: z.string().optional(),
  status: z.string().default('prospecting'),
  stage: z.string().default('initial_contact'),
  lead_source: z.string().optional(),
  source: z.string().optional(),
  campaign_id: z.string().uuid().optional().or(z.literal('')),
  assigned_to: z.string().optional(),
  owner_id: z.string().optional(),
  customer_id: z.string().uuid().optional().or(z.literal('')),
  contact_id: z.string().uuid().optional().or(z.literal('')),
  notes: z.string().optional(),
})

// Konfiguration für Opportunity ObjectPage
const createOpportunityConfig = (t: any, entityTypeLabel: string): MaskConfig => ({
  title: entityTypeLabel,
  subtitle: t('crud.detail.manage', { entityType: entityTypeLabel }),
  type: 'object-page',
  tabs: [
    {
      key: 'grundinformationen',
      label: t('crud.detail.basicInfo'),
      fields: [
        {
          name: 'number',
          label: t('crud.fields.number'),
          type: 'text',
          readOnly: true,
          placeholder: t('crud.tooltips.placeholders.autoGenerated')
        },
        {
          name: 'name',
          label: t('crud.fields.name'),
          type: 'text',
          required: true,
          placeholder: t('crud.tooltips.placeholders.opportunityName')
        },
        {
          name: 'description',
          label: t('crud.fields.description'),
          type: 'textarea',
          placeholder: t('crud.tooltips.placeholders.description')
        },
        {
          name: 'status',
          label: t('crud.fields.status'),
          type: 'select',
          options: [
            { value: 'prospecting', label: t('status.prospecting') },
            { value: 'qualification', label: t('status.qualification') },
            { value: 'proposal', label: t('status.proposal') },
            { value: 'negotiation', label: t('status.negotiation') },
            { value: 'closed_won', label: t('status.closedWon') },
            { value: 'closed_lost', label: t('status.closedLost') }
          ]
        },
        {
          name: 'stage',
          label: t('crud.fields.stage'),
          type: 'select',
          options: [
            { value: 'initial_contact', label: t('crud.stages.initialContact') },
            { value: 'needs_analysis', label: t('crud.stages.needsAnalysis') },
            { value: 'value_proposition', label: t('crud.stages.valueProposition') },
            { value: 'identify_decision_makers', label: t('crud.stages.identifyDecisionMakers') },
            { value: 'proposal_price_quote', label: t('crud.stages.proposalPriceQuote') },
            { value: 'negotiation_review', label: t('crud.stages.negotiationReview') },
            { value: 'closed_won', label: t('crud.stages.closedWon') },
            { value: 'closed_lost', label: t('crud.stages.closedLost') }
          ]
        },
        {
          name: 'customer_id',
          label: t('crud.entities.customer'),
          type: 'select',
          placeholder: t('crud.tooltips.placeholders.selectCustomer')
          // TODO: Load customers from API
        },
        {
          name: 'contact_id',
          label: t('crud.entities.contact'),
          type: 'select',
          placeholder: t('crud.tooltips.placeholders.selectContact')
          // TODO: Load contacts from API
        },
        {
          name: 'owner_id',
          label: t('crud.fields.owner'),
          type: 'text',
          placeholder: t('crud.tooltips.placeholders.owner')
        },
        {
          name: 'assigned_to',
          label: t('crud.fields.assignedTo'),
          type: 'text',
          placeholder: t('crud.tooltips.placeholders.assignedTo')
        }
      ],
      layout: 'grid',
      columns: 2
    },
    {
      key: 'deal_informationen',
      label: t('crud.detail.dealInfo'),
      fields: [
        {
          name: 'amount',
          label: t('crud.fields.amount'),
          type: 'number',
          placeholder: t('crud.tooltips.placeholders.amount')
        },
        {
          name: 'currency',
          label: t('crud.fields.currency'),
          type: 'select',
          options: [
            { value: 'EUR', label: 'EUR' },
            { value: 'USD', label: 'USD' },
            { value: 'GBP', label: 'GBP' },
            { value: 'CHF', label: 'CHF' }
          ],
          default: 'EUR'
        },
        {
          name: 'probability',
          label: t('crud.fields.probability'),
          type: 'number',
          min: 0,
          max: 100,
          placeholder: t('crud.tooltips.placeholders.probability')
        },
        {
          name: 'expected_revenue',
          label: t('crud.fields.expectedRevenue'),
          type: 'number',
          readOnly: true,
          placeholder: t('crud.tooltips.placeholders.autoCalculated')
        },
        {
          name: 'expected_close_date',
          label: t('crud.fields.expectedCloseDate'),
          type: 'date',
          placeholder: t('crud.tooltips.placeholders.expectedCloseDate')
        },
        {
          name: 'actual_close_date',
          label: t('crud.fields.actualCloseDate'),
          type: 'date',
          placeholder: t('crud.tooltips.placeholders.actualCloseDate')
        }
      ],
      layout: 'grid',
      columns: 2
    },
    {
      key: 'quelle_und_marketing',
      label: t('crud.detail.sourceAndMarketing'),
      fields: [
        {
          name: 'lead_source',
          label: t('crud.fields.leadSource'),
          type: 'text',
          placeholder: t('crud.tooltips.placeholders.leadSource')
        },
        {
          name: 'source',
          label: t('crud.fields.source'),
          type: 'select',
          options: [
            { value: 'web', label: t('crud.sources.web') },
            { value: 'referral', label: t('crud.sources.referral') },
            { value: 'email', label: t('crud.sources.email') },
            { value: 'phone', label: t('crud.sources.phone') },
            { value: 'trade_show', label: t('crud.sources.tradeShow') },
            { value: 'other', label: t('crud.sources.other') }
          ]
        },
        {
          name: 'campaign_id',
          label: t('crud.fields.campaign'),
          type: 'text',
          placeholder: t('crud.tooltips.placeholders.campaign')
        }
      ],
      layout: 'grid',
      columns: 2
    },
    {
      key: 'notizen',
      label: t('crud.detail.notes'),
      fields: [
        {
          name: 'notes',
          label: t('crud.fields.notes'),
          type: 'textarea',
          placeholder: t('crud.tooltips.placeholders.notes')
        }
      ],
      layout: 'grid',
      columns: 1
    }
  ],
  actions: [
    {
      key: 'save',
      label: t('crud.actions.save'),
      type: 'primary'
    },
    {
      key: 'cancel',
      label: t('crud.actions.cancel'),
      type: 'secondary'
    },
    {
      key: 'convertToQuote',
      label: t('crud.actions.convertToQuote'),
      type: 'default'
    },
    {
      key: 'markAsWon',
      label: t('crud.actions.markAsWon'),
      type: 'default'
    },
    {
      key: 'markAsLost',
      label: t('crud.actions.markAsLost'),
      type: 'secondary'
    }
  ],
  api: {
    baseUrl: '/api/crm-sales/opportunities',
    endpoints: {
      get: '/api/crm-sales/opportunities/{id}',
      create: '/api/crm-sales/opportunities',
      update: '/api/crm-sales/opportunities/{id}',
      delete: '/api/crm-sales/opportunities/{id}'
    }
  },
  permissions: ['crm.read', 'sales.read', 'sales.write']
})

// History Component
function OpportunityHistoryTab({ opportunityId }: { opportunityId: string }) {
  const { t } = useTranslation()
  const [history, setHistory] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const loadHistory = async () => {
      try {
        const response = await apiClient.get(`/opportunities/${opportunityId}/history`)
        if (response.success) {
          setHistory(response.data || [])
        }
      } catch (error) {
        console.error('Fehler beim Laden der History:', error)
      } finally {
        setLoading(false)
      }
    }
    if (opportunityId) {
      loadHistory()
    }
  }, [opportunityId])

  if (loading) {
    return <div className="p-4">Lade History...</div>
  }

  if (history.length === 0) {
    return <div className="p-4 text-muted-foreground">{t('crud.messages.noHistory')}</div>
  }

  return (
    <div className="space-y-4">
      {history.map((entry) => (
        <Card key={entry.id}>
          <CardContent className="pt-4">
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <div className="font-medium">{entry.field_name}</div>
                <div className="text-sm text-muted-foreground mt-1">
                  {entry.old_value && (
                    <span className="line-through text-red-600">{entry.old_value}</span>
                  )}
                  {entry.old_value && entry.new_value && ' → '}
                  {entry.new_value && (
                    <span className="text-green-600">{entry.new_value}</span>
                  )}
                </div>
                {entry.change_reason && (
                  <div className="text-xs text-muted-foreground mt-1">
                    {t('crud.fields.reason')}: {entry.change_reason}
                  </div>
                )}
              </div>
              <div className="text-right text-sm text-muted-foreground">
                <div>{entry.changed_by}</div>
                <div>{formatDate(entry.changed_at)}</div>
              </div>
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  )
}

// Quotes Component
function OpportunityQuotesTab({ opportunityId }: { opportunityId: string }) {
  const { t } = useTranslation()
  const [quotes, setQuotes] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const loadQuotes = async () => {
      try {
        // TODO: Implement quotes API endpoint
        // const response = await apiClient.get(`/opportunities/${opportunityId}/quotes`)
        // if (response.success) {
        //   setQuotes(response.data || [])
        // }
        setQuotes([]) // Placeholder
      } catch (error) {
        console.error('Fehler beim Laden der Quotes:', error)
      } finally {
        setLoading(false)
      }
    }
    if (opportunityId) {
      loadQuotes()
    }
  }, [opportunityId])

  if (loading) {
    return <div className="p-4">Lade Quotes...</div>
  }

  if (quotes.length === 0) {
    return (
      <div className="p-4 text-center">
        <FileText className="h-12 w-12 mx-auto text-muted-foreground mb-2" />
        <p className="text-muted-foreground">{t('crud.messages.noQuotes')}</p>
        <Button className="mt-4" onClick={() => {
          // TODO: Navigate to create quote page
          toast({
            title: t('crud.messages.comingSoon'),
            description: t('crud.messages.quoteCreationComingSoon')
          })
        }}>
          {t('crud.actions.createQuote')}
        </Button>
      </div>
    )
  }

  return (
    <div className="space-y-4">
      {quotes.map((quote) => (
        <Card key={quote.id}>
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              <span>{quote.quote_number}</span>
              <Badge>{quote.status}</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <div className="text-sm text-muted-foreground">{t('crud.fields.totalAmount')}</div>
                <div className="font-medium">{formatCurrency(quote.total_amount, quote.currency || 'EUR')}</div>
              </div>
              <div>
                <div className="text-sm text-muted-foreground">{t('crud.fields.validUntil')}</div>
                <div>{quote.valid_until ? formatDate(quote.valid_until) : '-'}</div>
              </div>
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  )
}

export default function OpportunityDetailPage(): JSX.Element {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const { id } = useParams<{ id: string }>()
  const [loading, setLoading] = useState(false)
  const [activeTab, setActiveTab] = useState('grundinformationen')
  const entityType = 'opportunity'
  const entityTypeLabel = getEntityTypeLabel(t, entityType, 'Opportunity')
  const opportunityConfig = createOpportunityConfig(t, entityTypeLabel)
  const isNew = !id || id === 'neu' || id === 'new'

  const { data, saveData, isLoading: dataLoading } = useMaskData({
    apiUrl: opportunityConfig.api.baseUrl,
    id: id || undefined
  })

  const { validate } = useMaskValidation({
    schema: createOpportunitySchema(t)
  })

  const handleSave = async (formData: any) => {
    setLoading(true)
    try {
      // Calculate expected_revenue if amount and probability are provided
      if (formData.amount && formData.probability) {
        formData.expected_revenue = formData.amount * (formData.probability / 100)
      }

      // Set owner_id from assigned_to if not provided
      if (!formData.owner_id && formData.assigned_to) {
        formData.owner_id = formData.assigned_to
      }

      // Validate
      const validationResult = validate(formData)
      if (!validationResult.valid) {
        toast({
          variant: 'destructive',
          title: t('crud.messages.validationError'),
          description: validationResult.errors.join(', ')
        })
        return
      }

      await saveData(formData)
      toast({
        title: getSuccessMessage(t, isNew ? 'create' : 'update', entityType),
      })
      navigate('/crm/opportunities')
    } catch (error: any) {
      console.error('Save error:', error)
      toast({
        variant: 'destructive',
        title: getErrorMessage(t, isNew ? 'create' : 'update', entityType),
        description: error.message || t('crud.messages.unknownError')
      })
    } finally {
      setLoading(false)
    }
  }

  const handleCancel = () => {
    if (confirm(t('crud.messages.discardChanges'))) {
      navigate('/crm/opportunities')
    }
  }

  const handleAction = async (action: string, formData: any) => {
    if (action === 'convertToQuote') {
      // TODO: Implement convert to quote
      toast({
        title: t('crud.messages.comingSoon'),
        description: t('crud.messages.convertToQuoteComingSoon')
      })
    } else if (action === 'markAsWon' && id) {
      try {
        await apiClient.put(`/opportunities/${id}`, {
          status: 'closed_won',
          actual_close_date: new Date().toISOString()
        })
        toast({
          title: getSuccessMessage(t, 'update', entityType),
        })
        navigate('/crm/opportunities')
      } catch (error) {
        toast({
          variant: 'destructive',
          title: getErrorMessage(t, 'update', entityType)
        })
      }
    } else if (action === 'markAsLost' && id) {
      try {
        await apiClient.put(`/opportunities/${id}`, {
          status: 'closed_lost'
        })
        toast({
          title: getSuccessMessage(t, 'update', entityType),
        })
        navigate('/crm/opportunities')
      } catch (error) {
        toast({
          variant: 'destructive',
          title: getErrorMessage(t, 'update', entityType)
        })
      }
    }
  }

  if (dataLoading && !isNew) {
    return (
      <div className="flex items-center justify-center p-8">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto mb-2"></div>
          <p>{t('crud.messages.loading')}</p>
        </div>
      </div>
    )
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <Button variant="ghost" onClick={() => navigate('/crm/opportunities')} className="mb-2">
            <ArrowLeft className="h-4 w-4 mr-2" />
            {t('crud.actions.back')}
          </Button>
          <h1 className="text-3xl font-bold">
            {isNew 
              ? t('crud.actions.create', { entityType: entityTypeLabel })
              : getDetailTitle(t, entityTypeLabel, data?.number || id || '')
            }
          </h1>
        </div>
      </div>

      <div className="grid grid-cols-4 gap-4">
        <div className="col-span-3">
          <ObjectPage
            config={opportunityConfig}
            data={data}
            onSave={handleSave}
            onCancel={handleCancel}
            onAction={handleAction}
            isLoading={loading || dataLoading}
          />
        </div>

        {!isNew && id && (
          <div className="col-span-1 space-y-4">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <History className="h-5 w-5" />
                  {t('crud.detail.history')}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <OpportunityHistoryTab opportunityId={id} />
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileText className="h-5 w-5" />
                  {t('crud.detail.quotes')}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <OpportunityQuotesTab opportunityId={id} />
              </CardContent>
            </Card>
          </div>
        )}
      </div>
    </div>
  )
}

