import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { ObjectPage } from '@/components/mask-builder'
import { useMaskData, useMaskActions } from '@/components/mask-builder/hooks'
import { MaskConfig } from '@/components/mask-builder/types'
import { getFieldsFromMaskConfig, validateFields } from '@/components/mask-builder/validation'
import { getEntityTypeLabel } from '@/features/crud/utils/i18n-helpers'
import { StornoDialog } from '@/components/finance/StornoDialog'
import { ModuleToolbar } from '@/components/navigation/ModuleToolbar'
import { LeaveConfirmDialog } from '@/components/LeaveConfirmDialog'
import { useUnsavedChanges } from '@/hooks/useUnsavedChanges'
import { financeService } from '@/lib/services/finance-service'
import { toast } from '@/hooks/use-toast'
import { apiClient } from '@/lib/api-client'


// Konfiguration für Buchungserfassung ObjectPage (wird in Komponente mit i18n erstellt)
const createBuchungConfig = (t: any, entityTypeLabel: string): MaskConfig => ({
  title: entityTypeLabel,
  subtitle: t('crud.fields.manualBooking'),
  type: 'object-page',
  tabs: [
    {
      key: 'allgemein',
      label: t('crud.detail.basicInfo'),
      fields: [
        {
          name: 'belegart',
          label: t('crud.fields.documentType'),
          type: 'select',
          required: true,
          options: [
            { value: 'RE', label: t('crud.fields.documentTypeRE') },
            { value: 'GUT', label: t('crud.fields.documentTypeGUT') },
            { value: 'STORNO', label: t('crud.fields.documentTypeSTORNO') },
            { value: 'KASSE', label: t('crud.fields.documentTypeKASSE') },
            { value: 'BANK', label: t('crud.fields.documentTypeBANK') }
          ]
        },
        {
          name: 'belegnummer',
          label: t('crud.fields.documentNumber'),
          type: 'text',
          required: true,
          placeholder: t('crud.tooltips.placeholders.autoGenerated')
        },
        {
          name: 'buchungsdatum',
          label: t('crud.fields.bookingDate'),
          type: 'date',
          required: true
        },
        {
          name: 'periode',
          label: t('crud.fields.period'),
          type: 'text',
          required: true,
          placeholder: t('crud.tooltips.placeholders.period'),
          pattern: '^\\d{4}-\\d{2}$'
        } as any,
        {
          name: 'buchungstext',
          label: t('crud.fields.bookingText'),
          type: 'text',
          required: true,
          placeholder: t('crud.tooltips.placeholders.bookingText')
        }
      ],
      layout: 'grid',
      columns: 2
    },
    {
      key: 'buchungszeilen',
      label: t('crud.fields.bookingLines'),
      fields: []
    } as any,
    {
      key: 'buchungszeilen_custom',
      label: '',
      fields: [],
      customRender: (_data: any, onChange: (_data: any) => void) => (
        <BuchungszeilenTable
          data={_data.buchungszeilen || []}
          onChange={(zeilen) => {
            const gesamtSoll = zeilen.reduce((sum: number, z: any) => sum + (z.soll || 0), 0)
            const gesamtHaben = zeilen.reduce((sum: number, z: any) => sum + (z.haben || 0), 0)
            onChange({
              ..._data,
              buchungszeilen: zeilen,
              gesamtSoll,
              gesamtHaben,
              differenz: gesamtSoll - gesamtHaben
            })
          }}
        />
      )
    },
    {
      key: 'summen',
      label: t('crud.fields.sumCheck'),
      fields: [
        {
          name: 'gesamtSoll',
          label: t('crud.fields.totalDebit'),
          type: 'number',
          readonly: true,
          step: 0.01
        },
        {
          name: 'gesamtHaben',
          label: t('crud.fields.totalCredit'),
          type: 'number',
          readonly: true,
          step: 0.01
        },
        {
          name: 'differenz',
          label: t('crud.fields.difference'),
          type: 'number',
          readonly: true,
          step: 0.01,
          helpText: t('crud.tooltips.fields.differenceMustBeZeroForValidBooking')
        }
      ],
      layout: 'grid',
      columns: 3
    },
    {
      key: 'anhaenge',
      label: t('crud.fields.attachments'),
      fields: [
        {
          name: 'belegUpload',
          label: t('crud.fields.uploadDocument'),
          type: 'file',
          accept: '.pdf,.jpg,.jpeg,.png',
          helpText: t('crud.tooltips.fields.gobdDocumentArchiving')
        } as any
      ]
    }
  ],
  actions: [
    { key: 'validate', label: t('crud.actions.validate'), type: 'secondary' },
    { key: 'save', label: t('crud.actions.book'), type: 'primary' },
    { key: 'storno', label: t('crud.actions.reverse'), type: 'danger' },
    { key: 'export', label: t('crud.actions.datevExport'), type: 'secondary' }
  ],
  api: {
    baseUrl: '/api/v1/journal-entries',
    endpoints: {
      list: '/api/v1/journal-entries',
      get: '/api/v1/journal-entries/{id}',
      create: '/api/v1/journal-entries',
      update: '/api/v1/journal-entries/{id}',
      delete: '/api/v1/journal-entries/{id}'
    }
  } as any,
  permissions: ['fibu.read', 'fibu.write']
})

// Buchungszeilen-Tabelle Komponente
function BuchungszeilenTable({ data: _data, onChange }: { data: any[], onChange: (_data: any[]) => void }) {
  const { t } = useTranslation()
  const addRow = () => {
    onChange([..._data, {
      konto: '',
      soll: 0,
      haben: 0,
      steuerschluessel: '',
      kostenstelle: '',
      kostentraeger: '',
      beleg: ''
    }])
  }

  const updateRow = (index: number, field: string, value: any) => {
    const newData = [..._data]
    newData[index] = { ...newData[index], [field]: value }
    onChange(newData)
  }

  const removeRow = (index: number) => {
    onChange(_data.filter((_, i) => i !== index))
  }

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center">
        <h3 className="text-lg font-semibold">{t('crud.fields.bookingLines')}</h3>
        <button
          onClick={addRow}
          className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
        >
          + {t('crud.actions.addLine')}
        </button>
      </div>

      <div className="overflow-x-auto">
        <table className="min-w-full border border-gray-300">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-4 py-2 border">{t('crud.fields.account')}</th>
              <th className="px-4 py-2 border">{t('crud.fields.debit')}</th>
              <th className="px-4 py-2 border">{t('crud.fields.credit')}</th>
              <th className="px-4 py-2 border">{t('crud.fields.tax')}</th>
              <th className="px-4 py-2 border">{t('crud.fields.costCenter')}</th>
              <th className="px-4 py-2 border">{t('crud.fields.costCarrier')}</th>
              <th className="px-4 py-2 border">{t('crud.actions.delete')}</th>
            </tr>
          </thead>
          <tbody>
            {_data.map((row, index) => (
              <tr key={index} className="border">
                <td className="px-4 py-2 border">
                  <input
                    type="text"
                    value={row.konto}
                    onChange={(e) => updateRow(index, 'konto', e.target.value)}
                    className="w-full p-1 border rounded"
                    placeholder={t('crud.tooltips.placeholders.accountNumber')}
                  />
                </td>
                <td className="px-4 py-2 border">
                  <input
                    type="number"
                    step="0.01"
                    value={row.soll}
                    onChange={(e) => updateRow(index, 'soll', parseFloat(e.target.value) || 0)}
                    className="w-full p-1 border rounded"
                  />
                </td>
                <td className="px-4 py-2 border">
                  <input
                    type="number"
                    step="0.01"
                    value={row.haben}
                    onChange={(e) => updateRow(index, 'haben', parseFloat(e.target.value) || 0)}
                    className="w-full p-1 border rounded"
                  />
                </td>
                <td className="px-4 py-2 border">
                  <input
                    type="text"
                    value={row.steuerschluessel}
                    onChange={(e) => updateRow(index, 'steuerschluessel', e.target.value)}
                    className="w-full p-1 border rounded"
                    placeholder={t('crud.tooltips.placeholders.taxKey')}
                  />
                </td>
                <td className="px-4 py-2 border">
                  <input
                    type="text"
                    value={row.kostenstelle}
                    onChange={(e) => updateRow(index, 'kostenstelle', e.target.value)}
                    className="w-full p-1 border rounded"
                  />
                </td>
                <td className="px-4 py-2 border">
                  <input
                    type="text"
                    value={row.kostentraeger}
                    onChange={(e) => updateRow(index, 'kostentraeger', e.target.value)}
                    className="w-full p-1 border rounded"
                  />
                </td>
                <td className="px-4 py-2 border">
                  <button
                    onClick={() => removeRow(index)}
                    className="px-2 py-1 bg-red-600 text-white rounded hover:bg-red-700"
                  >
                    ✕
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default function BuchungserfassungPage(): JSX.Element {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const [isDirty, setIsDirty] = useState(false)
  const [isStornoDialogOpen, setIsStornoDialogOpen] = useState(false)
  const [isStornoLoading, setIsStornoLoading] = useState(false)
  const [actionLoadingKey, setActionLoadingKey] = useState<string | null>(null)
  const entityType = 'booking'
  const entityTypeLabel = getEntityTypeLabel(t, entityType, 'Buchungserfassung')
  const buchungConfig = createBuchungConfig(t, entityTypeLabel)

  const { data, loading } = useMaskData({
    apiUrl: buchungConfig.api.baseUrl,
    id: 'new'
  })
  const initialFormData = {
    belegart: 'BANK',
    belegnummer: '',
    buchungsdatum: new Date().toISOString().slice(0, 10),
    periode: new Date().toISOString().slice(0, 7),
    buchungstext: '',
    gesamtSoll: 0,
    gesamtHaben: 0,
    differenz: 0,
    buchungszeilen: [],
  }
  const [latestFormData, setLatestFormData] = useState<any>(null)
  const formData = { ...initialFormData, ...(data ?? {}) }

  const validate = (formData: any) => {
    const errors = validateFields(getFieldsFromMaskConfig(buchungConfig), formData ?? {})
    const buchungszeilen = Array.isArray(formData?.buchungszeilen) ? formData.buchungszeilen : []

    if (buchungszeilen.length === 0) {
      errors.buchungszeilen = t('crud.messages.validationError')
    }

    if (Math.abs((formData?.gesamtSoll ?? 0) - (formData?.gesamtHaben ?? 0)) >= 0.01) {
      errors.differenz = t('crud.messages.debitCreditMustBalance')
    }

    return errors
  }
  const showValidationToast = (errors: Record<string, string>) => {
    toast({
      variant: 'destructive',
      title: t('crud.messages.validationError'),
      description: `${Object.keys(errors).length} Feld(er) muessen korrigiert werden.`,
    })
  }

  const { handleAction } = useMaskActions(async (action: string, formData: any) => {
    if (action === 'save') {
      const errors = validate(formData)
      if (Object.keys(errors).length > 0) {
        showValidationToast(errors)
        return
      }
      setActionLoadingKey('save')
      try {
        const period = String(formData?.periode ?? '').trim()
        if (period) {
          const periodCheck = (await apiClient.get<{ is_open: boolean; message: string }>(`/api/v1/finance/periods/check/${period}`)).data
          if (!periodCheck?.is_open) {
            throw new Error(periodCheck?.message || `Periode ${period} ist gesperrt.`)
          }
        }
        const postRes = (await apiClient.post<{ success: boolean; message: string }>('/api/v1/finance/journal-entries/post', formData ?? {})).data
        if (!postRes?.success) {
          throw new Error(postRes?.message || 'Buchung konnte nicht verbucht werden')
        }
        toast({ title: t('crud.messages.bookingValidationSuccess', { defaultValue: 'Buchung gebucht' }) })
        setIsDirty(false)
        navigate('/finance/buchungen')
      } catch (error: any) {
        const msg = error.response?.data?.detail ?? error.message
        toast({ variant: 'destructive', title: t('common.error'), description: msg })
      } finally {
        setActionLoadingKey(null)
      }
      return
    }
    if (action === 'validate') {
      const errors = validate(formData)
      if (Object.keys(errors).length === 0) {
        toast({ title: t('crud.messages.bookingValidationSuccess', { defaultValue: 'Validierung erfolgreich' }) })
      } else {
        showValidationToast(errors)
      }
      return
    }
    if (action === 'storno') {
      // Prüfe ob Buchung bereits gespeichert wurde
      if (!formData.id && !formData.belegnummer) {
        toast({
          variant: 'destructive',
          title: t('common.error'),
          description: t('crud.messages.saveFirst'),
        })
        return
      }
      setIsStornoDialogOpen(true)
    }
    if (action === 'export') {
      setActionLoadingKey('export')
      try {
        const res = (await apiClient.post<{ url?: string }>('/api/v1/export/list', { entity: 'journal_entries', format: 'datev' })).data
        if (res?.url) window.open(res.url, '_blank')
        toast({ title: t('crud.actions.datevExport'), description: t('crud.messages.exportCreated', { defaultValue: 'Export erstellt' }) })
      } catch (error: any) {
        const msg = error.response?.data?.detail ?? error.message
        toast({ variant: 'destructive', title: t('common.error'), description: msg })
      } finally {
        setActionLoadingKey(null)
      }
    }
  })

  const handleSave = async (formData: any) => {
    await handleAction('save', formData)
  }

  const handleCancel = () => {
    navigate('/finance/buchungen')
  }

  const blocker = useUnsavedChanges(isDirty)

  const handleStornoConfirm = async (reason: string) => {
    setIsStornoLoading(true)
    try {
      const entryId = data?.id || data?.belegnummer
      if (!entryId) {
        throw new Error('Buchung-ID nicht gefunden')
      }

      await financeService.reverseJournalEntry(entryId, reason)
      
      toast({
        title: t('crud.messages.stornoSuccess'),
        description: t('crud.messages.stornoSuccess'),
      })
      
      setIsStornoDialogOpen(false)
      navigate('/finance/buchungen')
    } catch (error) {
      toast({
        variant: 'destructive',
        title: t('crud.messages.stornoError'),
        description: error instanceof Error ? error.message : t('common.unknownError'),
      })
    } finally {
      setIsStornoLoading(false)
    }
  }

  return (
    <>
      <ModuleToolbar
        backTarget="/finance/buchungen"
        closeTarget="/finance/buchungen"
        title={entityTypeLabel}
      />
      <LeaveConfirmDialog
        blocker={blocker}
        onSave={() => handleSave(latestFormData ?? formData)}
        title={t('crud.messages.unsavedChanges', { defaultValue: 'Ungespeicherte Änderungen' })}
        description={t('crud.messages.unsavedChangesDescription', { defaultValue: 'Möchten Sie speichern, verwerfen oder hier bleiben?' })}
      />
      <ObjectPage
        config={buchungConfig}
        data={formData}
        onChange={(value) => { setLatestFormData(value); setIsDirty(true) }}
        onSave={handleSave}
        onCancel={handleCancel}
        isLoading={loading}
        onAction={(key, formData) => handleAction(key, formData)}
        loadingActionKey={actionLoadingKey}
      />
      <StornoDialog
        open={isStornoDialogOpen}
        onOpenChange={setIsStornoDialogOpen}
        onConfirm={handleStornoConfirm}
        entryNumber={data?.belegnummer}
        entryDate={data?.buchungsdatum}
        isLoading={isStornoLoading}
      />
    </>
  )
}
