import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { ObjectPage } from '@/components/mask-builder'
import { useMaskData, useMaskValidation, useMaskActions } from '@/components/mask-builder/hooks'
import { MaskConfig } from '@/components/mask-builder/types'
import { z } from 'zod'
import { getEntityTypeLabel } from '@/features/crud/utils/i18n-helpers'
import { StornoDialog } from '@/components/finance/StornoDialog'
import { financeService } from '@/lib/services/finance-service'
import { toast } from '@/hooks/use-toast'

// Zod-Schema für Buchungserfassung (wird in Komponente mit i18n erstellt)
const createBuchungSchema = (t: any) => z.object({
  belegart: z.enum(['RE', 'GUT', 'STORNO', 'KASSE', 'BANK'], {
    errorMap: () => ({ message: t('crud.messages.validationError') })
  }),
  belegnummer: z.string().min(1, t('crud.messages.validationError')),
  buchungsdatum: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, t('crud.messages.validationError')),
  periode: z.string().regex(/^\d{4}-\d{2}$/, t('crud.messages.validationError')),
  buchungstext: z.string().min(1, t('crud.messages.validationError')),
  gesamtSoll: z.number().min(0, t('crud.messages.validationError')),
  gesamtHaben: z.number().min(0, t('crud.messages.validationError')),
  differenz: z.number().max(0.01, t('crud.messages.validationError')).min(-0.01),
  buchungszeilen: z.array(z.object({
    konto: z.string().min(1, t('crud.messages.validationError')),
    soll: z.number().min(0),
    haben: z.number().min(0),
    steuerschluessel: z.string().optional(),
    kostenstelle: z.string().optional(),
    kostentraeger: z.string().optional(),
    beleg: z.string().optional()
  })).min(1, t('crud.messages.validationError'))
}).refine((data) => Math.abs(data.gesamtSoll - data.gesamtHaben) < 0.01, {
  message: t('crud.messages.debitCreditMustBalance'),
  path: ["differenz"]
})

// Konfiguration für Buchungserfassung ObjectPage (wird in Komponente mit i18n erstellt)
const createBuchungConfig = (t: any, entityTypeLabel: string): MaskConfig => ({
  title: entityTypeLabel,
  subtitle: t('crud.fields.manualBooking'),
  type: 'object-page',
  tabs: [
    {
      key: 'allgemein',
      label: t('crud.detail.basicInfo'),
      fields: [
        {
          name: 'belegart',
          label: t('crud.fields.documentType'),
          type: 'select',
          required: true,
          options: [
            { value: 'RE', label: t('crud.fields.documentTypeRE') },
            { value: 'GUT', label: t('crud.fields.documentTypeGUT') },
            { value: 'STORNO', label: t('crud.fields.documentTypeSTORNO') },
            { value: 'KASSE', label: t('crud.fields.documentTypeKASSE') },
            { value: 'BANK', label: t('crud.fields.documentTypeBANK') }
          ]
        },
        {
          name: 'belegnummer',
          label: t('crud.fields.documentNumber'),
          type: 'text',
          required: true,
          placeholder: t('crud.tooltips.placeholders.autoGenerated')
        },
        {
          name: 'buchungsdatum',
          label: t('crud.fields.bookingDate'),
          type: 'date',
          required: true
        },
        {
          name: 'periode',
          label: t('crud.fields.period'),
          type: 'text',
          required: true,
          placeholder: t('crud.tooltips.placeholders.period'),
          pattern: '^\\d{4}-\\d{2}$'
         } as any, {},
        {
          name: 'buchungstext',
          label: t('crud.fields.bookingText'),
          type: 'text',
          required: true,
          placeholder: t('crud.tooltips.placeholders.bookingText')
        }
      ],
      layout: 'grid',
      columns: 2
    },
    {
      key: 'buchungszeilen',
      label: t('crud.fields.bookingLines'),
      fields: []
    } as any,
    {
      key: 'buchungszeilen_custom',
      label: '',
      fields: [],
      customRender: (_data: any, onChange: (_data: any) => void) => (
        <BuchungszeilenTable
          data={_data.buchungszeilen || []}
          onChange={(zeilen) => {
            const gesamtSoll = zeilen.reduce((sum: number, z: any) => sum + (z.soll || 0), 0)
            const gesamtHaben = zeilen.reduce((sum: number, z: any) => sum + (z.haben || 0), 0)
            onChange({
              ..._data,
              buchungszeilen: zeilen,
              gesamtSoll,
              gesamtHaben,
              differenz: gesamtSoll - gesamtHaben
            })
          }}
        />
      )
    },
    {
      key: 'summen',
      label: t('crud.fields.sumCheck'),
      fields: [
        {
          name: 'gesamtSoll',
          label: t('crud.fields.totalDebit'),
          type: 'number',
          readonly: true,
          step: 0.01
        },
        {
          name: 'gesamtHaben',
          label: t('crud.fields.totalCredit'),
          type: 'number',
          readonly: true,
          step: 0.01
        },
        {
          name: 'differenz',
          label: t('crud.fields.difference'),
          type: 'number',
          readonly: true,
          step: 0.01,
          helpText: t('crud.tooltips.fields.differenceMustBeZeroForValidBooking')
        }
      ],
      layout: 'grid',
      columns: 3
    },
    {
      key: 'anhaenge',
      label: t('crud.fields.attachments'),
      fields: [
        {
          name: 'belegUpload',
          label: t('crud.fields.uploadDocument'),
          type: 'file',
          accept: '.pdf,.jpg,.jpeg,.png',
           } as any, {helpText: t('crud.tooltips.fields.gobdDocumentArchiving')
        }
      ]
    }
  ],
  actions: [
    {
      key: 'validate',
      label: t('crud.actions.validate'),
      type: 'secondary'
    , onClick: () => {} },
    {
      key: 'save',
      label: t('crud.actions.book'),
      type: 'primary'
    , onClick: () => {} },
    {
      key: 'storno',
      label: t('crud.actions.reverse'),
      type: 'danger'
    , onClick: () => {} },
    {
      key: 'export',
      label: t('crud.actions.datevExport'),
      type: 'secondary'
    , onClick: () => {} }
  ],
  api: {
    baseUrl: '/api/finance/buchungen',
    endpoints: {
      list: '/api/finance/buchungen',
      get: '/api/finance/buchungen/{id}',
      create: '/api/finance/buchungen',
      update: '/api/finance/buchungen/{id}',
      delete: '/api/finance/buchungen/{id}'
    }
  } as any,
  validation: createBuchungSchema(t),
  permissions: ['fibu.read', 'fibu.write']
})

// Buchungszeilen-Tabelle Komponente
function BuchungszeilenTable({ data: _data, onChange }: { data: any[], onChange: (_data: any[]) => void }) {
  const { t } = useTranslation()
  const addRow = () => {
    onChange([..._data, {
      konto: '',
      soll: 0,
      haben: 0,
      steuerschluessel: '',
      kostenstelle: '',
      kostentraeger: '',
      beleg: ''
    }])
  }

  const updateRow = (index: number, field: string, value: any) => {
    const newData = [..._data]
    newData[index] = { ...newData[index], [field]: value }
    onChange(newData)
  }

  const removeRow = (index: number) => {
    onChange(_data.filter((_, i) => i !== index))
  }

  return (
    <div className="space-y-4">
      <div className="flex justify-between items-center">
        <h3 className="text-lg font-semibold">{t('crud.fields.bookingLines')}</h3>
        <button
          onClick={addRow}
          className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
        >
          + {t('crud.actions.addLine')}
        </button>
      </div>

      <div className="overflow-x-auto">
        <table className="min-w-full border border-gray-300">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-4 py-2 border">{t('crud.fields.account')}</th>
              <th className="px-4 py-2 border">{t('crud.fields.debit')}</th>
              <th className="px-4 py-2 border">{t('crud.fields.credit')}</th>
              <th className="px-4 py-2 border">{t('crud.fields.tax')}</th>
              <th className="px-4 py-2 border">{t('crud.fields.costCenter')}</th>
              <th className="px-4 py-2 border">{t('crud.fields.costCarrier')}</th>
              <th className="px-4 py-2 border">{t('crud.actions.delete')}</th>
            </tr>
          </thead>
          <tbody>
            {_data.map((row, index) => (
              <tr key={index} className="border">
                <td className="px-4 py-2 border">
                  <input
                    type="text"
                    value={row.konto}
                    onChange={(e) => updateRow(index, 'konto', e.target.value)}
                    className="w-full p-1 border rounded"
                    placeholder={t('crud.tooltips.placeholders.accountNumber')}
                  />
                </td>
                <td className="px-4 py-2 border">
                  <input
                    type="number"
                    step="0.01"
                    value={row.soll}
                    onChange={(e) => updateRow(index, 'soll', parseFloat(e.target.value) || 0)}
                    className="w-full p-1 border rounded"
                  />
                </td>
                <td className="px-4 py-2 border">
                  <input
                    type="number"
                    step="0.01"
                    value={row.haben}
                    onChange={(e) => updateRow(index, 'haben', parseFloat(e.target.value) || 0)}
                    className="w-full p-1 border rounded"
                  />
                </td>
                <td className="px-4 py-2 border">
                  <input
                    type="text"
                    value={row.steuerschluessel}
                    onChange={(e) => updateRow(index, 'steuerschluessel', e.target.value)}
                    className="w-full p-1 border rounded"
                    placeholder={t('crud.tooltips.placeholders.taxKey')}
                  />
                </td>
                <td className="px-4 py-2 border">
                  <input
                    type="text"
                    value={row.kostenstelle}
                    onChange={(e) => updateRow(index, 'kostenstelle', e.target.value)}
                    className="w-full p-1 border rounded"
                  />
                </td>
                <td className="px-4 py-2 border">
                  <input
                    type="text"
                    value={row.kostentraeger}
                    onChange={(e) => updateRow(index, 'kostentraeger', e.target.value)}
                    className="w-full p-1 border rounded"
                  />
                </td>
                <td className="px-4 py-2 border">
                  <button
                    onClick={() => removeRow(index)}
                    className="px-2 py-1 bg-red-600 text-white rounded hover:bg-red-700"
                  >
                    ✕
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

export default function BuchungserfassungPage(): JSX.Element {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const [isDirty, setIsDirty] = useState(false)
  const [isStornoDialogOpen, setIsStornoDialogOpen] = useState(false)
  const [isStornoLoading, setIsStornoLoading] = useState(false)
  const entityType = 'booking'
  const entityTypeLabel = getEntityTypeLabel(t, entityType, 'Buchungserfassung')
  const buchungConfig = createBuchungConfig(t, entityTypeLabel)

  const { data, loading, saveData } = useMaskData({
    apiUrl: buchungConfig.api.baseUrl,
    id: 'new'
  })

  const { validate, showValidationToast } = useMaskValidation(buchungConfig.validation)

  const { handleAction } = useMaskActions(async (action: string, formData: any) => {
    if (action === 'save') {
      const isValid = validate(formData)
      if (!isValid.isValid) {
        showValidationToast(isValid.errors)
        return
      }

      try {
        await saveData(formData)
        setIsDirty(false)
        navigate('/finance/buchungen')
      } catch (error) {
        // Error wird bereits in useMaskData behandelt
      }
    } else if (action === 'validate') {
      const isValid = validate(formData)
      if (isValid.isValid) {
        alert(t('crud.messages.bookingValidationSuccess'))
      } else {
        showValidationToast(isValid.errors)
      }
    } else if (action === 'storno') {
      // Prüfe ob Buchung bereits gespeichert wurde
      if (!formData.id && !formData.belegnummer) {
        toast({
          variant: 'destructive',
          title: t('common.error'),
          description: t('crud.messages.saveFirst'),
        })
        return
      }
      setIsStornoDialogOpen(true)
    } else if (action === 'export') {
      window.open('/api/finance/buchungen/export', '_blank')
    }
  })

  const handleSave = async (formData: any) => {
    await handleAction('save', formData)
  }

  const handleCancel = () => {
    if (isDirty && !confirm(t('crud.messages.unsavedChanges'))) {
      return
    }
    navigate('/finance/buchungen')
  }

  const handleStornoConfirm = async (reason: string) => {
    setIsStornoLoading(true)
    try {
      const entryId = data?.id || data?.belegnummer
      if (!entryId) {
        throw new Error('Buchung-ID nicht gefunden')
      }

      await financeService.reverseJournalEntry(entryId, reason)
      
      toast({
        title: t('crud.messages.stornoSuccess'),
        description: t('crud.messages.stornoSuccess'),
      })
      
      setIsStornoDialogOpen(false)
      navigate('/finance/buchungen')
    } catch (error) {
      toast({
        variant: 'destructive',
        title: t('crud.messages.stornoError'),
        description: error instanceof Error ? error.message : t('common.unknownError'),
      })
    } finally {
      setIsStornoLoading(false)
    }
  }

  return (
    <>
      <ObjectPage
        config={buchungConfig}
        data={data}
        onSave={handleSave}
        onCancel={handleCancel}
        isLoading={loading}
      />
      <StornoDialog
        open={isStornoDialogOpen}
        onOpenChange={setIsStornoDialogOpen}
        onConfirm={handleStornoConfirm}
        entryNumber={data?.belegnummer}
        entryDate={data?.buchungsdatum}
        isLoading={isStornoLoading}
      />
    </>
  )
}