import { Euro, FileText, Leaf, Package, Search, ShieldCheck, ShoppingCart, Target, Truck, Users, Zap } from 'lucide-react'
import type { AiShortcut } from '@/app/navigation/types'
import { resolveRoutePathFromModule } from '@/app/navigation/route-paths'

export const AI_SHORTCUTS: AiShortcut[] = [
  {
    id: 'ai-ask-valeo',
    label: 'Ask VALEO (AI-Copilot)',
    icon: Zap,
    type: 'event',
    eventName: 'open-ask-valeo',
    keywords: ['ai', 'copilot', 'assistant'],
  },
  {
    id: 'ai-search',
    label: 'Semantische Suche',
    icon: Search,
    type: 'event',
    eventName: 'open-semantic-search',
    keywords: ['search', 'semantic'],
  },
  {
    id: 'ai-compliance',
    label: 'Compliance-Check durchfuehren',
    icon: ShieldCheck,
    type: 'navigate',
    path: resolveRoutePathFromModule('@/pages/admin/compliance-dashboard', 'admin/compliance'),
    keywords: ['compliance', 'audit'],
  },
  {
    id: 'ai-voice-lager',
    label: 'Lager - Voice-Befehl',
    icon: Package,
    type: 'event',
    eventName: 'voice-intent',
    eventPayload: { domain: 'lager' },
    keywords: ['lager', 'wareneingang', 'inventur', 'umlagerung', 'voice'],
  },
  {
    id: 'ai-voice-einkauf',
    label: 'Einkauf - Voice-Befehl',
    icon: ShoppingCart,
    type: 'event',
    eventName: 'voice-intent',
    eventPayload: { domain: 'einkauf' },
    keywords: ['einkauf', 'bestellung', 'lieferant', 'voice', 'beschaffung'],
  },
  {
    id: 'ai-voice-hr',
    label: 'Personal - Voice-Befehl',
    icon: Users,
    type: 'event',
    eventName: 'voice-intent',
    eventPayload: { domain: 'hr' },
    keywords: ['personal', 'hr', 'mitarbeiter', 'abwesenheit', 'lohnlauf', 'voice'],
  },
  {
    id: 'ai-voice-verkauf',
    label: 'Verkauf - Voice-Befehl',
    icon: FileText,
    type: 'event',
    eventName: 'voice-intent',
    eventPayload: { domain: 'sales' },
    keywords: ['verkauf', 'angebot', 'lieferschein', 'auftrag', 'voice', 'vertrieb'],
  },
  {
    id: 'ai-voice-crm',
    label: 'CRM - Voice-Befehl',
    icon: Target,
    type: 'event',
    eventName: 'voice-intent',
    eventPayload: { domain: 'crm' },
    keywords: ['crm', 'lead', 'kontakt', 'aktivitaet', 'marketing', 'voice'],
  },
  {
    id: 'ai-voice-fibu',
    label: 'Finanzen - Voice-Befehl',
    icon: Euro,
    type: 'event',
    eventName: 'voice-intent',
    eventPayload: { domain: 'finance' },
    keywords: ['fibu', 'buchhaltung', 'buchung', 'op', 'zahlungslauf', 'voice'],
  },
  {
    id: 'ai-voice-compliance',
    label: 'Compliance - Voice-Befehl',
    icon: ShieldCheck,
    type: 'event',
    eventName: 'voice-intent',
    eventPayload: { domain: 'compliance' },
    keywords: ['compliance', 'dsgvo', 'datenpanne', 'sanktion', 'voice'],
  },
  {
    id: 'ai-voice-agrar',
    label: 'Agrar - Voice-Befehl',
    icon: Leaf,
    type: 'event',
    eventName: 'voice-intent',
    eventPayload: { domain: 'agrar' },
    keywords: ['agrar', 'ernte', 'feldbuch', 'silo', 'schlag', 'voice'],
  },
  {
    id: 'ai-voice-logistik',
    label: 'Logistik - Voice-Befehl',
    icon: Truck,
    type: 'event',
    eventName: 'voice-intent',
    eventPayload: { domain: 'logistics' },
    keywords: ['logistik', 'tour', 'fracht', 'versand', 'voice'],
  },
]
