import {
  Activity,
  ArrowUpDown,
  AlertCircle,
  BarChart3,
  Building2,
  Calendar,
  Calculator,
  Database,
  Euro,
  FileDown,
  FileText,
  Globe,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Package,
  RefreshCw,
  Scale,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sprout,
  Target,
  Tractor,
  Truck,
  Upload,
  UserCog,
  Users,
  Zap,
  Plus,
  Search,
} from 'lucide-react'
import { resolveRoutePathFromModule } from '@/app/navigation/route-paths'
import { ENABLE_PROSPECTING_UI } from '@/features/prospecting/feature-flags'

type MCPInfo = {
  businessDomain: string
  scope: string
}

export type RawNavItem = {
  id: string
  label: string
  icon: typeof LayoutDashboard
  module?: string
  /**
   * When the preferred URL differs from the auto-derived path (e.g. landing page).
   */
  preferredPath?: string
  path?: string
  keywords?: string[]
  mcp: MCPInfo
  featureKey?: 'agrar'
  children?: RawNavItem[]
}

export type NavItem = Omit<RawNavItem, 'children'> & {
  path?: string
  children?: NavItem[]
}

export type NavigationShortcut = {
  id: string
  label: string
  icon: typeof LayoutDashboard
  path: string
  keywords?: string[]
}

export type ActionShortcut = {
  id: string
  label: string
  icon: typeof LayoutDashboard
  path: string
  keywords?: string[]
}

export type AiShortcut =
  | {
      id: string
      label: string
      icon: typeof LayoutDashboard
      type: 'event'
      eventName: string
      keywords?: string[]
    }
  | {
      id: string
      label: string
      icon: typeof LayoutDashboard
      type: 'navigate'
      path: string
      keywords?: string[]
    }

const CRM_CHILDREN: RawNavItem[] = [
  {
    id: 'kontakte',
    label: 'Kontakte',
    icon: Users,
    module: '@/pages/crm/kontakte-liste',
    keywords: ['kontakte'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'leads',
    label: 'Leads',
    icon: Target,
    module: '@/pages/crm/leads',
    keywords: ['leads'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'aktivitaeten',
    label: 'Aktivitäten',
    icon: Calendar,
    module: '@/pages/crm/aktivitaeten',
    keywords: ['aktivitäten'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'betriebsprofile',
    label: 'Betriebsprofile',
    icon: Tractor,
    module: '@/pages/crm/betriebsprofile-liste',
    keywords: ['betriebsprofile'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'kampagnen',
    label: 'Kampagnen',
    icon: Zap,
    module: '@/pages/crm/campaigns',
    preferredPath: 'crm/campaigns',
    keywords: ['kampagnen', 'marketing', 'campaign'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'kampagnen-vorlagen',
    label: 'Kampagnen-Vorlagen',
    icon: FileText,
    module: '@/pages/crm/campaign-templates',
    preferredPath: 'crm/campaign-templates',
    keywords: ['vorlagen', 'templates', 'kampagnen'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'kampagnen-performance',
    label: 'Kampagnen-Performance',
    icon: BarChart3,
    module: '@/pages/crm/campaign-performance-dashboard',
    preferredPath: 'crm/campaign-performance',
    keywords: ['performance', 'analytics', 'kampagnen'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'segmente',
    label: 'Segmente',
    icon: Users,
    module: '@/pages/crm/segments',
    preferredPath: 'crm/segments',
    keywords: ['segmente', 'zielgruppen'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'einwilligungen',
    label: 'Einwilligungen',
    icon: ShieldCheck,
    module: '@/pages/crm/consent-management',
    preferredPath: 'crm/consents',
    keywords: ['consent', 'einwilligung', 'dsgvo'],
    mcp: { businessDomain: 'crm', scope: 'compliance:read' },
  },
  {
    id: 'dsgvo-anfragen',
    label: 'DSGVO-Anfragen',
    icon: ShieldCheck,
    module: '@/pages/crm/gdpr-requests',
    preferredPath: 'crm/gdpr-requests',
    keywords: ['dsgvo', 'gdpr', 'datenschutz'],
    mcp: { businessDomain: 'crm', scope: 'compliance:read' },
  },
]

if (ENABLE_PROSPECTING_UI) {
  CRM_CHILDREN.splice(2, 0, {
    id: 'prospecting',
    label: 'Prospecting',
    icon: Search,
    module: '@/pages/prospecting/LeadExplorer',
    preferredPath: 'prospecting/leads',
    keywords: ['prospecting', 'gap', 'potenzial'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  })
}

const NAV_SECTIONS_CONFIG: RawNavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    module: '@/pages/start-dashboard',
    preferredPath: '/',
    mcp: { businessDomain: 'core', scope: 'core:read' },
  },
  {
    id: 'verkauf',
    label: 'Verkauf',
    icon: ShoppingCart,
    mcp: { businessDomain: 'sales', scope: 'sales:read' },
    children: [
      {
        id: 'sales-dashboard',
        label: 'Dashboard',
        icon: BarChart3,
        module: '@/pages/dashboard/sales-dashboard',
        preferredPath: 'dashboard/sales',
        keywords: ['dashboard', 'kpi', 'analytics'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'angebot',
        label: 'Angebote',
        icon: FileText,
        module: '@/pages/sales/angebot-erstellen',
        preferredPath: 'sales/angebote',
        keywords: ['angebot', 'angebot-erfassung', 'angebot-erstellen'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'auftrag',
        label: 'Aufträge',
        icon: FileText,
        module: '@/pages/sales/order-editor',
        preferredPath: 'sales/order',
        keywords: ['aufträge'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'lieferung',
        label: 'Lieferungen',
        icon: Truck,
        module: '@/pages/verkauf/lieferschein-erfassung',
        preferredPath: 'verkauf/lieferschein-erfassung',
        keywords: ['lieferungen', 'lieferschein'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'rechnung',
        label: 'Rechnungen',
        icon: FileText,
        module: '@/pages/sales/invoice-editor',
        preferredPath: 'sales/invoice',
        keywords: ['rechnungen'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kunden',
        label: 'Kunden',
        icon: Users,
        module: '@/pages/verkauf/kunden-liste',
        preferredPath: 'verkauf/kunden-liste',
        keywords: ['kunden', 'crm', 'customer'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'artikel',
        label: 'Artikel',
        icon: Package,
        module: '@/pages/artikel/liste',
        keywords: ['artikel', 'products', 'lager'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'unerledigte-auftrags-positionen',
        label: 'Unerledigte Auftrags-Positionen',
        icon: AlertCircle,
        module: '@/pages/verkauf/unerledigte-auftrags-positionen',
        preferredPath: 'verkauf/unerledigte-auftrags-positionen',
        keywords: ['unerledigte', 'auftrags', 'positionen', 'offene'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kommissions-auftraege',
        label: 'Kommissions-Aufträge',
        icon: FileText,
        module: '@/pages/verkauf/kommissions-auftraege',
        preferredPath: 'verkauf/kommissions-auftraege',
        keywords: ['kommissions', 'aufträge', 'kommission'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'betriebs-auftraege',
        label: 'Betriebs-Aufträge',
        icon: FileText,
        module: '@/pages/verkauf/betriebs-auftraege',
        preferredPath: 'verkauf/betriebs-auftraege',
        keywords: ['betriebs', 'aufträge', 'interne aufträge'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'analytics',
        label: 'Analytics',
        icon: BarChart3,
        module: '@/pages/analytics',
        keywords: ['analytics'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'reports',
        label: 'Berichte',
        icon: FileText,
        module: '@/pages/reports',
        keywords: ['berichte', 'reports'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
    ],
  },
  {
    id: 'crm',
    label: 'CRM & Marketing',
    icon: UserCog,
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
    children: CRM_CHILDREN,
  },
  {
    id: 'einkauf',
    label: 'Einkauf',
    icon: ShoppingCart,
    mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
    children: [
      {
        id: 'einkauf-dashboard',
        label: 'Dashboard',
        icon: BarChart3,
        module: '@/pages/dashboard/einkauf-dashboard',
        preferredPath: 'dashboard/einkauf',
        keywords: ['dashboard', 'einkauf'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlaege',
        label: 'Bestellvorschläge',
        icon: AlertCircle,
        module: '@/pages/einkauf/bestellvorschlaege',
        keywords: ['bestellvorschläge'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlag-lager',
        label: 'Bestellvorschlag Lager',
        icon: Package,
        module: '@/pages/einkauf/bestellvorschlag-lager',
        preferredPath: 'einkauf/bestellvorschlag-lager',
        keywords: ['bestellvorschlag', 'lager', 'mindestbestand'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlag-verkauf',
        label: 'Bestellvorschlag Verkauf',
        icon: ShoppingCart,
        module: '@/pages/einkauf/bestellvorschlag-verkauf',
        preferredPath: 'einkauf/bestellvorschlag-verkauf',
        keywords: ['bestellvorschlag', 'verkauf', 'aufträge'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlag-rohware',
        label: 'Bestellvorschlag Rohstoff',
        icon: Sprout,
        module: '@/pages/einkauf/bestellvorschlag-rohware',
        preferredPath: 'einkauf/bestellvorschlag-rohware',
        keywords: ['bestellvorschlag', 'rohstoff', 'bedarf', 'rohware'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellungen',
        label: 'Bestellungen',
        icon: FileText,
        module: '@/pages/einkauf/bestellungen-liste',
        preferredPath: 'einkauf/bestellungen',
        keywords: ['bestellungen'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'einkauf-lieferschein-erfassung',
        label: 'Eingehende Belege',
        icon: FileText,
        module: '@/pages/einkauf/lieferschein-erfassung',
        preferredPath: 'einkauf/lieferschein-erfassung',
        keywords: ['eingehende belege', 'einkauf lieferschein', 'wareneingang', 'kreditor'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferschein-frachtauftrag',
        label: 'Lieferschein/Frachtauftrag',
        icon: Truck,
        module: '@/pages/einkauf/lieferschein-frachtauftrag',
        preferredPath: 'einkauf/lieferschein-frachtauftrag',
        keywords: ['lieferschein', 'frachtauftrag'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'frachtauftraege-eingang',
        label: 'Frachtaufträge Eingang',
        icon: Truck,
        module: '@/pages/einkauf/frachtauftraege-eingang',
        preferredPath: 'einkauf/frachtauftraege-eingang',
        keywords: ['frachtaufträge', 'eingang', 'spediteur', 'pauschalfracht'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'wareneingang',
        label: 'Wareneingang',
        icon: Package,
        module: '@/pages/charge/wareneingang',
        keywords: ['wareneingang'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferanten',
        label: 'Lieferanten',
        icon: Users,
        module: '@/pages/einkauf/lieferanten-liste',
        keywords: ['lieferanten'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'warengruppen',
        label: 'Warengruppen',
        icon: Package,
        module: '@/pages/einkauf/warengruppen',
        keywords: ['warengruppen'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'anfragen',
        label: 'Anfragen (RFQ)',
        icon: FileText,
        module: '@/pages/einkauf/anfragen-liste',
        keywords: ['anfragen', 'rfq'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'anfrage-erfassung',
        label: 'Anfrage erfassen',
        icon: FileText,
        module: '@/pages/einkauf/anfrage-erfassung',
        preferredPath: 'einkauf/anfrage-erfassung',
        keywords: ['anfrage', 'rfq', 'erfassen', 'lieferant'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'angebote-einkauf',
        label: 'Angebote',
        icon: FileText,
        module: '@/pages/einkauf/angebote-liste',
        keywords: ['angebote', 'einkauf'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'rechnungseingaenge',
        label: 'Rechnungseingänge',
        icon: Euro,
        module: '@/pages/einkauf/rechnungseingaenge-liste',
        keywords: ['rechnungseingang', 'eingangsrechnung'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'rechnung-eingang-erfassung',
        label: 'Eingangsrechnung erfassen',
        icon: Euro,
        module: '@/pages/einkauf/rechnung-eingang-erfassung',
        preferredPath: 'einkauf/rechnung-eingang-erfassung',
        keywords: ['eingangsrechnung', 'rechnungseingang', 'erfassen', 'kreditor'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'rechnung-abgleich',
        label: 'Rechnungsabgleich',
        icon: Calculator,
        module: '@/pages/einkauf/rechnung-abgleich',
        keywords: ['abgleich', '3-wege'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'retouren',
        label: 'Retouren',
        icon: Truck,
        module: '@/pages/einkauf/retouren',
        keywords: ['retouren', 'rückgabe'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
      {
        id: 'disposition',
        label: 'Disposition',
        icon: Calculator,
        module: '@/pages/disposition/liste',
        keywords: ['disposition'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'commodity-position-matrix',
        label: 'Commodity Position Matrix',
        icon: LayoutGrid,
        module: '@/pages/disposition/LstCommodityPositionMatrix',
        preferredPath: 'disposition/position-matrix',
        keywords: ['position', 'matrix', 'long', 'short', 'deckung'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'position-regeln',
        label: 'Position-Regeln',
        icon: Settings,
        module: '@/pages/disposition/FrmPositionRules',
        preferredPath: 'disposition/regeln',
        keywords: ['position', 'regeln', 'toleranz'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'coverage-monitor',
        label: 'Coverage Monitor',
        icon: AlertCircle,
        module: '@/pages/disposition/FrmCoverageMonitor',
        preferredPath: 'disposition/coverage-monitor',
        keywords: ['coverage', 'deckung', 'lücken'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferantenbewertung',
        label: 'Lieferantenbewertung',
        icon: ShieldCheck,
        module: '@/pages/einkauf/lieferantenbewertung',
        keywords: ['lieferanten', 'bewertung', 'score'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferanten-dokumente',
        label: 'Lieferanten-Dokumente',
        icon: FileText,
        module: '@/pages/einkauf/lieferanten-dokumente',
        keywords: ['supplier', 'dokumente', 'nachweise'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
      {
        id: 'service-entry-sheets',
        label: 'Service Entry Sheets',
        icon: FileText,
        module: '@/pages/einkauf/service-entry-sheets',
        keywords: ['ses', 'service entry', 'leistung'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
      {
        id: 'audit-drilldown',
        label: 'Audit Drilldown',
        icon: Activity,
        module: '@/pages/einkauf/audit-drilldown',
        keywords: ['audit', 'belegkette', 'drilldown'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'edi-portal',
        label: 'EDI Portal',
        icon: Activity,
        module: '@/pages/einkauf/edi-portal',
        keywords: ['edi', 'portal', 'ordner', 'messages'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
    ],
  },
  {
    id: 'fibu',
    label: 'Finanzbuchhaltung',
    icon: Euro,
    mcp: { businessDomain: 'finance', scope: 'finance:read' },
    children: [
      {
        id: 'hauptbuch',
        label: 'Hauptbuch',
        icon: FileText,
        module: '@/pages/fibu/hauptbuch',
        keywords: ['hauptbuch'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'debitoren',
        label: 'Debitoren',
        icon: Users,
        module: '@/pages/fibu/debitoren',
        keywords: ['debitoren'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'kreditoren',
        label: 'Kreditoren',
        icon: Users,
        module: '@/pages/fibu/kreditoren',
        keywords: ['kreditoren'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'buchungsjournal',
        label: 'Buchungsjournal',
        icon: FileText,
        module: '@/pages/fibu/buchungsjournal',
        keywords: ['buchungsjournal'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'kontenplan',
        label: 'Kontenplan',
        icon: FileText,
        module: '@/pages/fibu/kontenplan',
        keywords: ['kontenplan'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'bilanz',
        label: 'Bilanz',
        icon: BarChart3,
        module: '@/pages/fibu/bilanz',
        keywords: ['bilanz'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'guv',
        label: 'GuV',
        icon: BarChart3,
        module: '@/pages/fibu/guv',
        keywords: ['guv'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'bwa',
        label: 'BWA',
        icon: BarChart3,
        module: '@/pages/fibu/bwa',
        keywords: ['bwa'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'anlagen',
        label: 'Anlagenbuchhaltung',
        icon: Building2,
        module: '@/pages/fibu/anlagen',
        keywords: ['anlagen'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'op-verwaltung',
        label: 'OP-Verwaltung',
        icon: Euro,
        module: '@/pages/fibu/op-verwaltung',
        keywords: ['op', 'verwaltung'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'offene-posten',
        label: 'Offene Posten',
        icon: Euro,
        module: '@/pages/fibu/offene-posten',
        keywords: ['offene posten', 'op', 'forderungen'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'abschluss-cockpit',
        label: 'Abschluss-Cockpit',
        icon: ShieldCheck,
        module: '@/pages/fibu/abschluss-cockpit',
        preferredPath: 'fibu/abschluss-cockpit',
        keywords: ['abschluss', 'cockpit', 'periodenabschluss'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'zahlungslaeufe',
        label: 'Zahlungsläufe',
        icon: Euro,
        module: '@/pages/fibu/zahlungslaeufe',
        keywords: ['zahlungsläufe', 'zahlung'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'zahlungseingaenge',
        label: 'Zahlungseingänge & Matching',
        icon: Euro,
        module: '@/pages/finance/payment-matching',
        preferredPath: 'finance/payments',
        keywords: ['zahlungseingang', 'bankimport', 'matching', 'op-zuordnung'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'bank-stamm',
        label: 'Bankkonten (Bankstamm)',
        icon: Building2,
        module: '@/pages/finance/bank-stamm',
        preferredPath: 'finance/bank-stamm',
        keywords: ['bank', 'bankkonto', 'bankstamm', 'iban', 'gegenkonto'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'op-debitoren-finance',
        label: 'OP Debitoren',
        icon: Euro,
        module: '@/pages/finance/op-debitoren',
        preferredPath: 'finance/op-debitoren',
        keywords: ['op', 'debitoren', 'ausgleich', 'forderungen'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'op-kreditoren-finance',
        label: 'OP Kreditoren',
        icon: Euro,
        module: '@/pages/finance/op-kreditoren',
        preferredPath: 'finance/op-kreditoren',
        keywords: ['op', 'kreditoren', 'ausgleich', 'verbindlichkeiten'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'nebenbuch-abstimmung',
        label: 'Nebenbuch-Abstimmung',
        icon: BarChart3,
        module: '@/pages/finance/nebenbuch-abstimmung',
        preferredPath: 'finance/nebenbuch-abstimmung',
        keywords: ['nebenbuch', 'abstimmung', 'debitoren', 'kreditoren', 'abschluss'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'kostenstellenrechnung',
        label: 'Kostenstellen',
        icon: Calculator,
        module: '@/pages/fibu/kostenstellenrechnung',
        keywords: ['kostenstellen', 'controlling'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'ustva',
        label: 'USt.-Voranmeldung',
        icon: FileText,
        module: '@/pages/export/umsatzsteuervoranmeldung',
        preferredPath: 'export/ustva',
        keywords: ['ustva'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'audit-trail-finance',
        label: 'Audit-Trail (GoBD)',
        icon: ShieldCheck,
        module: '@/pages/finance/audit-trail',
        keywords: ['audit', 'gobd', 'trail', 'hash'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'periodensteuerung',
        label: 'Periodensteuerung',
        icon: Calendar,
        module: '@/pages/finance/periods',
        preferredPath: 'finance/periods',
        keywords: ['perioden', 'sperre', 'abschluss', 'buchungsperiode'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'wechselkurse',
        label: 'Wechselkurse',
        icon: RefreshCw,
        module: '@/pages/finance/wechselkurse',
        keywords: ['wechselkurs', 'devisen', 'fremdwährung', 'ezb', 'kurs'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'buchungsvorlagen',
        label: 'Buchungsvorlagen',
        icon: FileText,
        module: '@/pages/finance/buchungsvorlagen',
        keywords: ['buchungsvorlage', 'vorlage', 'schema', 'automatisch', 'wiederkehrend'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'buchungsimport',
        label: 'Massen-Import',
        icon: Upload,
        module: '@/pages/finance/buchungsimport',
        keywords: ['buchungsimport', 'import', 'csv', 'massenbuchung', 'datev'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'uebernahme-tagesabschluss-pos',
        label: 'Übernahme Buchungen Tagesabschluss POS',
        icon: ShoppingCart,
        module: '@/pages/pos/tagesabschluss-enhanced',
        preferredPath: 'pos/tagesabschluss',
        keywords: ['übernahme', 'tagesabschluss', 'pos', 'kasse', 'fibu', 'buchung'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'buchungsuebernahme-connectors',
        label: 'Buchungsübernahme Connectors',
        icon: Zap,
        module: '@/pages/fibu/buchungsuebernahme-connectors',
        preferredPath: 'fibu/buchungsuebernahme-connectors',
        keywords: ['buchungsübernahme', 'connectors', 'lohn', 'anlagen', 'fibu'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'buchhaltungsuebersicht',
        label: 'Buchhaltungsübersicht',
        icon: BarChart3,
        module: '@/pages/fibu/buchhaltungsuebersicht',
        keywords: ['buchhaltungsübersicht', 'bilanz', 'guv', 'auswertung', 'fibu'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'monatswerte',
        label: 'Monatswerte für mehrere Monate',
        icon: BarChart3,
        module: '@/pages/fibu/monatswerte',
        keywords: ['monatswerte', 'bwa', 'mehrere monate', 'fibu', 'auswertung'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'uebernahme-kasse',
        label: 'Übernahme Kasse',
        icon: Database,
        module: '@/pages/pos/uebernahme-kasse',
        keywords: ['übernahme', 'kasse', 'sqlite', 'bewegungsdaten', 'serviceerp'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'ubergabe-fibu',
        label: 'Übergabe an FIBU',
        icon: FileDown,
        module: '@/pages/fibu/schnittstelle-fibu',
        keywords: ['übergabe', 'fibu', 'schnittstelle', 'buchungsübergabe', 'asc'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'schnittstelle-fibu',
        label: 'Schnittstelle FIBU',
        icon: FileDown,
        module: '@/pages/fibu/schnittstelle-fibu',
        keywords: ['schnittstelle', 'fibu', 'buchungsübergabe', 'export', 'asc'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'schnittstellen-center',
        label: 'Schnittstellen-Center',
        icon: LayoutDashboard,
        module: '@/pages/fibu/schnittstellen-center',
        keywords: ['schnittstellen', 'center', 'connectoren', 'datev', 'sepa', 'export', 'import'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'lohn-connector',
        label: 'Lohn-Connector',
        icon: Building2,
        module: '@/pages/fibu/lohn-connector',
        keywords: ['lohn', 'lexware', 'connector', 'lohnbuchungen'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'anlagen-suite',
        label: 'VALEO Suite Anlagen (Asset Ledger)',
        icon: LayoutGrid,
        module: '@/pages/fibu/anlagen-suite',
        keywords: ['anlagen', 'asset ledger', 'anlagenbuchhaltung', 'afa', 'abscheidung'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'atlas',
        label: 'ATLAS (Zoll)',
        icon: FileDown,
        module: '@/pages/fibu/atlas',
        keywords: ['atlas', 'zoll', 'zollanmeldung', 'ausfuhr', 'eu-übermittlung'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'elster-online',
        label: 'ELSTER (Online)',
        icon: FileText,
        module: '@/pages/fibu/elster-online',
        keywords: ['elster', 'ustva', 'lohnsteuer', 'einkommensteuer', 'finanzamt'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
    ],
  },
  {
    id: 'lager',
    label: 'Lager & Bestände',
    icon: Package,
    mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
    children: [
      {
        id: 'bestandsuebersicht',
        label: 'Bestandsübersicht',
        icon: Package,
        module: '@/pages/lager/bestandsuebersicht',
        keywords: ['bestandsübersicht'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'einlagerung',
        label: 'Einlagerung',
        icon: Truck,
        module: '@/pages/lager/einlagerung',
        keywords: ['einlagerung'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'auslagerung',
        label: 'Auslagerung',
        icon: Truck,
        module: '@/pages/lager/auslagerung',
        keywords: ['auslagerung'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'inventur',
        label: 'Inventur',
        icon: Scale,
        module: '@/pages/lager/inventur',
        keywords: ['inventur'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'lagerbewegungen',
        label: 'Lagerbewegungen',
        icon: ArrowUpDown,
        module: '@/pages/lager/lagerbewegungen',
        keywords: ['lagerbewegungen', 'buchungen', 'stock movements'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
    ],
  },
  {
    id: 'agrar',
    label: 'Agrar & Warenwirtschaft',
    icon: Sprout,
    featureKey: 'agrar',
    mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
    children: [
      {
        id: 'psm',
        label: 'Pflanzenschutz',
        icon: Leaf,
        module: '@/pages/agrar/psm/liste',
        preferredPath: 'agrar/psm',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'duenger',
        label: 'Dünger',
        icon: Sprout,
        module: '@/pages/agrar/duenger-liste',
        preferredPath: 'agrar/duenger-liste',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'saatgut',
        label: 'Saatgut',
        icon: Leaf,
        module: '@/pages/agrar/saatgut-liste',
        preferredPath: 'agrar/saatgut-liste',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'bodenproben',
        label: 'Bodenproben',
        icon: Scale,
        module: '@/pages/agrar/bodenproben/liste',
        preferredPath: 'agrar/bodenproben',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'ernte',
        label: 'Ernteplanung',
        icon: Tractor,
        module: '@/pages/agrar/ernte/liste',
        preferredPath: 'agrar/ernte',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'ernte-annahme',
        label: 'Ernte-Annahme',
        icon: Tractor,
        module: '@/pages/agrar/ernte-annahme-erfassung',
        preferredPath: 'agrar/ernte-annahme-erfassung',
        keywords: ['ernte', 'annahme', 'erfassung'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
      },
      {
        id: 'nawaro',
        label: 'NaWaRo',
        icon: Leaf,
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
        children: [
          {
            id: 'nawaro-mitteilung-drucken',
            label: 'Mitteilung drucken',
            icon: FileText,
            module: '@/pages/nawaro/mitteilung-drucken',
            preferredPath: 'nawaro/mitteilung-drucken',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'nawaro-vertraege',
            label: 'Vertraege',
            icon: FileText,
            module: '@/pages/nawaro/vertraege',
            preferredPath: 'nawaro/vertraege',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'nawaro-anbauflaechen',
            label: 'Anbauflaechen',
            icon: FileText,
            module: '@/pages/nawaro/anbauflaechen',
            preferredPath: 'nawaro/anbauflaechen',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'nawaro-raps-profil',
            label: 'Raps-Profil',
            icon: FileText,
            module: '@/pages/nawaro/raps-profil',
            preferredPath: 'nawaro/raps-profil',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
        ],
      },
      {
        id: 'feldbuch',
        label: 'Feldbuch',
        icon: FileText,
        module: '@/pages/agrar/feldbuch/schlagkartei',
        preferredPath: 'agrar/feldbuch/schlagkartei',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'futtermittel',
        label: 'Futtermittel',
        icon: Package,
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
        children: [
          {
            id: 'einzelfuttermittel',
            label: 'Einzelfuttermittel',
            icon: Package,
            module: '@/pages/futtermittel/einzelfuttermittel-liste',
            preferredPath: 'futtermittel/einzelfuttermittel-liste',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'mischfuttermittel',
            label: 'Mischfuttermittel',
            icon: Package,
            module: '@/pages/futtermittel/mischfuttermittel-liste',
            preferredPath: 'futtermittel/mischfuttermittel-liste',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'futtermittel-wareneingang',
            label: 'Wareneingang',
            icon: Truck,
            module: '@/pages/futtermittel/futtermittel-wareneingang',
            preferredPath: 'futtermittel/futtermittel-wareneingang',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'futtermittel-qualitaet',
            label: 'Qualitätskontrolle',
            icon: Activity,
            module: '@/pages/futtermittel/futtermittel-qualitaetskontrolle',
            preferredPath: 'futtermittel/futtermittel-qualitaetskontrolle',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'futtermittel-statistik',
            label: 'Statistik',
            icon: BarChart3,
            module: '@/pages/futtermittel/futtermittel-statistik',
            preferredPath: 'futtermittel/futtermittel-statistik',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
        ],
      },
    ],
  },
  {
    id: 'annahme',
    label: 'Annahme & Waage',
    icon: Truck,
    mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
    children: [
      {
        id: 'annahme-qr',
        label: 'QR-Code (Handy)',
        icon: Truck,
        module: '@/pages/annahme/annahme-qr',
        path: '/annahme/qr',
        keywords: ['qr', 'handy', 'mobil', 'scan'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'warteschlange',
        label: 'Warteschlange',
        icon: Truck,
        module: '@/pages/annahme/warteschlange',
        path: '/annahme/warteschlange',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'hofliste',
        label: 'Hofliste',
        icon: Scale,
        module: '@/pages/waage/hofliste',
        path: '/waage/hofliste',
        keywords: ['hofliste', 'hof', 'yard'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'waage-liste',
        label: 'Waagen',
        icon: Scale,
        module: '@/pages/waage/liste',
        path: '/waage/liste',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'wiegungen',
        label: 'Wiegungen',
        icon: FileText,
        module: '@/pages/waage/wiegungen',
        path: '/waage/wiegungen',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
    ],
  },
  {
    id: 'quality',
    label: 'Qualität & Compliance',
    icon: ShieldCheck,
    mcp: { businessDomain: 'quality', scope: 'quality:read' },
    children: [
      {
        id: 'qm-dokumente',
        label: 'QM-Dokumente',
        icon: FileText,
        module: '@/pages/document',
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
      {
        id: 'audit-trails',
        label: 'Audit Trails',
        icon: ShieldCheck,
        module: '@/pages/admin/audit-log',
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
      {
        id: 'compliance',
        label: 'Compliance Cockpit',
        icon: ShieldCheck,
        module: '@/pages/admin/compliance-dashboard',
        preferredPath: 'admin/compliance',
        keywords: ['compliance'],
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
    ],
  },
  {
    id: 'compliance',
    label: 'Compliance',
    icon: ShieldCheck,
    mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
    children: [
      {
        id: 'policies',
        label: 'Policies',
        icon: ShieldCheck,
        module: '@/pages/policy-manager',
        preferredPath: 'policies',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'zulassungen',
        label: 'Zulassungen',
        icon: FileText,
        module: '@/pages/compliance/zulassungen-register',
        path: '/compliance/zulassungen-register',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'export-pruefprotokoll',
        label: 'Export-Protokoll',
        icon: FileText,
        module: '@/pages/compliance/export-pruefprotokoll',
        path: '/compliance/export-pruefprotokoll',
        keywords: ['export', 'gefahrstoff', 'naehrstoff', 'trace'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'meldewesen',
        label: 'Meldewesen',
        icon: FileText,
        module: '@/pages/compliance/meldewesen-konsole',
        path: '/compliance/meldewesen-konsole',
        keywords: ['meldewesen', 'intrastat', 'mvo', 'eudr'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'eudr',
        label: 'EUDR-Compliance',
        icon: Leaf,
        module: '@/pages/nachhaltigkeit/eudr-compliance',
        path: '/nachhaltigkeit/eudr-compliance',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'labor',
        label: 'Labor',
        icon: FileText,
        module: '@/pages/qualitaet/labor-liste',
        path: '/qualitaet/labor-liste',
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
      {
        id: 'zertifikate',
        label: 'Zertifikate',
        icon: ShieldCheck,
        module: '@/pages/zertifikate/liste',
        path: '/zertifikate/liste',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
    ],
  },
  {
    id: 'logistik',
    label: 'Logistik',
    icon: Truck,
    mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
    children: [
      {
        id: 'tourenplanung',
        label: 'Tourenplanung',
        icon: Truck,
        module: '@/pages/logistik/tourenplanung',
        preferredPath: 'logistik/tourenplanung',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'frachtbriefe',
        label: 'Frachtbriefe',
        icon: Target,
        module: '@/pages/logistik/frachtbriefe',
        preferredPath: 'logistik/frachtbriefe',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'fuhrpark',
        label: 'Fuhrpark',
        icon: Truck,
        module: '@/pages/fuhrpark/uebersicht',
        preferredPath: 'fuhrpark/uebersicht',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
        children: [
          {
            id: 'fuhrpark-dashboard',
            label: 'Übersicht',
            icon: BarChart3,
            module: '@/pages/fuhrpark/uebersicht',
            preferredPath: 'fuhrpark/uebersicht',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'fuhrpark-fahrzeuge',
            label: 'Fahrzeuge',
            icon: Truck,
            module: '@/pages/fuhrpark/fahrzeuge',
            preferredPath: 'fuhrpark/fahrzeuge',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'fuhrpark-stammdaten',
            label: 'Stammdaten',
            icon: Settings,
            module: '@/pages/fuhrpark/fuhrpark-stammdaten',
            preferredPath: 'fuhrpark/fuhrpark-stammdaten',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'fuhrpark-rechnungen',
            label: 'Rechnungen',
            icon: FileText,
            module: '@/pages/fuhrpark/fuhrpark-rechnungen',
            preferredPath: 'fuhrpark/fuhrpark-rechnungen',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'fuhrpark-auswertungen',
            label: 'Auswertungen',
            icon: BarChart3,
            module: '@/pages/fuhrpark/fuhrpark-auswertung-kosten-pro-fahrzeug',
            preferredPath: 'fuhrpark/fuhrpark-auswertung-kosten-pro-fahrzeug',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'fuhrpark-ausgehende-belege-dokumente',
            label: 'Ausgehende Belege & Dokumente',
            icon: FileText,
            module: '@/pages/fuhrpark/ausgehende-belege-dokumente',
            preferredPath: 'fuhrpark/ausgehende-belege-dokumente',
            keywords: ['belege', 'dokumente', 'versand', 'druck'],
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
        ],
      },
      {
        id: 'strecke',
        label: 'Strecke',
        icon: Truck,
        module: '@/pages/strecke/menu',
        preferredPath: 'strecke/menu',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
        children: [
          {
            id: 'strecke-menu',
            label: 'Menue',
            icon: Truck,
            module: '@/pages/strecke/menu',
            preferredPath: 'strecke/menu',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'strecke-streckengeschaeft',
            label: 'Streckengeschaeft',
            icon: FileText,
            module: '@/pages/strecke/streckengeschaeft',
            preferredPath: 'strecke/streckengeschaeft',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'strecke-disposition',
            label: 'Strecken-Disposition',
            icon: Truck,
            module: '@/pages/strecke/disposition',
            preferredPath: 'strecke/disposition',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'strecke-vorlaeufig',
            label: 'Vorlaeufige Streckengeschaefte',
            icon: FileText,
            module: '@/pages/strecke/vorlaeufige-streckengeschaefte',
            preferredPath: 'strecke/vorlaeufige-streckengeschaefte',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'strecke-dokumente-drucken',
            label: 'Strecken-Dokumente drucken',
            icon: FileText,
            module: '@/pages/strecke/dokumente-drucken',
            preferredPath: 'strecke/dokumente-drucken',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'strecke-qualitaets-abweichung',
            label: 'Qualitaets-Abweichung',
            icon: AlertCircle,
            module: '@/pages/strecke/qualitaets-abweichung',
            preferredPath: 'strecke/qualitaets-abweichung',
            mcp: { businessDomain: 'quality', scope: 'quality:read' },
          },
          {
            id: 'strecke-fracht-preise',
            label: 'Speditionen / Fracht-Preise',
            icon: Euro,
            module: '@/pages/strecke/speditionen-fracht-preise',
            preferredPath: 'strecke/speditionen-fracht-preise',
            keywords: ['fracht', 'preise', 'plz', 'spedition'],
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'strecke-nawaro-vertraege-pruefen',
            label: 'NaWaRo-Vertraege pruefen',
            icon: ShieldCheck,
            module: '@/pages/strecke/nawaro-vertraege-pruefen',
            preferredPath: 'strecke/nawaro-vertraege-pruefen',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'strecke-nawaro-uebersicht',
            label: 'NaWaRo-Uebersicht',
            icon: BarChart3,
            module: '@/pages/strecke/nawaro-uebersicht',
            preferredPath: 'strecke/nawaro-uebersicht',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'strecke-nawaro-uebersicht-drucken',
            label: 'NaWaRo-Uebersicht drucken',
            icon: FileText,
            module: '@/pages/strecke/nawaro-uebersicht-drucken',
            preferredPath: 'strecke/nawaro-uebersicht-drucken',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'strecke-nawaro-lieferungen',
            label: 'NaWaRo-Lieferungen',
            icon: Truck,
            module: '@/pages/strecke/nawaro-lieferungen',
            preferredPath: 'strecke/nawaro-lieferungen',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'strecke-nawaro-ernterklaerung-drucken',
            label: 'NaWaRo-Ernterklaerung drucken',
            icon: FileText,
            module: '@/pages/strecke/nawaro-ernterklaerung-drucken',
            preferredPath: 'strecke/nawaro-ernterklaerung-drucken',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
        ],
      },
    ],
  },
  {
    id: 'versand',
    label: 'Versand',
    icon: Truck,
    mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
    children: [
      {
        id: 'versand-paket-etikett',
        label: 'Paket-Etikett',
        icon: FileText,
        module: '@/pages/versand/paket-etikett',
        preferredPath: 'versand/paket-etikett',
        keywords: ['paket', 'etikett', 'label', 'versand'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
      {
        id: 'versand-frachtdokumente',
        label: 'Frachtdokumente',
        icon: FileText,
        module: '@/pages/versand/frachtdokumente',
        preferredPath: 'versand/frachtdokumente',
        keywords: ['fracht', 'dokumente', 'frachtbrief', 'versand'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
      {
        id: 'versand-avis',
        label: 'Versand-Avis',
        icon: Truck,
        module: '@/pages/versand/versand-avis',
        preferredPath: 'versand/versand-avis',
        keywords: ['avis', 'versand', 'ankündigung'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
    ],
  },
  {
    id: 'produktion',
    label: 'Produktion',
    icon: Settings,
    mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
    children: [
      {
        id: 'produktions-dokumente-drucken',
        label: 'Produktions-Dokumente drucken',
        icon: FileText,
        module: '@/pages/produktion/produktions-dokumente-drucken',
        preferredPath: 'produktion/produktions-dokumente-drucken',
        keywords: ['produktion', 'dokumente', 'drucken', 'produkt'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
    ],
  },
  {
    id: 'pos',
    label: 'POS & Filialen',
    icon: Euro,
    mcp: { businessDomain: 'pos', scope: 'pos:read' },
    children: [
      {
        id: 'pos-terminal',
        label: 'POS Terminal',
        icon: Euro,
        module: '@/pages/pos/terminal',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
      {
        id: 'tse-journal',
        label: 'TSE Journal',
        icon: FileText,
        module: '@/pages/pos/tse-journal',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
      {
        id: 'tagesabschluss',
        label: 'Tagesabschluss',
        icon: Calculator,
        module: '@/pages/pos/tagesabschluss-enhanced',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
      {
        id: 'gift-cards',
        label: 'Geschenkkarten',
        icon: Euro,
        module: '@/pages/pos/gift-cards',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
      {
        id: 'rabatte',
        label: 'Rabatte',
        icon: Euro,
        module: '@/pages/pos/rabatte',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
    ],
  },
  {
    id: 'personal',
    label: 'Personal',
    icon: Users,
    mcp: { businessDomain: 'hr', scope: 'hr:read' },
    children: [
      {
        id: 'mitarbeiter-liste',
        label: 'Mitarbeiter',
        icon: Users,
        module: '@/pages/personal/mitarbeiter-liste',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'zeiterfassung',
        label: 'Zeiterfassung',
        icon: Calendar,
        module: '@/pages/personal/zeiterfassung',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'stundenzettel',
        label: 'Stundenzettel',
        icon: FileText,
        module: '@/pages/personal/stundenzettel-liste',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'schulungen',
        label: 'Schulungen',
        icon: UserCog,
        module: '@/pages/personal/schulungen',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'qualifikationen',
        label: 'Qualifikationen',
        icon: UserCog,
        module: '@/pages/personal/qualifikationen',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'onboarding',
        label: 'Onboarding',
        icon: Users,
        module: '@/pages/personal/onboarding',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'schichtplan',
        label: 'Schichtplan',
        icon: Calendar,
        module: '@/pages/schichtplan/liste',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
    ],
  },
  {
    id: 'controlling',
    label: 'Controlling',
    icon: BarChart3,
    mcp: { businessDomain: 'finance', scope: 'finance:read' },
    children: [
      {
        id: 'plan-ist',
        label: 'Plan/Ist-Vergleich',
        icon: BarChart3,
        module: '@/pages/controlling/plan-ist',
        keywords: ['plan', 'ist', 'controlling'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'kpi-verwaltung',
        label: 'KPI-Verwaltung',
        icon: Settings,
        module: '@/pages/controlling/kpi-verwaltung',
        keywords: ['kpi', 'controlling', 'dashboard'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'dashboard-verwaltung',
        label: 'Dashboard-Verwaltung',
        icon: LayoutDashboard,
        module: '@/pages/controlling/dashboard-verwaltung',
        keywords: ['dashboard', 'controlling', 'widgets'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'widget-verwaltung',
        label: 'Widget-Verwaltung',
        icon: Settings,
        module: '@/pages/controlling/widget-verwaltung',
        keywords: ['widget', 'dashboard', 'controlling'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'timeseries-erfassung',
        label: 'Timeseries-Erfassung',
        icon: BarChart3,
        module: '@/pages/controlling/timeseries-erfassung',
        keywords: ['timeseries', 'kpi', 'controlling'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'massnahmen',
        label: 'Massnahmen',
        icon: FileText,
        module: '@/pages/controlling/massnahmen',
        keywords: ['massnahmen', 'actions', 'controlling'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'deckungsbeitrag',
        label: 'Deckungsbeitrag',
        icon: Calculator,
        module: '@/pages/reports/deckungsbeitrag',
        keywords: ['deckungsbeitrag', 'db'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'liquiditaet',
        label: 'Liquiditätsplanung',
        icon: Euro,
        module: '@/pages/finanzplanung/liquiditaet',
        keywords: ['liquidität', 'cashflow'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'executive-dashboard',
        label: 'Geschäftsführung',
        icon: LayoutDashboard,
        module: '@/pages/management/executive-dashboard',
        keywords: ['executive', 'geschäftsführung', 'management'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
    ],
  },
  {
    id: 'workflow',
    label: 'Workflows',
    icon: Zap,
    mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
    children: [
      {
        id: 'workflow-monitoring',
        label: 'Monitoring',
        icon: Activity,
        module: '@/pages/workflow/workflow-monitoring',
        keywords: ['workflow', 'monitoring'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
      {
        id: 'workflow-regeln',
        label: 'Regeln',
        icon: Settings,
        module: '@/pages/workflow/workflow-regeln',
        keywords: ['workflow', 'regeln', 'rules'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:write' },
      },
      {
        id: 'workflow-approval',
        label: 'Freigaben',
        icon: ShieldCheck,
        module: '@/pages/workflows/approval',
        keywords: ['freigabe', 'approval', 'genehmigung'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:write' },
      },
    ],
  },
  {
    id: 'admin',
    label: 'Administration',
    icon: Settings,
    mcp: { businessDomain: 'admin', scope: 'admin:read' },
    children: [
      {
        id: 'benutzer',
        label: 'Benutzer',
        icon: Users,
        module: '@/pages/admin/benutzer-liste',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'rollen-verwaltung',
        label: 'Rollen',
        icon: UserCog,
        module: '@/pages/admin/rollen-verwaltung',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'audit-log',
        label: 'Audit-Log',
        icon: FileText,
        module: '@/pages/admin/audit-log',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'report-berechtigungen',
        label: 'Report-Berechtigungen',
        icon: ShieldCheck,
        module: '@/pages/admin/report-berechtigungen',
        preferredPath: 'admin/report-berechtigungen',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'monitoring',
        label: 'Monitoring',
        icon: AlertCircle,
        module: '@/pages/admin/monitoring/alerts',
        preferredPath: 'monitoring/alerts',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'monitoring-regeln',
        label: 'Monitoring-Regeln',
        icon: Settings,
        module: '@/pages/admin/monitoring/regeln',
        preferredPath: 'monitoring/regeln',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'integrationen-quarantaene',
        label: 'Integrationen-Quarantaene',
        icon: AlertCircle,
        module: '@/pages/admin/integrationen-quarantaene',
        preferredPath: 'admin/integrationen-quarantaene',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'compliance-dashboard',
        label: 'Compliance',
        icon: ShieldCheck,
        module: '@/pages/admin/compliance-dashboard',
        preferredPath: 'admin/compliance',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      ...(ENABLE_PROSPECTING_UI
        ? [
            {
              id: 'gap-pipeline',
              label: 'GAP-Pipeline',
              icon: BarChart3,
              module: '@/pages/admin/GapPipelineConsole',
              preferredPath: 'admin/gap-pipeline',
              keywords: ['gap', 'pipeline', 'prospecting', 'import'],
              mcp: { businessDomain: 'admin', scope: 'admin:write' },
            },
          ]
        : []),
      {
        id: 'system-einstellungen',
        label: 'System',
        icon: Settings,
        module: '@/pages/einstellungen/system',
        preferredPath: 'einstellungen/system',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
    ],
  },
  {
    id: 'kundenportal',
    label: 'Kundenportal',
    icon: Globe,
    path: '/portal',
    keywords: ['portal', 'kunde', 'landwirt', 'shop', 'bestellung', 'futterbestellung', 'verträge'],
    mcp: { businessDomain: 'sales', scope: 'sales:read' },
  },
]

const ACTION_SHORTCUTS_CONFIG: Array<
  {
    id: string
    label: string
    icon: typeof LayoutDashboard
    module: string
    preferredPath?: string
    keywords?: string[]
  }
> = [
  {
    id: 'action-new-customer',
    label: 'Neuer Kunde anlegen',
    icon: Plus,
    module: '@/pages/verkauf/kunde-neu',
    keywords: ['neu', 'kunde'],
  },
  {
    id: 'action-new-invoice',
    label: 'Neue Rechnung erstellen',
    icon: Plus,
    module: '@/pages/sales/invoice-editor',
    preferredPath: 'sales/invoice',
    keywords: ['rechnung'],
  },
  {
    id: 'action-bestellvorschlag',
    label: 'Bestellvorschlag generieren',
    icon: Calculator,
    module: '@/pages/einkauf/bestellvorschlaege',
    keywords: ['bestellvorschlag'],
  },
  {
    id: 'action-ernte-annahme',
    label: 'Ernte-Annahme erfassen',
    icon: Tractor,
    module: '@/pages/agrar/ernte-annahme-erfassung',
    preferredPath: 'agrar/ernte-annahme-erfassung',
    keywords: ['ernte', 'annahme'],
  },
]

export const NAV_SECTIONS: NavItem[] = NAV_SECTIONS_CONFIG.map(resolveNavItem)

export const NAV_LINKS: NavItem[] = flattenNavItems(NAV_SECTIONS)

export const NAVIGATION_SHORTCUTS: NavigationShortcut[] = NAV_LINKS.filter(
  (item): item is NavItem & { path: string } => Boolean(item.path),
).map((item) => ({
  id: item.id,
  label: item.label,
  icon: item.icon,
  path: item.path,
  keywords: item.keywords,
}))

export const ACTION_SHORTCUTS: ActionShortcut[] = ACTION_SHORTCUTS_CONFIG.map((shortcut) => ({
  id: shortcut.id,
  label: shortcut.label,
  icon: shortcut.icon,
  path: resolveRoutePathFromModule(shortcut.module, shortcut.preferredPath),
  keywords: shortcut.keywords,
}))

export const AI_SHORTCUTS: AiShortcut[] = [
  {
    id: 'ai-ask-valeo',
    label: 'Ask VALEO (AI-Copilot)',
    icon: Zap,
    type: 'event',
    eventName: 'open-ask-valeo',
    keywords: ['ai', 'copilot', 'assistant'],
  },
  {
    id: 'ai-search',
    label: 'Semantische Suche',
    icon: Search,
    type: 'event',
    eventName: 'open-semantic-search',
    keywords: ['search', 'semantic'],
  },
  {
    id: 'ai-compliance',
    label: 'Compliance-Check durchführen',
    icon: ShieldCheck,
    type: 'navigate',
    path: resolveRoutePathFromModule('@/pages/admin/compliance-dashboard', 'admin/compliance'),
    keywords: ['compliance', 'audit'],
  },
]

function resolveNavItem(item: RawNavItem): NavItem {
  const moduleSpecifier = item.module ?? inferModuleFromPath(item.path)
  const resolvedPath =
    item.path ??
    (moduleSpecifier ? resolveRoutePathFromModule(moduleSpecifier, item.preferredPath) : undefined)

  return {
    ...item,
    module: moduleSpecifier,
    path: resolvedPath,
    children: item.children?.map(resolveNavItem),
  }
}

function inferModuleFromPath(path?: string): string | undefined {
  if (!path) {
    return undefined
  }
  const normalized = path.startsWith('/') ? path.slice(1) : path
  if (!normalized) {
    return '@/pages/index'
  }
  return `@/pages/${normalized}`
}

function flattenNavItems(items: NavItem[]): NavItem[] {
  return items.flatMap((item) => {
    const result: NavItem[] = []
    if (item.path) {
      result.push(item)
    }
    if (item.children) {
      result.push(...flattenNavItems(item.children))
    }
    return result
  })
}
