-- Fix articles schema
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS suchbegriff VARCHAR(100);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS hersteller VARCHAR(120);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS description2 TEXT;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS short_description VARCHAR(255);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS matchcode2 VARCHAR(100);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS herkunftsland VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS naehrwertangaben JSONB;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS mhd_erforderlich BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS lagerartikel BOOLEAN DEFAULT true;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS mehrwertsteuer_prozent DECIMAL(5,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS warengruppe VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS gefahrgutklasse VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS gefahrgut_un_nummer VARCHAR(20);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS gefahrgut_verpackungsgruppe VARCHAR(10);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS gefahrgut_anhaenge JSONB;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS lagerorte JSONB;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS chargenpflicht BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS qs_pruefung_erforderlich BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS zolltarifnummer VARCHAR(20);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS bio_kennzeichnung VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS gmp_plus_relevanz BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS kennzeichnung_bio JSONB;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS kennzeichnung_vegan JSONB;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS kennzeichnung_vegetarisch JSONB;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS kennzeichnung_allergene JSONB;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS kennzeichnung_herkunft JSONB;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS lager_min_temperatur DECIMAL(5,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS lager_max_temperatur DECIMAL(5,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS lager_lagerdauer_tage INTEGER;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS lager_zentral BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS lager_silo BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS analyse_protein DECIMAL(5,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS analyse_feuchtigkeit DECIMAL(5,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS analyse_schadex DECIMAL(5,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS analyse_fremdstoffe DECIMAL(5,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS analyse_sonstiges TEXT;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS ean_code VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS alt_ean_code VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS lieferanten_artikelnummer VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS kunden_artikelnummer VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS verwendungszweck TEXT;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS nachhaltige_biomasse BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS pool_artikel BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS rabatt_auftrag_rechnung DECIMAL(5,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS rabatt_lose DECIMAL(5,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS rabatt_selbstabholer DECIMAL(5,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS zu_abschlag_1_code VARCHAR(20);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS zu_abschlag_1_prozent DECIMAL(5,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS zu_abschlag_2_code VARCHAR(20);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS zu_abschlag_2_prozent DECIMAL(5,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS berechne_zu_abschlag_auf_netto BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS einfuegen_summe_nach_zu_abschlag BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS skontofaehig BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS warenrueckverguetung BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS bonus_faehig BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS rabattfaehig BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS einheit_typ VARCHAR(20);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS einheit_faktor DECIMAL(10,4);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS einheit_preiseinheit VARCHAR(20);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS gebinde_groesse DECIMAL(10,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS gebinde_einheit VARCHAR(20);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS etikett_druck BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS etikett_preis_je_1kg BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS etikett_vorlage VARCHAR(100);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS etikett_abweichende_bezugsgroesse VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS web_sichtbar BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS web_preis_auf_anfrage BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS intrastat_warennr VARCHAR(20);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS kontrakt_erlaubt BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS chargen_nr_erforderlich BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS serien_nr_erforderlich BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS bioware BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS waage_artikel BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS pflanzenschutzmittel BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS explosionsstoff BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS nur_einzelverkauf BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS artikel_umbuchung_bei_ls_freigabe BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS haltbarkeit_tage INTEGER;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS regal_flaeche VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS min_menge_auftrag DECIMAL(10,2);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS kostenstelle VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS duengemittel_inhalte_id VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS duengemittel_inhalte_bezeichnung VARCHAR(100);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS kaufabrechnung BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS mva_kontrakt BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS mahlerzeugnis BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS schnittstelle_artikel_nr VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS schnittstelle_waage_nr VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS schnittstelle_produkt_nr VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS waage_etikett_art VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS nawaro_endprodukt BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS getreidemeldung_formular_spalte VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS getreidemeldung_herkunft VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS mvo_bereich VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS mvo_gruppe VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS mvo_erzeugnis VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS mvo_bestandsgroesse VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS analyse_text TEXT;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS analyse_bild_datei VARCHAR(255);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS druck_anfrage BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS druck_angebot BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS druck_auftragsbestaetigung BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS druck_lieferschein BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS druck_rechnung BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS druck_kontrakt BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS druck_wiegeschein BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS druck_statt_artikel_bezeichnung BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS druck_zusaetzlich BOOLEAN DEFAULT false;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS lieferantennummer VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS subcategory VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS barcode VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS supplier_number VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS customer_article_number VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS currency VARCHAR(3) DEFAULT 'EUR';
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS min_stock INTEGER DEFAULT 0;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS max_stock INTEGER DEFAULT 0;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS weight DECIMAL(10,3);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS dimensions VARCHAR(50);
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS reserved_stock INTEGER DEFAULT 0;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS available_stock INTEGER DEFAULT 0;
ALTER TABLE domain_inventory.articles ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE;
