-- ============================================================================
-- VALEO-NeuroERP - L3 Import Tabellen (PostgreSQL)
-- Auto-generated from L3 Database Schema
-- ============================================================================

-- ADRESSEN
CREATE TABLE IF NOT EXISTS l3_adressen (
    nummer SERIAL PRIMARY KEY,
    name1 VARCHAR(255),
    name2 VARCHAR(255),
    branche VARCHAR(255),
    strasse VARCHAR(255),
    nat VARCHAR(255),
    plz VARCHAR(100),
    ort VARCHAR(255),
    postfach VARCHAR(255),
    postfplz VARCHAR(100),
    postfort VARCHAR(255),
    telefon1 VARCHAR(100),
    telefon2 VARCHAR(100),
    telefax VARCHAR(100),
    land VARCHAR(255),
    anrede VARCHAR(255),
    briefanr VARCHAR(255),
    art VARCHAR(255),
    knr VARCHAR(255),
    frei1 VARCHAR(255),
    frei2 VARCHAR(255),
    frei3 VARCHAR(255),
    frei4 VARCHAR(255),
    trans VARCHAR(255),
    email VARCHAR(255),
    homepage VARCHAR(255),
    trfield VARCHAR(255),
    repl_id VARCHAR(255),
    repl_database VARCHAR(255),
    lname1 VARCHAR(255),
    lname2 VARCHAR(255),
    lbranche VARCHAR(255),
    erledigt VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_l3_adressen_name1 ON l3_adressen(name1);
CREATE INDEX IF NOT EXISTS idx_l3_adressen_name2 ON l3_adressen(name2);
CREATE INDEX IF NOT EXISTS idx_l3_adressen_lname1 ON l3_adressen(lname1);
CREATE INDEX IF NOT EXISTS idx_l3_adressen_lname2 ON l3_adressen(lname2);

-- ARTIKEL
CREATE TABLE IF NOT EXISTS l3_artikel (
    artikelnr VARCHAR(255),
    artikelgrp VARCHAR(255),
    matchcode VARCHAR(100),
    bezeichn1 VARCHAR(255),
    bezeichn2 VARCHAR(255),
    beschreib VARCHAR(255),
    me1 VARCHAR(255),
    umr1 VARCHAR(255),
    me2 VARCHAR(255),
    umr2 VARCHAR(255),
    me3 VARCHAR(255),
    umr3 VARCHAR(255),
    pe1 VARCHAR(255),
    verpart VARCHAR(255),
    artikelart VARCHAR(255),
    sorte1 VARCHAR(255),
    sorte2 VARCHAR(255),
    abrtabnr VARCHAR(255),
    gesperrt VARCHAR(255),
    kontrakt VARCHAR(255),
    skonto VARCHAR(255),
    wrv VARCHAR(255),
    mwstschl VARCHAR(255),
    zollkennz VARCHAR(255),
    kundennr VARCHAR(255),
    arbplan VARCHAR(255),
    zeichnung VARCHAR(255),
    material VARCHAR(255),
    format VARCHAR(255),
    laenge VARCHAR(255),
    breite VARCHAR(255),
    hoehe VARCHAR(255),
    eancode VARCHAR(100),
    eantabelle VARCHAR(255),
    bewertart VARCHAR(255),
    kennz1 VARCHAR(255),
    kennz2 VARCHAR(255),
    kennz3 VARCHAR(255),
    kennz4 VARCHAR(255),
    kennz5 VARCHAR(255),
    trans VARCHAR(255),
    trfield VARCHAR(255),
    repl_id VARCHAR(255),
    repl_database VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_l3_artikel_artikelnr ON l3_artikel(artikelnr);
CREATE INDEX IF NOT EXISTS idx_l3_artikel_artikelgrp ON l3_artikel(artikelgrp);
CREATE INDEX IF NOT EXISTS idx_l3_artikel_artikelart ON l3_artikel(artikelart);
CREATE INDEX IF NOT EXISTS idx_l3_artikel_kundennr ON l3_artikel(kundennr);

-- RECHNUNG
CREATE TABLE IF NOT EXISTS l3_rechnung (
    auftragnr VARCHAR(255),
    lfdleistnr VARCHAR(255),
    rechnungnr VARCHAR(255),
    abschlagnr VARCHAR(255),
    rechndatum DATE,
    buchdatum DATE,
    bezeichn VARCHAR(255),
    netto VARCHAR(255),
    mwst VARCHAR(255),
    brutto VARCHAR(255),
    datum1 DATE,
    zahlung1 VARCHAR(255),
    datum2 DATE,
    zahlung2 VARCHAR(255),
    datum3 DATE,
    zahlung3 VARCHAR(255),
    kundennr VARCHAR(255),
    debitorkto VARCHAR(255),
    erloeskto VARCHAR(255),
    datumvon DATE,
    datumbis DATE,
    skonto1tg VARCHAR(255),
    skonto1pr VARCHAR(255),
    skonto2tg VARCHAR(255),
    skonto2pr VARCHAR(255),
    nettotg VARCHAR(255),
    kostenst VARCHAR(255),
    rechstatus VARCHAR(255),
    rechart VARCHAR(255),
    rechaltnr VARCHAR(255),
    rechtext VARCHAR(255),
    zwkto VARCHAR(255),
    mwstkto VARCHAR(255),
    fordkto VARCHAR(255),
    ustid VARCHAR(255),
    kundname VARCHAR(255),
    trans VARCHAR(255),
    mwstsatz VARCHAR(255),
    mwstsl VARCHAR(255),
    waehrcode VARCHAR(100),
    natcode VARCHAR(100),
    eurnetto VARCHAR(255),
    eurmwst VARCHAR(255),
    eurbrutto VARCHAR(255),
    trfield VARCHAR(255),
    repl_id VARCHAR(255),
    repl_database VARCHAR(255),
    steuernummer VARCHAR(255),
    betriebsnr VARCHAR(255),
    mwstslart VARCHAR(255),
    blrechohnemwst VARCHAR(255),
    dleistzeitraumvon VARCHAR(255),
    dleistzeitraumbis VARCHAR(255),
    cuebergabefibu VARCHAR(255),
    blbonus VARCHAR(255),
    kgeschst VARCHAR(255),
    eurnettodiv VARCHAR(255),
    lfdnrkunde VARCHAR(255),
    rechnrkunde VARCHAR(255),
    kostentrauf VARCHAR(255),
    ibonusgutschrift BOOLEAN DEFAULT FALSE,
    dbonusprozent VARCHAR(255),
    dtdruckdatum DATE,
    dtfaktvon VARCHAR(255),
    dtfaktbis VARCHAR(255),
    cprotbediener VARCHAR(255),
    dtprotdatum DATE,
    dnetto VARCHAR(255),
    dmwst VARCHAR(255),
    dbrutto VARCHAR(255),
    eurnettooab VARCHAR(255),
    eurmwstoab VARCHAR(255),
    eurbruttooab VARCHAR(255),
    eurnettoab VARCHAR(255),
    eurmwstab VARCHAR(255),
    eurbruttoab VARCHAR(255),
    signatur VARCHAR(255),
    uebergabedatum DATE,
    uebergabebeleg VARCHAR(255),
    uebergabepaygate VARCHAR(255),
    gutschriftnrfremd VARCHAR(255),
    gutschriftdatumfremd DATE,
    nettotage VARCHAR(255),
    skonto1 VARCHAR(255),
    skonto2 VARCHAR(255),
    rechnungsartentxt VARCHAR(255),
    id_stornogruende BOOLEAN DEFAULT FALSE,
    dbid_stornogruende VARCHAR(255),
    stornogrund VARCHAR(255),
    uebergabepdf VARCHAR(255),
    teilstorno VARCHAR(255),
    mwstsl2 VARCHAR(255),
    eurnettomaster VARCHAR(255),
    eurmwstmaster VARCHAR(255),
    eurbruttomaster VARCHAR(255),
    rechnrbezug VARCHAR(255),
    abrechnungerfolgt VARCHAR(255),
    debktohauptkd VARCHAR(255),
    skontonr VARCHAR(255),
    mwstsl_original VARCHAR(255),
    id_stornoanforderer BOOLEAN DEFAULT FALSE,
    dbid_stornoanforderer VARCHAR(255),
    stornoanforderer VARCHAR(255),
    logingeschst VARCHAR(255),
    guid VARCHAR(255),
    stornonr VARCHAR(255),
    uebergabefactoring VARCHAR(255),
    uebergabepdffibu VARCHAR(255),
    id_contact BOOLEAN DEFAULT FALSE,
    dbid_contact VARCHAR(255),
    rechnungsformat_zugferd VARCHAR(255),
    next_email_versendet VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_l3_rechnung_rechndatum ON l3_rechnung(rechndatum);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_buchdatum ON l3_rechnung(buchdatum);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_datum1 ON l3_rechnung(datum1);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_datum2 ON l3_rechnung(datum2);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_datum3 ON l3_rechnung(datum3);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_kundennr ON l3_rechnung(kundennr);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_datumvon ON l3_rechnung(datumvon);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_datumbis ON l3_rechnung(datumbis);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_kundname ON l3_rechnung(kundname);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_steuernummer ON l3_rechnung(steuernummer);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_lfdnrkunde ON l3_rechnung(lfdnrkunde);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_rechnrkunde ON l3_rechnung(rechnrkunde);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_dtdruckdatum ON l3_rechnung(dtdruckdatum);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_dtprotdatum ON l3_rechnung(dtprotdatum);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_uebergabedatum ON l3_rechnung(uebergabedatum);
CREATE INDEX IF NOT EXISTS idx_l3_rechnung_gutschriftdatumfremd ON l3_rechnung(gutschriftdatumfremd);

-- AUFTRAG
CREATE TABLE IF NOT EXISTS l3_auftrag (
    auftragnr VARCHAR(255),
    angebotnr VARCHAR(255),
    kundennr VARCHAR(255),
    besteller VARCHAR(255),
    geschst VARCHAR(255),
    kostenst VARCHAR(255),
    angebdatum DATE,
    bestdatum DATE,
    bestnrkd VARCHAR(255),
    arbbereich VARCHAR(255),
    vondatum DATE,
    bisdatum DATE,
    anzmitarb VARCHAR(255),
    sichbakund VARCHAR(255),
    sichbaeig VARCHAR(255),
    mwst VARCHAR(255),
    waehrcode VARCHAR(100),
    rechnwaehr VARCHAR(255),
    waehrkurs VARCHAR(255),
    tageskurs VARCHAR(255),
    skonto1tg VARCHAR(255),
    skonto1pr VARCHAR(255),
    skonto2tg VARCHAR(255),
    skonto2pr VARCHAR(255),
    nettotg VARCHAR(255),
    arbzeitmo VARCHAR(255),
    arbzeitdi VARCHAR(255),
    arbzeitmi VARCHAR(255),
    arbzeitdo VARCHAR(255),
    arbzeitfr VARCHAR(255),
    arbzeitsa VARCHAR(255),
    arbzeitso VARCHAR(255),
    arbzeitwch VARCHAR(255),
    arbzeitmon VARCHAR(255),
    arbzeitvon VARCHAR(255),
    arbzeitbis VARCHAR(255),
    pause1von VARCHAR(255),
    pause1bis VARCHAR(255),
    pause2von VARCHAR(255),
    pause2bis VARCHAR(255),
    pause3von VARCHAR(255),
    pause3bis VARCHAR(255),
    auftstatus VARCHAR(255),
    verantw_ag VARCHAR(255),
    verantw_an VARCHAR(255),
    auftragbeg VARCHAR(255),
    maxabschl VARCHAR(255),
    garantproz VARCHAR(255),
    preisaus VARCHAR(255),
    memo VARCHAR(255),
    bediener VARCHAR(255),
    vertrbeauf VARCHAR(255),
    kurzbez VARCHAR(255),
    bauleiter VARCHAR(255),
    persleiter VARCHAR(255),
    sichsrproz VARCHAR(255),
    nettotgsic VARCHAR(255),
    mwstschl VARCHAR(255),
    druckform VARCHAR(255),
    trans VARCHAR(255),
    cad_profil VARCHAR(255),
    zusmemo1 VARCHAR(255),
    zusmemo2 VARCHAR(255),
    zusmemo3 VARCHAR(255),
    zusmemo4 VARCHAR(255),
    best_anrede VARCHAR(255),
    best_ansprnr VARCHAR(255),
    nachweisnr VARCHAR(255),
    nachweisart VARCHAR(255),
    trfield VARCHAR(255),
    repl_id VARCHAR(255),
    repl_database VARCHAR(255),
    idauftragprojekte BOOLEAN DEFAULT FALSE,
    dbidauftragprojekte VARCHAR(255),
    id_ablehnung BOOLEAN DEFAULT FALSE,
    dbid_ablehnung VARCHAR(255),
    blablehnung VARCHAR(255),
    cgeplatzt VARCHAR(255),
    id_auftrag_geplatzt BOOLEAN DEFAULT FALSE,
    iddb_auftrag_geplatzt BOOLEAN DEFAULT FALSE,
    geplatzttext VARCHAR(255),
    bestanrede VARCHAR(255),
    blrechohnemwst VARCHAR(255),
    vergabedatum DATE,
    bezeichnung VARCHAR(255),
    cvbbediener VARCHAR(255),
    id_anfragetyp BOOLEAN DEFAULT FALSE,
    dbid_anfragetyp VARCHAR(255),
    sanfragekennzeichen VARCHAR(255),
    ivertragsart BOOLEAN DEFAULT FALSE,
    irvertragnr BOOLEAN DEFAULT FALSE,
    drvertragunteram VARCHAR(255),
    inachtragauftragnr BOOLEAN DEFAULT FALSE,
    cdisponent VARCHAR(255),
    dgueltigbis VARCHAR(255),
    cbonustext VARCHAR(255),
    id_auftragbearbeit BOOLEAN DEFAULT FALSE,
    dbid_auftragbearbeit VARCHAR(255),
    id_auftragablehn BOOLEAN DEFAULT FALSE,
    dbid_auftragablehn VARCHAR(255),
    blablehnunggr VARCHAR(255),
    cmitbewerbschl VARCHAR(255),
    cmitbewerbson VARCHAR(255),
    itqmbogen BOOLEAN DEFAULT FALSE,
    dtqmbogendatum DATE,
    ctqmbogenbediener VARCHAR(255),
    irechart BOOLEAN DEFAULT FALSE,
    csammelrech VARCHAR(255),
    cformular VARCHAR(255),
    dtangguetbis VARCHAR(255),
    best_briefanr VARCHAR(255),
    id_rechnunggruppierung BOOLEAN DEFAULT FALSE,
    dbid_rechnunggruppierung VARCHAR(255),
    ifakturumlage BOOLEAN DEFAULT FALSE,
    ioutsourcing BOOLEAN DEFAULT FALSE,
    iairbus BOOLEAN DEFAULT FALSE,
    cfibunetbeleg2 VARCHAR(255),
    kostentraeger VARCHAR(255),
    ityprechnunganhang BOOLEAN DEFAULT FALSE,
    dtangelegtam VARCHAR(255),
    sprojektnr VARCHAR(255),
    sammelrech VARCHAR(255),
    rechnungvortext VARCHAR(255),
    rechnungnachtext VARCHAR(255),
    equaltreatment VARCHAR(255),
    mailingid VARCHAR(255),
    mailingdbid VARCHAR(255),
    rabatttage VARCHAR(255),
    bestellervorname VARCHAR(255),
    event VARCHAR(255),
    eventtitel VARCHAR(255),
    eventtext VARCHAR(255),
    nichtsichtbarwebportal VARCHAR(255),
    skontonr VARCHAR(255),
    eventrechnung VARCHAR(255),
    sperre VARCHAR(255),
    l1rechgruppe VARCHAR(255),
    stoptarifequalpaydatum DATE,
    event_strasse VARCHAR(255),
    event_plz VARCHAR(100),
    event_ort VARCHAR(255),
    abschlagpr VARCHAR(255),
    maxfaktpr VARCHAR(255),
    erloeskto VARCHAR(255),
    inplanung BOOLEAN DEFAULT FALSE,
    default_inplanung_position VARCHAR(255),
    event_location VARCHAR(255),
    aktiv VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_l3_auftrag_kundennr ON l3_auftrag(kundennr);
CREATE INDEX IF NOT EXISTS idx_l3_auftrag_angebdatum ON l3_auftrag(angebdatum);
CREATE INDEX IF NOT EXISTS idx_l3_auftrag_bestdatum ON l3_auftrag(bestdatum);
CREATE INDEX IF NOT EXISTS idx_l3_auftrag_vondatum ON l3_auftrag(vondatum);
CREATE INDEX IF NOT EXISTS idx_l3_auftrag_bisdatum ON l3_auftrag(bisdatum);
CREATE INDEX IF NOT EXISTS idx_l3_auftrag_vergabedatum ON l3_auftrag(vergabedatum);
CREATE INDEX IF NOT EXISTS idx_l3_auftrag_dtqmbogendatum ON l3_auftrag(dtqmbogendatum);
CREATE INDEX IF NOT EXISTS idx_l3_auftrag_bestellervorname ON l3_auftrag(bestellervorname);
CREATE INDEX IF NOT EXISTS idx_l3_auftrag_stoptarifequalpaydatum ON l3_auftrag(stoptarifequalpaydatum);

