"""Pydantic schemas for CRM Marketing."""

from .segment import (
    SegmentBase,
    SegmentCreate,
    SegmentUpdate,
    Segment,
    SegmentRuleBase,
    SegmentRuleCreate,
    SegmentRuleUpdate,
    SegmentRule,
    SegmentMemberBase,
    SegmentMemberCreate,
    SegmentMember,
    SegmentPerformance,
    SegmentCalculateRequest,
    SegmentExportRequest,
)
from .campaign import (
    CampaignBase,
    CampaignCreate,
    CampaignUpdate,
    Campaign,
    CampaignTemplateBase,
    CampaignTemplateCreate,
    CampaignTemplateUpdate,
    CampaignTemplate,
    CampaignRecipientBase,
    CampaignRecipientCreate,
    CampaignRecipient,
    CampaignEventBase,
    CampaignEventCreate,
    CampaignEvent,
    CampaignPerformance as CampaignPerformanceSchema,
    CampaignScheduleRequest,
    CampaignTestRequest,
)

__all__ = [
    "SegmentBase",
    "SegmentCreate",
    "SegmentUpdate",
    "Segment",
    "SegmentRuleBase",
    "SegmentRuleCreate",
    "SegmentRuleUpdate",
    "SegmentRule",
    "SegmentMemberBase",
    "SegmentMemberCreate",
    "SegmentMember",
    "SegmentPerformance",
    "SegmentCalculateRequest",
    "SegmentExportRequest",
    "CampaignBase",
    "CampaignCreate",
    "CampaignUpdate",
    "Campaign",
    "CampaignTemplateBase",
    "CampaignTemplateCreate",
    "CampaignTemplateUpdate",
    "CampaignTemplate",
    "CampaignRecipientBase",
    "CampaignRecipientCreate",
    "CampaignRecipient",
    "CampaignEventBase",
    "CampaignEventCreate",
    "CampaignEvent",
    "CampaignPerformanceSchema",
    "CampaignScheduleRequest",
    "CampaignTestRequest",
]

