import {
  Activity,
  ArrowUpDown,
  AlertCircle,
  BarChart3,
  Building2,
  Calendar,
  Calculator,
  Database,
  Euro,
  FileDown,
  FileText,
  FlaskConical,
  Globe,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Package,
  RefreshCw,
  Scale,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sprout,
  Target,
  Tractor,
  Truck,
  Upload,
  UserCog,
  Users,
  Zap,
  Search,
  BookOpen,
  Users2,
} from 'lucide-react'
import type { RawNavItem } from '@/app/navigation/types'
import { ENABLE_PROSPECTING_UI } from '@/features/prospecting/feature-flags'

const CRM_CHILDREN: RawNavItem[] = [
  {
    id: 'kontakte',
    label: 'Kontakte',
    icon: Users,
    module: '@/pages/crm/kontakte-liste',
    keywords: ['kontakte'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'leads',
    label: 'Leads',
    icon: Target,
    module: '@/pages/crm/leads',
    keywords: ['leads'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'aktivitaeten',
    label: 'Aktivitäten',
    icon: Calendar,
    module: '@/pages/crm/aktivitaeten',
    keywords: ['aktivitäten'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'betriebsprofile',
    label: 'Betriebsprofile',
    icon: Tractor,
    module: '@/pages/crm/betriebsprofile-liste',
    keywords: ['betriebsprofile'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'kampagnen',
    label: 'Kampagnen',
    icon: Zap,
    module: '@/pages/crm/campaigns',
    preferredPath: 'crm/campaigns',
    keywords: ['kampagnen', 'marketing', 'campaign'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'kampagnen-vorlagen',
    label: 'Kampagnen-Vorlagen',
    icon: FileText,
    module: '@/pages/crm/campaign-templates',
    preferredPath: 'crm/campaign-templates',
    keywords: ['vorlagen', 'templates', 'kampagnen'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'kampagnen-performance',
    label: 'Kampagnen-Performance',
    icon: BarChart3,
    module: '@/pages/crm/campaign-performance-dashboard',
    preferredPath: 'crm/campaign-performance',
    keywords: ['performance', 'analytics', 'kampagnen'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'segmente',
    label: 'Segmente',
    icon: Users,
    module: '@/pages/crm/segments',
    preferredPath: 'crm/segments',
    keywords: ['segmente', 'zielgruppen'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'einwilligungen',
    label: 'Einwilligungen',
    icon: ShieldCheck,
    module: '@/pages/crm/consent-management',
    preferredPath: 'crm/consents',
    keywords: ['consent', 'einwilligung', 'dsgvo'],
    mcp: { businessDomain: 'crm', scope: 'compliance:read' },
  },
  {
    id: 'dsgvo-anfragen',
    label: 'DSGVO-Anfragen',
    icon: ShieldCheck,
    module: '@/pages/crm/gdpr-requests',
    preferredPath: 'crm/gdpr-requests',
    keywords: ['dsgvo', 'gdpr', 'datenschutz'],
    mcp: { businessDomain: 'crm', scope: 'compliance:read' },
  },
]

if (ENABLE_PROSPECTING_UI) {
  CRM_CHILDREN.splice(2, 0, {
    id: 'prospecting',
    label: 'Potenzialsuche',
    icon: Search,
    module: '@/pages/prospecting/LeadExplorer',
    preferredPath: 'prospecting/leads',
    keywords: ['prospecting', 'gap', 'potenzial'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  })
}

export const RAW_NAV_SECTIONS: RawNavItem[] = [
  {
    id: 'kontrakte',
    label: 'Kontrakte',
    icon: BookOpen,
    mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
    children: [
      {
        id: 'kontrakt-uebersicht',
        label: 'Kontraktübersicht',
        icon: FileText,
        module: '@/pages/kontrakte/LstKontraktUebersicht',
        preferredPath: 'kontrakte/LstKontraktUebersicht',
        keywords: ['kontrakte', 'übersicht', 'liste'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'kontrakt-alarm',
        label: 'Alarm-Dashboard',
        icon: FileText,
        module: '@/pages/kontrakte/KontraktAlarmDashboard',
        preferredPath: 'kontrakte/KontraktAlarmDashboard',
        keywords: ['kontrakt', 'alarm', 'fälligkeit', 'warnung'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'kontrakt-positionsmonitor',
        label: 'Positionsmonitor',
        icon: FileText,
        module: '@/pages/kontrakte/KontraktPositionsmonitor',
        preferredPath: 'kontrakte/KontraktPositionsmonitor',
        keywords: ['kontrakt', 'positionen', 'monitor', 'status'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'kontraktklassen',
        label: 'Kontraktklassen',
        icon: FileText,
        module: '@/pages/kontrakte/kontraktklassen',
        preferredPath: 'kontrakte/kontraktklassen',
        keywords: ['kontraktklassen', 'fixpreis', 'basis', 'prämie', 'poolpreis'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
    ],
  },
  {
    id: 'preise',
    label: 'Preise & Kalkulation',
    icon: Calculator,
    mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
    children: [
      {
        id: 'preis-kalkulation',
        label: 'Preis-Kalkulation',
        icon: Calculator,
        module: '@/pages/preise/kalkulation',
        preferredPath: 'preise/kalkulation',
        keywords: ['preis', 'kalkulation', 'berechnung', 'marge'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'preis-historie',
        label: 'Preishistorie',
        icon: Calculator,
        module: '@/pages/preise/historie',
        preferredPath: 'preise/historie',
        keywords: ['preis', 'historie', 'verlauf', 'entwicklung'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'preis-konditionen',
        label: 'Konditionen',
        icon: Calculator,
        module: '@/pages/preise/konditionen',
        preferredPath: 'preise/konditionen',
        keywords: ['konditionen', 'rabatt', 'preis', 'staffel'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
    ],
  },
  {
    id: 'genossenschaft',
    label: 'Genossenschaft',
    icon: Users2,
    mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
    children: [
      {
        id: 'genossenschaft-mitglieder',
        label: 'Mitglieder',
        icon: Users,
        module: '@/pages/genossenschaft/mitglieder',
        preferredPath: 'genossenschaft/mitglieder',
        keywords: ['mitglieder', 'genossenschaft', 'geschäftsanteile'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
    ],
  },
  {
    id: 'verkauf',
    label: 'Verkauf',
    icon: ShoppingCart,
    mcp: { businessDomain: 'sales', scope: 'sales:read' },
    children: [
      {
        id: 'sales-dashboard',
        label: 'Dashboard',
        icon: BarChart3,
        module: '@/pages/dashboard/sales-dashboard',
        preferredPath: 'dashboard/sales',
        keywords: ['dashboard', 'kpi', 'analytics'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'angebot',
        label: 'Angebote',
        icon: FileText,
        module: '@/pages/sales/angebot-erstellen',
        preferredPath: 'sales/angebote',
        keywords: ['angebot', 'angebot-erfassung', 'angebot-erstellen'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'auftrag',
        label: 'Aufträge',
        icon: FileText,
        module: '@/pages/sales/order-editor',
        preferredPath: 'sales/order',
        keywords: ['aufträge'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'lieferung',
        label: 'Lieferungen',
        icon: Truck,
        module: '@/pages/verkauf/lieferschein-erfassung',
        preferredPath: 'verkauf/lieferschein-erfassung',
        keywords: ['lieferungen', 'lieferschein'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'rechnung',
        label: 'Rechnungen',
        icon: FileText,
        module: '@/pages/sales/invoice-editor',
        preferredPath: 'sales/invoice',
        keywords: ['rechnungen'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kunden',
        label: 'Kunden',
        icon: Users,
        module: '@/pages/verkauf/kunden-liste',
        preferredPath: 'verkauf/kunden-liste',
        keywords: ['kunden', 'crm', 'customer'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'artikel',
        label: 'Artikel',
        icon: Package,
        module: '@/pages/artikel/liste',
        keywords: ['artikel', 'products', 'lager'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'unerledigte-auftrags-positionen',
        label: 'Unerledigte Auftrags-Positionen',
        icon: AlertCircle,
        module: '@/pages/verkauf/unerledigte-auftrags-positionen',
        preferredPath: 'verkauf/unerledigte-auftrags-positionen',
        keywords: ['unerledigte', 'auftrags', 'positionen', 'offene'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kommissions-auftraege',
        label: 'Kommissions-Aufträge',
        icon: FileText,
        module: '@/pages/verkauf/kommissions-auftraege',
        preferredPath: 'verkauf/kommissions-auftraege',
        keywords: ['kommissions', 'aufträge', 'kommission'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'betriebs-auftraege',
        label: 'Betriebs-Aufträge',
        icon: FileText,
        module: '@/pages/verkauf/betriebs-auftraege',
        preferredPath: 'verkauf/betriebs-auftraege',
        keywords: ['betriebs', 'aufträge', 'interne aufträge'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'analytics',
        label: 'Vertriebsanalyse',
        icon: BarChart3,
        module: '@/pages/analytics',
        keywords: ['analytics'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'reports',
        label: 'Berichte',
        icon: FileText,
        module: '@/pages/reports',
        keywords: ['berichte', 'reports'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
    ],
  },
  {
    id: 'crm',
    label: 'CRM & Marketing',
    icon: UserCog,
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
    children: CRM_CHILDREN,
  },
  {
    id: 'einkauf',
    label: 'Einkauf',
    icon: ShoppingCart,
    mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
    children: [
      {
        id: 'einkauf-dashboard',
        label: 'Dashboard',
        icon: BarChart3,
        module: '@/pages/dashboard/einkauf-dashboard',
        preferredPath: 'dashboard/einkauf',
        keywords: ['dashboard', 'einkauf'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlaege',
        label: 'Bestellvorschläge',
        icon: AlertCircle,
        module: '@/pages/einkauf/bestellvorschlaege',
        keywords: ['bestellvorschläge'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlag-lager',
        label: 'Bestellvorschlag Lager',
        icon: Package,
        module: '@/pages/einkauf/bestellvorschlag-lager',
        preferredPath: 'einkauf/bestellvorschlag-lager',
        keywords: ['bestellvorschlag', 'lager', 'mindestbestand'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlag-verkauf',
        label: 'Bestellvorschlag Verkauf',
        icon: ShoppingCart,
        module: '@/pages/einkauf/bestellvorschlag-verkauf',
        preferredPath: 'einkauf/bestellvorschlag-verkauf',
        keywords: ['bestellvorschlag', 'verkauf', 'aufträge'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlag-rohware',
        label: 'Bestellvorschlag Rohstoff',
        icon: Sprout,
        module: '@/pages/einkauf/bestellvorschlag-rohware',
        preferredPath: 'einkauf/bestellvorschlag-rohware',
        keywords: ['bestellvorschlag', 'rohstoff', 'bedarf', 'rohware'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellungen',
        label: 'Bestellungen',
        icon: FileText,
        module: '@/pages/einkauf/bestellungen-liste',
        preferredPath: 'einkauf/bestellungen',
        keywords: ['bestellungen'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'einkauf-lieferschein-erfassung',
        label: 'Eingehende Belege',
        icon: FileText,
        module: '@/pages/einkauf/lieferschein-erfassung',
        preferredPath: 'einkauf/lieferschein-erfassung',
        keywords: ['eingehende belege', 'einkauf lieferschein', 'wareneingang', 'kreditor'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferschein-frachtauftrag',
        label: 'Lieferschein/Frachtauftrag',
        icon: Truck,
        module: '@/pages/einkauf/lieferschein-frachtauftrag',
        preferredPath: 'einkauf/lieferschein-frachtauftrag',
        keywords: ['lieferschein', 'frachtauftrag'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'frachtauftraege-eingang',
        label: 'Frachtaufträge Eingang',
        icon: Truck,
        module: '@/pages/einkauf/frachtauftraege-eingang',
        preferredPath: 'einkauf/frachtauftraege-eingang',
        keywords: ['frachtaufträge', 'eingang', 'spediteur', 'pauschalfracht'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'wareneingang',
        label: 'Wareneingang',
        icon: Package,
        module: '@/pages/charge/wareneingang',
        keywords: ['wareneingang'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferanten',
        label: 'Lieferanten',
        icon: Users,
        module: '@/pages/einkauf/lieferanten-liste',
        keywords: ['lieferanten'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'warengruppen',
        label: 'Warengruppen',
        icon: Package,
        module: '@/pages/einkauf/warengruppen',
        keywords: ['warengruppen'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'anfragen',
        label: 'Anfragen (RFQ)',
        icon: FileText,
        module: '@/pages/einkauf/anfragen-liste',
        keywords: ['anfragen', 'rfq'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'anfrage-erfassung',
        label: 'Anfrage erfassen',
        icon: FileText,
        module: '@/pages/einkauf/anfrage-erfassung',
        preferredPath: 'einkauf/anfrage-erfassung',
        keywords: ['anfrage', 'rfq', 'erfassen', 'lieferant'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'angebote-einkauf',
        label: 'Angebote',
        icon: FileText,
        module: '@/pages/einkauf/angebote-liste',
        keywords: ['angebote', 'einkauf'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'rechnungseingaenge',
        label: 'Rechnungseingänge',
        icon: Euro,
        module: '@/pages/einkauf/rechnungseingaenge-liste',
        keywords: ['rechnungseingang', 'eingangsrechnung'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'rechnung-eingang-erfassung',
        label: 'Eingangsrechnung erfassen',
        icon: Euro,
        module: '@/pages/einkauf/rechnung-eingang-erfassung',
        preferredPath: 'einkauf/rechnung-eingang-erfassung',
        keywords: ['eingangsrechnung', 'rechnungseingang', 'erfassen', 'kreditor'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'rechnung-abgleich',
        label: 'Rechnungsabgleich',
        icon: Calculator,
        module: '@/pages/einkauf/rechnung-abgleich',
        keywords: ['abgleich', '3-wege'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'retouren',
        label: 'Retouren',
        icon: Truck,
        module: '@/pages/einkauf/retouren',
        keywords: ['retouren', 'rückgabe'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
      {
        id: 'disposition',
        label: 'Disposition',
        icon: Calculator,
        module: '@/pages/disposition/liste',
        keywords: ['disposition'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'commodity-position-matrix',
        label: 'Rohwaren-Positionsmatrix',
        icon: LayoutGrid,
        module: '@/pages/disposition/LstCommodityPositionMatrix',
        preferredPath: 'disposition/position-matrix',
        keywords: ['position', 'matrix', 'long', 'short', 'deckung'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'position-regeln',
        label: 'Position-Regeln',
        icon: Settings,
        module: '@/pages/disposition/FrmPositionRules',
        preferredPath: 'disposition/regeln',
        keywords: ['position', 'regeln', 'toleranz'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'coverage-monitor',
        label: 'Deckungsmonitor',
        icon: AlertCircle,
        module: '@/pages/disposition/FrmCoverageMonitor',
        preferredPath: 'disposition/coverage-monitor',
        keywords: ['coverage', 'deckung', 'lücken'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferantenbewertung',
        label: 'Lieferantenbewertung',
        icon: ShieldCheck,
        module: '@/pages/einkauf/lieferantenbewertung',
        keywords: ['lieferanten', 'bewertung', 'score'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferanten-dokumente',
        label: 'Lieferanten-Dokumente',
        icon: FileText,
        module: '@/pages/einkauf/lieferanten-dokumente',
        keywords: ['supplier', 'dokumente', 'nachweise'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
      {
        id: 'service-entry-sheets',
        label: 'Leistungsnachweise',
        icon: FileText,
        module: '@/pages/einkauf/service-entry-sheets',
        keywords: ['ses', 'service entry', 'leistung'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
      {
        id: 'audit-drilldown',
        label: 'Audit-Analyse',
        icon: Activity,
        module: '@/pages/einkauf/audit-drilldown',
        keywords: ['audit', 'belegkette', 'drilldown'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'edi-portal',
        label: 'EDI-Leitstand',
        icon: Activity,
        module: '@/pages/einkauf/edi-portal',
        keywords: ['edi', 'portal', 'ordner', 'messages'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
    ],
  },
]
