import {
  Activity,
  ArrowUpDown,
  AlertCircle,
  BarChart3,
  Building2,
  Calendar,
  Calculator,
  Database,
  Euro,
  FileDown,
  FileText,
  FlaskConical,
  Globe,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Package,
  RefreshCw,
  Scale,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sprout,
  Tag,
  Target,
  Tractor,
  Truck,
  Upload,
  UserCog,
  Users,
  Zap,
  MapPin,
  Search,
  Sparkles,
  BookOpen,
  Users2,
  Layers,
  Box,
  Headset,
  MessageCircle,
  ListChecks,
} from 'lucide-react'
import type { RawNavItem } from '@/app/navigation/types'
import { ENABLE_PROSPECTING_UI } from '@/features/prospecting/feature-flags'

const CRM_CHILDREN: RawNavItem[] = [
  {
    id: 'kontakte',
    label: 'Kontakte',
    icon: Users,
    module: '@/pages/crm/kontakte-liste',
    keywords: ['kontakte'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'leads',
    label: 'Leads',
    icon: Target,
    module: '@/pages/crm/leads',
    keywords: ['leads'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'lead-generierung',
    label: 'Lead-Generierung',
    icon: Sparkles,
    module: '@/pages/crm/lead-generierung',
    preferredPath: 'crm/lead-generierung',
    keywords: ['lead', 'generierung', 'gap', 'lkv', 'potenzial', 'akquise', 'prospecting', 'region'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'aktivitaeten',
    label: 'Aktivitäten',
    icon: Calendar,
    module: '@/pages/crm/aktivitaeten',
    keywords: ['aktivitäten'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'betriebsprofile',
    label: 'Betriebsprofile',
    icon: Tractor,
    module: '@/pages/crm/betriebsprofile-liste',
    keywords: ['betriebsprofile'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'kampagnen',
    label: 'Kampagnen',
    icon: Zap,
    module: '@/pages/crm/campaigns',
    preferredPath: 'crm/campaigns',
    keywords: ['kampagnen', 'marketing', 'campaign'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'kampagnen-vorlagen',
    label: 'Kampagnen-Vorlagen',
    icon: FileText,
    module: '@/pages/crm/campaign-templates',
    preferredPath: 'crm/campaign-templates',
    keywords: ['vorlagen', 'templates', 'kampagnen'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'kampagnen-performance',
    label: 'Kampagnen-Performance',
    icon: BarChart3,
    module: '@/pages/crm/campaign-performance-dashboard',
    preferredPath: 'crm/campaign-performance',
    keywords: ['performance', 'analytics', 'kampagnen'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'segmente',
    label: 'Segmente',
    icon: Users,
    module: '@/pages/crm/segments',
    preferredPath: 'crm/segments',
    keywords: ['segmente', 'zielgruppen'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'einwilligungen',
    label: 'Einwilligungen',
    icon: ShieldCheck,
    module: '@/pages/crm/consent-management',
    preferredPath: 'crm/consents',
    keywords: ['consent', 'einwilligung', 'dsgvo'],
    mcp: { businessDomain: 'crm', scope: 'compliance:read' },
  },
  {
    id: 'dsgvo-anfragen',
    label: 'DSGVO-Anfragen',
    icon: ShieldCheck,
    module: '@/pages/crm/gdpr-requests',
    preferredPath: 'crm/gdpr-requests',
    keywords: ['dsgvo', 'gdpr', 'datenschutz'],
    mcp: { businessDomain: 'crm', scope: 'compliance:read' },
  },
  {
    id: 'verarbeitungsverzeichnis',
    label: 'Verarbeitungsverzeichnis (Art. 30)',
    icon: ShieldCheck,
    module: '@/pages/compliance/verarbeitungsverzeichnis',
    preferredPath: 'compliance/verarbeitungsverzeichnis',
    keywords: ['dsgvo', 'art30', 'ropa', 'verarbeitungsverzeichnis', 'datenschutz'],
    mcp: { businessDomain: 'compliance', scope: 'compliance:write' },
  },
  {
    id: 'datenpannen',
    label: 'Datenpannen-Meldeprozess (Art. 33)',
    icon: ShieldCheck,
    module: '@/pages/compliance/datenpannen',
    preferredPath: 'compliance/datenpannen',
    keywords: ['dsgvo', 'art33', 'datenpanne', 'breach', 'meldepflicht', '72h', 'datenschutz'],
    mcp: { businessDomain: 'compliance', scope: 'compliance:write' },
  },
]

if (ENABLE_PROSPECTING_UI) {
  CRM_CHILDREN.splice(2, 0, {
    id: 'prospecting',
    label: 'Potenzialsuche',
    icon: Search,
    module: '@/pages/prospecting/LeadExplorer',
    preferredPath: 'prospecting/leads',
    keywords: ['prospecting', 'gap', 'potenzial'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  })
}

export const RAW_NAV_SECTIONS: RawNavItem[] = [
  {
    id: 'kontrakte',
    label: 'Kontrakte',
    icon: BookOpen,
    mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
    children: [
      {
        id: 'kontrakt-uebersicht',
        label: 'Kontraktübersicht',
        icon: FileText,
        module: '@/pages/kontrakte/LstKontraktUebersicht',
        preferredPath: 'kontrakte/kontrakt-uebersicht',
        keywords: ['kontrakte', 'übersicht', 'liste'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'kontrakt-alarm',
        label: 'Alarm-Dashboard',
        icon: FileText,
        module: '@/pages/kontrakte/KontraktAlarmDashboard',
        preferredPath: 'kontrakte/kontrakt-alarm-dashboard',
        keywords: ['kontrakt', 'alarm', 'fälligkeit', 'warnung'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'kontrakt-positionsmonitor',
        label: 'Positionsmonitor',
        icon: FileText,
        module: '@/pages/kontrakte/KontraktPositionsmonitor',
        preferredPath: 'kontrakte/kontrakt-positionsmonitor',
        keywords: ['kontrakt', 'positionen', 'monitor', 'status'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'kontraktklassen',
        label: 'Kontraktklassen',
        icon: FileText,
        module: '@/pages/kontrakte/kontraktklassen',
        preferredPath: 'kontrakte/kontraktklassen',
        keywords: ['kontraktklassen', 'fixpreis', 'basis', 'prämie', 'poolpreis'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
    ],
  },
  {
    id: 'preise',
    label: 'Preise & Kalkulation',
    icon: Calculator,
    mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
    children: [
      {
        id: 'preis-kalkulation',
        label: 'Preis-Kalkulation',
        icon: Calculator,
        module: '@/pages/preise/kalkulation',
        preferredPath: 'preise/kalkulation',
        keywords: ['preis', 'kalkulation', 'berechnung', 'marge'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'preis-historie',
        label: 'Preishistorie',
        icon: Calculator,
        module: '@/pages/preise/historie',
        preferredPath: 'preise/historie',
        keywords: ['preis', 'historie', 'verlauf', 'entwicklung'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'preis-konditionen',
        label: 'Konditionen',
        icon: Calculator,
        module: '@/pages/preise/konditionen',
        preferredPath: 'preise/konditionen',
        keywords: ['konditionen', 'rabatt', 'preis', 'staffel'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'zu-abschlaggruppen',
        label: 'Zu-/Abschlaggruppen',
        icon: ArrowUpDown,
        module: '@/pages/preise/zu-abschlaggruppen',
        preferredPath: 'preise/zu-abschlaggruppen',
        keywords: ['zuschlag', 'abschlag', 'gruppen', 'klassen', 'konditionen', 'zagr', 'zakl'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'rabattgruppen',
        label: 'Rabattgruppen & -klassen [RAG/RAK]',
        icon: Scale,
        module: '@/pages/preise/rabattgruppen',
        preferredPath: 'preise/rabattgruppen',
        keywords: ['rabatt', 'rabattgruppe', 'rabattklasse', 'rag', 'rak', 'rabattsatz', 'konditionen'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'individualpreise',
        label: 'Individualpreise [PRI/PRIE]',
        icon: Tag,
        module: '@/pages/preise/individualpreise',
        preferredPath: 'preise/individualpreise',
        keywords: ['individualpreis', 'pri', 'prie', 'kundenpreis', 'lieferantenpreis', 'staffelpreis'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
    ],
  },
  {
    id: 'genossenschaft',
    label: 'Genossenschaft',
    icon: Users2,
    mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
    children: [
      {
        id: 'genossenschaft-mitglieder',
        label: 'Mitglieder',
        icon: Users,
        module: '@/pages/genossenschaft/mitglieder',
        preferredPath: 'genossenschaft/mitglieder',
        keywords: ['mitglieder', 'genossenschaft', 'geschäftsanteile'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
    ],
  },
  {
    id: 'verkauf',
    label: 'Verkauf',
    icon: ShoppingCart,
    mcp: { businessDomain: 'sales', scope: 'sales:read' },
    children: [
      {
        id: 'sales-dashboard',
        label: 'Dashboard',
        icon: BarChart3,
        module: '@/pages/dashboard/sales-dashboard',
        preferredPath: 'dashboard/sales',
        keywords: ['dashboard', 'kpi', 'analytics'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'angebot',
        label: 'Angebote',
        icon: FileText,
        module: '@/pages/sales/angebot-erstellen',
        preferredPath: 'sales/angebote',
        keywords: ['angebot', 'angebot-erfassung', 'angebot-erstellen'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'auftrag',
        label: 'Aufträge',
        icon: FileText,
        module: '@/pages/sales/order-editor',
        preferredPath: 'sales/order',
        keywords: ['aufträge'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'lieferung',
        label: 'Lieferungen',
        icon: Truck,
        module: '@/pages/verkauf/lieferschein-erfassung',
        preferredPath: 'verkauf/lieferschein-erfassung',
        keywords: ['lieferungen', 'lieferschein'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'rechnung',
        label: 'Rechnungen',
        icon: FileText,
        module: '@/pages/sales/invoice-editor',
        preferredPath: 'sales/invoice',
        keywords: ['rechnungen'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kunden',
        label: 'Kunden',
        icon: Users,
        module: '@/pages/verkauf/kunden-liste',
        preferredPath: 'verkauf/kunden-liste',
        keywords: ['kunden', 'crm', 'customer', 'stamm', 'business partner'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kunden-karte',
        label: 'Kundenkarte',
        icon: MapPin,
        module: '@/pages/crm/kunden-karte',
        preferredPath: 'crm/kunden-karte',
        keywords: ['kunden', 'karte', 'map', 'poi', 'crm', 'regional'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kunden-cockpit',
        label: 'Kunden-Cockpit',
        icon: Headset,
        module: '@/pages/crm/kunden-cockpit',
        preferredPath: 'crm/kunden-cockpit',
        keywords: ['kunden', 'cockpit', 'kontakt', 'wiedervorlage', 'telefon', 'whatsapp', 'crm', 'kontakthistorie'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'bestell-inbox',
        label: 'Bestell-Inbox',
        icon: MessageCircle,
        module: '@/pages/crm/bestell-inbox',
        preferredPath: 'crm/bestell-inbox',
        keywords: ['bestellung', 'whatsapp', 'inbox', 'posteingang', 'ai', 'futterbestellung', 'erfassung'],
        mcp: { businessDomain: 'sales', scope: 'sales:write' },
      },
      {
        id: 'bedarfsdeckung',
        label: 'Bedarfsdeckung',
        icon: Target,
        module: '@/pages/crm/bedarfsdeckung-cockpit',
        preferredPath: 'crm/bedarfsdeckung-cockpit',
        keywords: ['bedarf', 'deckung', 'durchdringung', 'cross-sell', 'luecke', 'share of wallet', 'next best offer', 'potenzial'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'durchdringungs-pipeline',
        label: 'Durchdringungs-Pipeline',
        icon: ListChecks,
        module: '@/pages/crm/durchdringungs-pipeline',
        preferredPath: 'crm/durchdringungs-pipeline',
        keywords: ['pipeline', 'durchdringung', 'arbeitsliste', 'chance', 'prioritaet', 'aussendienst', 'luecke', 'next best offer'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kunden-schnellauswahl',
        label: 'Kunden-Schnellauswahl',
        icon: Search,
        module: '@/pages/crm/kunden-schnellauswahl',
        preferredPath: 'crm/kunden-schnellauswahl',
        keywords: ['kunden', 'suche', 'schnellauswahl', 'lookup', 'auswahl'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'artikel',
        label: 'Artikel',
        icon: Package,
        module: '@/pages/artikel/liste',
        keywords: ['artikel', 'products', 'lager'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'unerledigte-auftrags-positionen',
        label: 'Unerledigte Auftrags-Positionen',
        icon: AlertCircle,
        module: '@/pages/verkauf/unerledigte-auftrags-positionen',
        preferredPath: 'verkauf/unerledigte-auftrags-positionen',
        keywords: ['unerledigte', 'auftrags', 'positionen', 'offene'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kommissions-auftraege',
        label: 'Kommissions-Aufträge',
        icon: FileText,
        module: '@/pages/verkauf/kommissions-auftraege',
        preferredPath: 'verkauf/kommissions-auftraege',
        keywords: ['kommissions', 'aufträge', 'kommission'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'betriebs-auftraege',
        label: 'Betriebs-Aufträge',
        icon: FileText,
        module: '@/pages/verkauf/betriebs-auftraege',
        preferredPath: 'verkauf/betriebs-auftraege',
        keywords: ['betriebs', 'aufträge', 'interne aufträge'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'dauerauftraege',
        label: 'Daueraufträge',
        icon: RefreshCw,
        module: '@/pages/verkauf/dauerauftraege',
        preferredPath: 'verkauf/dauerauftraege',
        keywords: ['dauerauftrag', 'wiederkehrend', 'abo', 'intervall'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'analytics',
        label: 'Vertriebsanalyse',
        icon: BarChart3,
        module: '@/pages/analytics',
        keywords: ['analytics'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'reports',
        label: 'Berichte',
        icon: FileText,
        module: '@/pages/reports',
        keywords: ['berichte', 'reports'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
    ],
  },
  {
    id: 'crm',
    label: 'CRM & Marketing',
    icon: UserCog,
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
    children: CRM_CHILDREN,
  },
  {
    id: 'vertreter',
    label: 'Vertreter & Provisionen',
    icon: Users2,
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
    children: [
      {
        id: 'vertreterprovisionen',
        label: 'Provisionsgruppen & -staffeln',
        icon: Euro,
        module: '@/pages/crm/vertreterprovisionen',
        preferredPath: 'crm/vertreterprovisionen',
        keywords: ['provisionen', 'vertreter', 'außendienst', 'staffel', 'provisionsgruppe'],
        mcp: { businessDomain: 'crm', scope: 'crm:read' },
      },
      {
        id: 'vertreterstamm',
        label: 'Vertreterstamm [VERT/VGRP]',
        icon: UserCog,
        module: '@/pages/crm/vertreterstamm',
        preferredPath: 'crm/vertreterstamm',
        keywords: ['vertreter', 'außendienst', 'vertretergruppe', 'vertreterstamm'],
        mcp: { businessDomain: 'crm', scope: 'crm:read' },
      },
    ],
  },
  {
    id: 'einkauf',
    label: 'Einkauf',
    icon: ShoppingCart,
    mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
    children: [
      {
        id: 'einkauf-dashboard',
        label: 'Dashboard',
        icon: BarChart3,
        module: '@/pages/dashboard/einkauf-dashboard',
        preferredPath: 'dashboard/einkauf',
        keywords: ['dashboard', 'einkauf'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlaege',
        label: 'Bestellvorschläge',
        icon: AlertCircle,
        module: '@/pages/einkauf/bestellvorschlaege',
        keywords: ['bestellvorschläge'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlag-lager',
        label: 'Bestellvorschlag Lager',
        icon: Package,
        module: '@/pages/einkauf/bestellvorschlag-lager',
        preferredPath: 'einkauf/bestellvorschlag-lager',
        keywords: ['bestellvorschlag', 'lager', 'mindestbestand'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlag-verkauf',
        label: 'Bestellvorschlag Verkauf',
        icon: ShoppingCart,
        module: '@/pages/einkauf/bestellvorschlag-verkauf',
        preferredPath: 'einkauf/bestellvorschlag-verkauf',
        keywords: ['bestellvorschlag', 'verkauf', 'aufträge'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlag-rohware',
        label: 'Bestellvorschlag Rohstoff',
        icon: Sprout,
        module: '@/pages/einkauf/bestellvorschlag-rohware',
        preferredPath: 'einkauf/bestellvorschlag-rohware',
        keywords: ['bestellvorschlag', 'rohstoff', 'bedarf', 'rohware'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellungen',
        label: 'Bestellungen',
        icon: FileText,
        module: '@/pages/einkauf/bestellungen-liste',
        preferredPath: 'einkauf/bestellungen',
        keywords: ['bestellungen'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'einkauf-lieferschein-erfassung',
        label: 'Eingehende Belege',
        icon: FileText,
        module: '@/pages/einkauf/lieferschein-erfassung',
        preferredPath: 'einkauf/lieferschein-erfassung',
        keywords: ['eingehende belege', 'einkauf lieferschein', 'wareneingang', 'kreditor'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferschein-frachtauftrag',
        label: 'Lieferschein/Frachtauftrag',
        icon: Truck,
        module: '@/pages/einkauf/lieferschein-frachtauftrag',
        preferredPath: 'einkauf/lieferschein-frachtauftrag',
        keywords: ['lieferschein', 'frachtauftrag'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'frachtauftraege-eingang',
        label: 'Frachtaufträge Eingang',
        icon: Truck,
        module: '@/pages/einkauf/frachtauftraege-eingang',
        preferredPath: 'einkauf/frachtauftraege-eingang',
        keywords: ['frachtaufträge', 'eingang', 'spediteur', 'pauschalfracht'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'wareneingang',
        label: 'Wareneingang',
        icon: Package,
        module: '@/pages/charge/wareneingang',
        keywords: ['wareneingang'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferanten',
        label: 'Lieferanten',
        icon: Users,
        module: '@/pages/einkauf/lieferanten-liste',
        keywords: ['lieferanten'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'warengruppen',
        label: 'Warengruppen',
        icon: Package,
        module: '@/pages/einkauf/warengruppen',
        keywords: ['warengruppen'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'mengeneinheiten',
        label: 'Mengeneinheiten & Gruppen',
        icon: Scale,
        module: '@/pages/stammdaten/mengeneinheiten',
        preferredPath: 'stammdaten/mengeneinheiten',
        keywords: ['mengeneinheit', 'einheitengruppe', 'umrechnung', 'kg', 'tonne'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'zahlungsbedingungen',
        label: 'Zahlungsbedingungen',
        icon: Euro,
        module: '@/pages/einkauf/zahlungsbedingungen',
        preferredPath: 'einkauf/zahlungsbedingungen',
        keywords: ['zahlungsbedingungen', 'skonto', 'zahlungsziel', 'zabd'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'anfragen',
        label: 'Anfragen (RFQ)',
        icon: FileText,
        module: '@/pages/einkauf/anfragen-liste',
        keywords: ['anfragen', 'rfq'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'anfrage-erfassung',
        label: 'Anfrage erfassen',
        icon: FileText,
        module: '@/pages/einkauf/anfrage-erfassung',
        preferredPath: 'einkauf/anfrage-erfassung',
        keywords: ['anfrage', 'rfq', 'erfassen', 'lieferant'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'angebote-einkauf',
        label: 'Angebote',
        icon: FileText,
        module: '@/pages/einkauf/angebote-liste',
        keywords: ['angebote', 'einkauf'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'rechnungseingaenge',
        label: 'Rechnungseingänge',
        icon: Euro,
        module: '@/pages/einkauf/rechnungseingaenge-liste',
        keywords: ['rechnungseingang', 'eingangsrechnung'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'rechnung-eingang-erfassung',
        label: 'Eingangsrechnung erfassen',
        icon: Euro,
        module: '@/pages/einkauf/rechnung-eingang-erfassung',
        preferredPath: 'einkauf/rechnung-eingang-erfassung',
        keywords: ['eingangsrechnung', 'rechnungseingang', 'erfassen', 'kreditor'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'rechnung-abgleich',
        label: 'Rechnungsabgleich',
        icon: Calculator,
        module: '@/pages/einkauf/rechnung-abgleich',
        keywords: ['abgleich', '3-wege'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'retouren',
        label: 'Retouren',
        icon: Truck,
        module: '@/pages/einkauf/retouren',
        keywords: ['retouren', 'rückgabe'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
      {
        id: 'disposition',
        label: 'Disposition',
        icon: Calculator,
        module: '@/pages/disposition/liste',
        keywords: ['disposition'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'commodity-position-matrix',
        label: 'Rohwaren-Positionsmatrix',
        icon: LayoutGrid,
        module: '@/pages/disposition/LstCommodityPositionMatrix',
        preferredPath: 'disposition/position-matrix',
        keywords: ['position', 'matrix', 'long', 'short', 'deckung'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'position-regeln',
        label: 'Position-Regeln',
        icon: Settings,
        module: '@/pages/disposition/FrmPositionRules',
        preferredPath: 'disposition/regeln',
        keywords: ['position', 'regeln', 'toleranz'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'coverage-monitor',
        label: 'Deckungsmonitor',
        icon: AlertCircle,
        module: '@/pages/disposition/FrmCoverageMonitor',
        preferredPath: 'disposition/coverage-monitor',
        keywords: ['coverage', 'deckung', 'lücken'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferantenbewertung',
        label: 'Lieferantenbewertung',
        icon: ShieldCheck,
        module: '@/pages/einkauf/lieferantenbewertung',
        keywords: ['lieferanten', 'bewertung', 'score'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferanten-dokumente',
        label: 'Lieferanten-Dokumente',
        icon: FileText,
        module: '@/pages/einkauf/lieferanten-dokumente',
        keywords: ['supplier', 'dokumente', 'nachweise'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
      {
        id: 'service-entry-sheets',
        label: 'Leistungsnachweise',
        icon: FileText,
        module: '@/pages/einkauf/service-entry-sheets',
        keywords: ['ses', 'service entry', 'leistung'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
      {
        id: 'audit-drilldown',
        label: 'Audit-Analyse',
        icon: Activity,
        module: '@/pages/einkauf/audit-drilldown',
        keywords: ['audit', 'belegkette', 'drilldown'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'edi-portal',
        label: 'EDI-Leitstand',
        icon: Activity,
        module: '@/pages/einkauf/edi-portal',
        keywords: ['edi', 'portal', 'ordner', 'messages'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
    ],
  },
  {
    id: 'artikel-stammdaten',
    label: 'Artikel-Stammdaten',
    icon: Package,
    mcp: { businessDomain: 'admin', scope: 'admin:read' },
    children: [
      {
        id: 'artikel-bestandteile',
        label: 'Artikel-Bestandteile',
        icon: Layers,
        module: '@/pages/stammdaten/artikelbestandteile',
        preferredPath: 'stammdaten/artikelbestandteile',
        keywords: ['bestandteile', 'inhaltsstoffe', 'qualität', 'analyse'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'artikel-verpackung',
        label: 'Artikelverpackung',
        icon: Box,
        module: '@/pages/stammdaten/artikelverpackung',
        preferredPath: 'stammdaten/artikelverpackung',
        keywords: ['verpackung', 'palette', 'karton', 'stück', 'vpk'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'individuelle-artikelnummern',
        label: 'Individuelle Artikelnummern',
        icon: Tag,
        module: '@/pages/stammdaten/individuelle-artikelnummern',
        preferredPath: 'stammdaten/individuelle-artikelnummern',
        keywords: ['individuelle', 'artikelnummer', 'partner', 'kunde', 'lieferant', 'mapping'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
    ],
  },
]
