import {
  Activity,
  ArrowUpDown,
  AlertCircle,
  BarChart3,
  Building2,
  Calendar,
  Calculator,
  Database,
  Euro,
  FileDown,
  FileText,
  FlaskConical,
  Globe,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Package,
  Plus,
  RefreshCw,
  Scale,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sprout,
  Tag,
  Target,
  Tractor,
  Truck,
  Upload,
  UserCog,
  Users,
  Zap,
  MapPin,
  Search,
  Sparkles,
  BookOpen,
  Users2,
  Layers,
  Box,
  Headset,
  MessageCircle,
  ListChecks,
  Inbox,
  CopyCheck,
  UserCheck,
  CalendarClock,
  LineChart,
  Boxes,
  Receipt,
  PackageCheck,
  Undo2,
} from 'lucide-react'
import type { RawNavItem } from '@/app/navigation/types'
import { ENABLE_PROSPECTING_UI } from '@/features/prospecting/feature-flags'

const CRM_CHILDREN: RawNavItem[] = [
  {
    id: 'kontakte',
    label: 'Kontakte',
    icon: Users,
    module: '@/pages/crm/kontakte-liste',
    keywords: ['kontakte'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'leads',
    label: 'Leads',
    icon: Target,
    module: '@/pages/crm/leads',
    keywords: ['leads'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'lead-generierung',
    label: 'Lead-Generierung',
    icon: Sparkles,
    module: '@/pages/crm/lead-generierung',
    preferredPath: 'crm/lead-generierung',
    keywords: ['lead', 'generierung', 'gap', 'lkv', 'potenzial', 'akquise', 'prospecting', 'region'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'aktivitaeten',
    label: 'Aktivitäten',
    icon: Calendar,
    module: '@/pages/crm/aktivitaeten',
    keywords: ['aktivitäten'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'betriebsprofile',
    label: 'Betriebsprofile',
    icon: Tractor,
    module: '@/pages/crm/betriebsprofile-liste',
    keywords: ['betriebsprofile'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  },
  {
    id: 'kampagnen',
    label: 'Kampagnen',
    icon: Zap,
    module: '@/pages/crm/campaigns',
    preferredPath: 'crm/campaigns',
    keywords: ['kampagnen', 'marketing', 'campaign'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'kampagnen-vorlagen',
    label: 'Kampagnen-Vorlagen',
    icon: FileText,
    module: '@/pages/crm/campaign-templates',
    preferredPath: 'crm/campaign-templates',
    keywords: ['vorlagen', 'templates', 'kampagnen'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'kampagnen-performance',
    label: 'Kampagnen-Performance',
    icon: BarChart3,
    module: '@/pages/crm/campaign-performance-dashboard',
    preferredPath: 'crm/campaign-performance',
    keywords: ['performance', 'analytics', 'kampagnen'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'segmente',
    label: 'Segmente',
    icon: Users,
    module: '@/pages/crm/segments',
    preferredPath: 'crm/segments',
    keywords: ['segmente', 'zielgruppen'],
    mcp: { businessDomain: 'crm', scope: 'marketing:read' },
  },
  {
    id: 'einwilligungen',
    label: 'Einwilligungen',
    icon: ShieldCheck,
    module: '@/pages/crm/consent-management',
    preferredPath: 'crm/consents',
    keywords: ['consent', 'einwilligung', 'dsgvo'],
    mcp: { businessDomain: 'crm', scope: 'compliance:read' },
  },
  {
    id: 'dsgvo-anfragen',
    label: 'DSGVO-Anfragen',
    icon: ShieldCheck,
    module: '@/pages/crm/gdpr-requests',
    preferredPath: 'crm/gdpr-requests',
    keywords: ['dsgvo', 'gdpr', 'datenschutz'],
    mcp: { businessDomain: 'crm', scope: 'compliance:read' },
  },
  {
    id: 'verarbeitungsverzeichnis',
    label: 'Verarbeitungsverzeichnis (Art. 30)',
    icon: ShieldCheck,
    module: '@/pages/compliance/verarbeitungsverzeichnis',
    preferredPath: 'compliance/verarbeitungsverzeichnis',
    keywords: ['dsgvo', 'art30', 'ropa', 'verarbeitungsverzeichnis', 'datenschutz'],
    mcp: { businessDomain: 'compliance', scope: 'compliance:write' },
  },
  {
    id: 'datenpannen',
    label: 'Datenpannen-Meldeprozess (Art. 33)',
    icon: ShieldCheck,
    module: '@/pages/compliance/datenpannen',
    preferredPath: 'compliance/datenpannen',
    keywords: ['dsgvo', 'art33', 'datenpanne', 'breach', 'meldepflicht', '72h', 'datenschutz'],
    mcp: { businessDomain: 'compliance', scope: 'compliance:write' },
  },
]

if (ENABLE_PROSPECTING_UI) {
  CRM_CHILDREN.splice(2, 0, {
    id: 'prospecting',
    label: 'Potenzialsuche',
    icon: Search,
    module: '@/pages/prospecting/LeadExplorer',
    preferredPath: 'prospecting/leads',
    keywords: ['prospecting', 'gap', 'potenzial'],
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
  })
}

export const RAW_NAV_SECTIONS: RawNavItem[] = [
  {
    id: 'kontrakte',
    label: 'Kontrakte',
    icon: BookOpen,
    mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
    children: [
      {
        id: 'kontrakt-uebersicht',
        label: 'Kontraktübersicht',
        icon: FileText,
        module: '@/pages/kontrakte/LstKontraktUebersicht',
        preferredPath: 'kontrakte/kontrakt-uebersicht',
        keywords: ['kontrakte', 'übersicht', 'liste'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'kontrakt-erfuellung',
        label: 'Kontrakt-Erfüllung',
        icon: ListChecks,
        module: '@/pages/agrar/kontrakt-erfuellung',
        preferredPath: 'agrar/kontrakt-erfuellung',
        keywords: ['kontrakt', 'erfüllung', 'abruf', 'abgerufen', 'offen', 'engagement', 'überfällig', 'fixierung', 'matif', 'einkauf', 'verkauf'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'kontrakt-fixierung',
        label: 'Kontrakt-Fixierung',
        icon: LineChart,
        module: '@/pages/agrar/kontrakt-fixierung',
        preferredPath: 'agrar/kontrakt-fixierung',
        keywords: ['kontrakt', 'fixierung', 'teilfixierung', 'matif', 'marktwert', 'bewertung', 'prämie', 'basis', 'preisabsicherung', 'mark-to-market'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
      },
      {
        id: 'kontrakt-engagement',
        label: 'Kontrakt-Engagement',
        icon: Boxes,
        module: '@/pages/agrar/kontrakt-engagement',
        preferredPath: 'agrar/kontrakt-engagement',
        keywords: ['kontrakt', 'engagement', 'offen', 'netto', 'position', 'artikel', 'partei', 'mahnung', 'kontraktmahnung', 'überfällig', 'einkauf', 'verkauf'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
      },
      {
        id: 'kontrakt-settlement',
        label: 'Kontrakt-Settlement',
        icon: Receipt,
        module: '@/pages/agrar/kontrakt-settlement',
        preferredPath: 'agrar/kontrakt-settlement',
        keywords: ['kontrakt', 'settlement', 'abrechnung', 'übergabe', 'storno', 'stornieren', 'bewegung', 'abruf', 'fixierung', 'gutschrift'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
      },
      {
        id: 'kontrakt-alarm',
        label: 'Alarm-Dashboard',
        icon: FileText,
        module: '@/pages/kontrakte/KontraktAlarmDashboard',
        preferredPath: 'kontrakte/kontrakt-alarm-dashboard',
        keywords: ['kontrakt', 'alarm', 'fälligkeit', 'warnung'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'kontrakt-positionsmonitor',
        label: 'Positionsmonitor',
        icon: FileText,
        module: '@/pages/kontrakte/KontraktPositionsmonitor',
        preferredPath: 'kontrakte/kontrakt-positionsmonitor',
        keywords: ['kontrakt', 'positionen', 'monitor', 'status'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'kontraktklassen',
        label: 'Kontraktklassen',
        icon: FileText,
        module: '@/pages/kontrakte/kontraktklassen',
        preferredPath: 'kontrakte/kontraktklassen',
        keywords: ['kontraktklassen', 'fixpreis', 'basis', 'prämie', 'poolpreis'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'kontrakt-mengenzeitraeume',
        label: 'Mengenzeiträume & Zu-/Abschläge',
        icon: FileText,
        module: '@/pages/kontrakte/mengenzeitraeume',
        preferredPath: 'kontrakte/mengenzeitraeume',
        keywords: ['mengenzeiträume', 'staffel', 'abnahme', 'zuschlag', 'abschlag', 'kontrakt'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
    ],
  },
  {
    id: 'preise',
    label: 'Preise & Kalkulation',
    icon: Calculator,
    mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
    children: [
      {
        id: 'preis-kalkulation',
        label: 'Preis-Kalkulation',
        icon: Calculator,
        module: '@/pages/preise/kalkulation',
        preferredPath: 'preise/kalkulation',
        keywords: ['preis', 'kalkulation', 'berechnung', 'marge'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'preis-historie',
        label: 'Preishistorie',
        icon: Calculator,
        module: '@/pages/preise/historie',
        preferredPath: 'preise/historie',
        keywords: ['preis', 'historie', 'verlauf', 'entwicklung'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'preis-konditionen',
        label: 'Konditionen',
        icon: Calculator,
        module: '@/pages/preise/konditionen',
        preferredPath: 'preise/konditionen',
        keywords: ['konditionen', 'rabatt', 'preis', 'staffel'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'zu-abschlaggruppen',
        label: 'Zu-/Abschlaggruppen',
        icon: ArrowUpDown,
        module: '@/pages/preise/zu-abschlaggruppen',
        preferredPath: 'preise/zu-abschlaggruppen',
        keywords: ['zuschlag', 'abschlag', 'gruppen', 'klassen', 'konditionen', 'zagr', 'zakl'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'rabattgruppen',
        label: 'Rabattgruppen & -klassen [RAG/RAK]',
        icon: Scale,
        module: '@/pages/preise/rabattgruppen',
        preferredPath: 'preise/rabattgruppen',
        keywords: ['rabatt', 'rabattgruppe', 'rabattklasse', 'rag', 'rak', 'rabattsatz', 'konditionen'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'individualpreise',
        label: 'Individualpreise [PRI/PRIE]',
        icon: Tag,
        module: '@/pages/preise/individualpreise',
        preferredPath: 'preise/individualpreise',
        keywords: ['individualpreis', 'pri', 'prie', 'kundenpreis', 'lieferantenpreis', 'staffelpreis'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'konditionssystem',
        label: 'Konditionssystem KOND-001',
        icon: Calculator,
        module: '@/pages/konditionen/konditionssystem',
        preferredPath: 'konditionen/konditionssystem',
        keywords: ['konditionssystem', 'preisliste', 'staffelpreis', 'rabattgruppe', 'rabattklasse', 'rabattsatz', 'individualpreis', 'preisfindung', 'kond'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
      },
    ],
  },
  {
    id: 'genossenschaft',
    label: 'Genossenschaft',
    icon: Users2,
    mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
    children: [
      {
        id: 'genossenschaft-mitglieder',
        label: 'Mitglieder',
        icon: Users,
        module: '@/pages/genossenschaft/mitglieder',
        preferredPath: 'genossenschaft/mitglieder',
        keywords: ['mitglieder', 'genossenschaft', 'geschäftsanteile'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
    ],
  },
  {
    id: 'verkauf',
    label: 'Verkauf',
    icon: ShoppingCart,
    mcp: { businessDomain: 'sales', scope: 'sales:read' },
    children: [
      {
        id: 'sales-dashboard',
        label: 'Dashboard',
        icon: BarChart3,
        module: '@/pages/dashboard/sales-dashboard',
        preferredPath: 'dashboard/sales',
        keywords: ['dashboard', 'kpi', 'analytics'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'ausgehende-belege',
        label: 'Ausgehende Belege',
        icon: Receipt,
        keywords: ['ausgehende belege', 'belege erfassen', 'verkauf', 'o2c'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
        children: [
          {
            id: 'ausgehend-angebot',
            label: 'Angebot erfassen',
            icon: FileText,
            module: '@/pages/sales/angebot-erstellen',
            preferredPath: 'sales/angebot/neu',
            keywords: ['angebot', 'angebot-erfassung', 'angebot-erstellen', 'ausgehende belege'],
            mcp: { businessDomain: 'sales', scope: 'sales:read' },
          },
          {
            id: 'ausgehend-auftrag',
            label: 'Auftrag erfassen',
            icon: FileText,
            module: '@/pages/sales/order-editor',
            preferredPath: 'sales/order',
            keywords: ['auftrag', 'auftrags-erfassung', 'kundenauftrag', 'ausgehende belege'],
            mcp: { businessDomain: 'sales', scope: 'sales:read' },
          },
          {
            id: 'ausgehend-lieferschein',
            label: 'Sofort-Lieferschein erfassen',
            icon: Truck,
            module: '@/pages/verkauf/lieferschein-erfassung',
            preferredPath: 'verkauf/lieferschein-erfassung',
            keywords: ['sofort-lieferschein', 'lieferschein-erfassung', 'ausgehender lieferschein', 'lieferung', 'ausgehende belege'],
            mcp: { businessDomain: 'sales', scope: 'sales:read' },
          },
          {
            id: 'ausgehend-rechnung',
            label: 'Rechnung erfassen',
            icon: FileText,
            module: '@/pages/sales/invoice-editor',
            preferredPath: 'sales/invoice',
            keywords: ['rechnung', 'rechnung-erfassung', 'ausgangsrechnung', 'ausgehende belege'],
            mcp: { businessDomain: 'sales', scope: 'sales:read' },
          },
          {
            id: 'ausgehend-gutschrift',
            label: 'Gutschrift erfassen',
            icon: Undo2,
            module: '@/pages/sales/credit-note-editor',
            preferredPath: 'sales/credit-notes',
            keywords: ['gutschrift', 'credit note', 'storno', 'ausgehende belege'],
            mcp: { businessDomain: 'sales', scope: 'sales:write' },
          },
        ],
      },
      {
        id: 'angebot',
        label: 'Angebote',
        icon: FileText,
        module: '@/pages/sales/angebot-erstellen',
        preferredPath: 'sales/angebote',
        keywords: ['angebot', 'angebot-erfassung', 'angebot-erstellen'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'auftragskette',
        label: 'Auftragskette (O2C)',
        icon: ArrowUpDown,
        module: '@/pages/sales/auftragskette',
        preferredPath: 'sales/auftragskette',
        keywords: ['o2c', 'order-to-cash', 'auftragskette', 'angebot', 'auftrag', 'lieferschein', 'rechnung', 'kette', 'durchgängig', 'sales'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'auftrag-lieferschein-abgleich',
        label: 'Auftrag-Lieferschein-Abgleich',
        icon: PackageCheck,
        module: '@/pages/sales/auftrag-lieferschein-abgleich',
        preferredPath: 'sales/auftrag-lieferschein-abgleich',
        keywords: ['o2c', 'abgleich', 'match', 'positionen', 'auftrag', 'lieferschein', 'teillieferung', 'überlieferung', 'offen', 'sales'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kreditlimit-pruefung',
        label: 'Kreditlimit-Prüfung',
        icon: ShieldCheck,
        module: '@/pages/sales/kreditlimit-pruefung',
        preferredPath: 'sales/kreditlimit-pruefung',
        keywords: ['kreditlimit', 'kredit', 'limit', 'bonität', 'exposure', 'ampel', 'sperre', 'auftrag', 'o2c', 'sales', 'debitor'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'lieferung-storno',
        label: 'Lieferung-Storno / Gutschrift',
        icon: Undo2,
        module: '@/pages/sales/lieferung-storno',
        preferredPath: 'sales/lieferung-storno',
        keywords: ['storno', 'stornieren', 'gutschrift', 'lieferschein', 'rücknahme', 'auftrag', 'o2c', 'sales'],
        mcp: { businessDomain: 'sales', scope: 'sales:write' },
      },
      {
        id: 'auftrag',
        label: 'Aufträge',
        icon: FileText,
        module: '@/pages/sales/order-editor',
        preferredPath: 'sales/order',
        keywords: ['aufträge'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'lieferung',
        label: 'Lieferungen',
        icon: Truck,
        module: '@/pages/verkauf/lieferschein-erfassung',
        preferredPath: 'verkauf/lieferschein-erfassung',
        keywords: ['lieferungen', 'lieferschein'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'rechnung',
        label: 'Rechnungen',
        icon: FileText,
        module: '@/pages/sales/invoice-editor',
        preferredPath: 'sales/invoice',
        keywords: ['rechnungen'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kunden',
        label: 'Kunden',
        icon: Users,
        module: '@/pages/verkauf/kunden-liste',
        preferredPath: 'verkauf/kunden-liste',
        keywords: ['kunden', 'crm', 'customer', 'stamm', 'business partner'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kunden-karte',
        label: 'Kundenkarte',
        icon: MapPin,
        module: '@/pages/crm/kunden-karte',
        preferredPath: 'crm/kunden-karte',
        keywords: ['kunden', 'karte', 'map', 'poi', 'crm', 'regional'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kim-cockpit',
        label: 'KIM – Kunde im Mittelpunkt',
        icon: Headset,
        module: '@/pages/crm/kim/index',
        preferredPath: 'crm',
        keywords: ['kim', 'kunde', '360', 'cockpit', 'kundenstamm', 'crm', 'dossier', 'neuroai', 'kontakthistorie'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        // DEPRECATED (KIM-DEPRECATE-COCKPIT-001): durch KIM (/crm) abgelöst; Eintrag
        // leitet via Redirect-Seite auf das KIM-360°-Cockpit.
        id: 'kunden-cockpit',
        label: 'Kunden-Cockpit (abgelöst → KIM)',
        icon: Headset,
        module: '@/pages/crm/kunden-cockpit',
        preferredPath: 'crm/kunden-cockpit',
        keywords: ['kunden', 'cockpit', 'kontakt', 'wiedervorlage', 'telefon', 'whatsapp', 'crm', 'kontakthistorie', 'kim', 'abgelöst'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'bestell-inbox',
        label: 'Bestell-Inbox',
        icon: MessageCircle,
        module: '@/pages/crm/bestell-inbox',
        preferredPath: 'crm/bestell-inbox',
        keywords: ['bestellung', 'whatsapp', 'inbox', 'posteingang', 'ai', 'futterbestellung', 'erfassung'],
        mcp: { businessDomain: 'sales', scope: 'sales:write' },
      },
      {
        id: 'klaerfall-inbox',
        label: 'Klärfall-Inbox',
        icon: Inbox,
        module: '@/pages/crm/klaerfall-inbox',
        preferredPath: 'crm/klaerfall-inbox',
        keywords: ['klärfall', 'klaerfall', 'inbox', 'auto-capture', 'unzugeordnet', 'telefon', 'email', 'whatsapp', 'transkript', 'kontakt', 'zuordnen', 'kim'],
        mcp: { businessDomain: 'sales', scope: 'sales:write' },
      },
      {
        id: 'mail-arbeitsplatz',
        label: 'Mail-Arbeitsplatz',
        icon: Inbox,
        module: '@/pages/crm/mail-arbeitsplatz',
        preferredPath: 'crm/mail-arbeitsplatz',
        keywords: ['mail', 'email', 'rollenpostfach', 'posteingang', 'anlage', 'entwurf', 'senden'],
        mcp: { businessDomain: 'sales', scope: 'sales:write' },
      },
      {
        id: 'crm-dubletten',
        label: 'Kunden-Dubletten',
        icon: CopyCheck,
        module: '@/pages/crm/dubletten',
        preferredPath: 'crm/dubletten',
        keywords: ['dubletten', 'duplikate', 'doppelanlage', 'zusammenführen', 'merge', 'kunden', 'datenqualität', 'crm'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'crm-kunden-zuordnung',
        label: 'Kunden-Zuordnung',
        icon: UserCheck,
        module: '@/pages/crm/kunden-zuordnung',
        preferredPath: 'crm/kunden-zuordnung',
        keywords: ['ownership', 'zuordnung', 'außendienst', 'aussendienst', 'innendienst', 'vertreter', 'übergabe', 'betreuer', 'kunden', 'crm'],
        mcp: { businessDomain: 'sales', scope: 'sales:write' },
      },
      {
        id: 'crm-wiedervorlagen',
        label: 'Wiedervorlagen',
        icon: CalendarClock,
        module: '@/pages/crm/wiedervorlagen',
        preferredPath: 'crm/wiedervorlagen',
        keywords: ['wiedervorlage', 'aufgaben', 'todo', 'fällig', 'überfällig', 'serviceabschluss', 'erledigen', 'kontakt', 'crm'],
        mcp: { businessDomain: 'sales', scope: 'sales:write' },
      },
      {
        id: 'bedarfsdeckung',
        label: 'Bedarfsdeckung',
        icon: Target,
        module: '@/pages/crm/bedarfsdeckung-cockpit',
        preferredPath: 'crm/bedarfsdeckung-cockpit',
        keywords: ['bedarf', 'deckung', 'durchdringung', 'cross-sell', 'luecke', 'share of wallet', 'next best offer', 'potenzial'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'durchdringungs-pipeline',
        label: 'Durchdringungs-Pipeline',
        icon: ListChecks,
        module: '@/pages/crm/durchdringungs-pipeline',
        preferredPath: 'crm/durchdringungs-pipeline',
        keywords: ['pipeline', 'durchdringung', 'arbeitsliste', 'chance', 'prioritaet', 'aussendienst', 'luecke', 'next best offer'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kunden-schnellauswahl',
        label: 'Kunden-Schnellauswahl',
        icon: Search,
        module: '@/pages/crm/kunden-schnellauswahl',
        preferredPath: 'crm/kunden-schnellauswahl',
        keywords: ['kunden', 'suche', 'schnellauswahl', 'lookup', 'auswahl'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'artikel',
        label: 'Artikel',
        icon: Package,
        module: '@/pages/artikel/liste',
        preferredPath: 'artikel',
        keywords: ['artikel', 'artikelstamm', 'products', 'lager'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'unerledigte-auftrags-positionen',
        label: 'Unerledigte Auftrags-Positionen',
        icon: AlertCircle,
        module: '@/pages/verkauf/unerledigte-auftrags-positionen',
        preferredPath: 'verkauf/unerledigte-auftrags-positionen',
        keywords: ['unerledigte', 'auftrags', 'positionen', 'offene'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'kommissions-auftraege',
        label: 'Kommissions-Aufträge',
        icon: FileText,
        module: '@/pages/verkauf/kommissions-auftraege',
        preferredPath: 'verkauf/kommissions-auftraege',
        keywords: ['kommissions', 'aufträge', 'kommission'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'betriebs-auftraege',
        label: 'Betriebs-Aufträge',
        icon: FileText,
        module: '@/pages/verkauf/betriebs-auftraege',
        preferredPath: 'verkauf/betriebs-auftraege',
        keywords: ['betriebs', 'aufträge', 'interne aufträge'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'dauerauftraege',
        label: 'Daueraufträge',
        icon: RefreshCw,
        module: '@/pages/verkauf/dauerauftraege',
        preferredPath: 'verkauf/dauerauftraege',
        keywords: ['dauerauftrag', 'wiederkehrend', 'abo', 'intervall'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'analytics',
        label: 'Vertriebsanalyse',
        icon: BarChart3,
        module: '@/pages/analytics',
        keywords: ['analytics'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
      {
        id: 'reports',
        label: 'Berichte',
        icon: FileText,
        module: '@/pages/reports',
        keywords: ['berichte', 'reports'],
        mcp: { businessDomain: 'sales', scope: 'sales:read' },
      },
    ],
  },
  {
    id: 'crm',
    label: 'CRM & Marketing',
    icon: UserCog,
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
    children: CRM_CHILDREN,
  },
  {
    id: 'vertreter',
    label: 'Vertreter & Provisionen',
    icon: Users2,
    mcp: { businessDomain: 'crm', scope: 'crm:read' },
    children: [
      {
        id: 'vertreterprovisionen',
        label: 'Provisionsgruppen & -staffeln',
        icon: Euro,
        module: '@/pages/crm/vertreterprovisionen',
        preferredPath: 'crm/vertreterprovisionen',
        keywords: ['provisionen', 'vertreter', 'außendienst', 'staffel', 'provisionsgruppe'],
        mcp: { businessDomain: 'crm', scope: 'crm:read' },
      },
      {
        id: 'vertreterstamm',
        label: 'Vertreterstamm [VERT/VGRP]',
        icon: UserCog,
        module: '@/pages/crm/vertreterstamm',
        preferredPath: 'crm/vertreterstamm',
        keywords: ['vertreter', 'außendienst', 'vertretergruppe', 'vertreterstamm'],
        mcp: { businessDomain: 'crm', scope: 'crm:read' },
      },
    ],
  },
  {
    id: 'einkauf',
    label: 'Einkauf',
    icon: ShoppingCart,
    mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
    children: [
      {
        id: 'einkauf-dashboard',
        label: 'Dashboard',
        icon: BarChart3,
        module: '@/pages/dashboard/einkauf-dashboard',
        preferredPath: 'dashboard/einkauf',
        keywords: ['dashboard', 'einkauf'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'eingehende-belege',
        label: 'Eingehende Belege',
        icon: Inbox,
        keywords: ['eingehende belege', 'belege erfassen', 'einkauf', 'p2p'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
        children: [
          {
            id: 'eingehend-anlieferavis',
            label: 'Anlieferavis erfassen',
            icon: Truck,
            module: '@/pages/einkauf/anlieferavis',
            preferredPath: 'einkauf/anlieferavis/neu',
            keywords: ['anlieferavis', 'lieferavis', 'avis', 'eingehende belege'],
            mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
          },
          {
            id: 'eingehend-wareneingang',
            label: 'Wareneingang erfassen',
            icon: PackageCheck,
            module: '@/pages/einkauf/wareneingang',
            preferredPath: 'einkauf/wareneingang',
            keywords: ['wareneingang', 'goods receipt', 'eingehende belege'],
            mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
          },
          {
            id: 'eingehend-lieferschein',
            label: 'Lieferschein Eingang erfassen',
            icon: FileText,
            module: '@/pages/einkauf/lieferschein-erfassung',
            preferredPath: 'einkauf/lieferschein-erfassung',
            keywords: ['lieferschein eingang', 'eingehender lieferschein', 'einkauf lieferschein', 'eingehende belege'],
            mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
          },
          {
            id: 'eingehend-rechnung',
            label: 'Rechnungseingang erfassen',
            icon: Euro,
            module: '@/pages/einkauf/rechnung-eingang-erfassung',
            preferredPath: 'einkauf/rechnung-eingang-erfassung',
            keywords: ['rechnungseingang', 'eingangsrechnung', 'kreditorenrechnung', 'eingehende belege'],
            mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
          },
        ],
      },
      {
        id: 'bestellvorschlaege',
        label: 'Bestellvorschläge',
        icon: AlertCircle,
        module: '@/pages/einkauf/bestellvorschlaege',
        keywords: ['bestellvorschläge'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'wareneingangsabgleich',
        label: 'Wareneingangs-Abgleich',
        icon: ListChecks,
        module: '@/pages/einkauf/wareneingangsabgleich',
        preferredPath: 'einkauf/wareneingangsabgleich',
        keywords: ['3-wege-match', 'wareneingang', 'abgleich', 'bestellung', 'matching', 'abweichung', 'teillieferung', 'überlieferung', 'einkauf', 'procurement'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlag-lager',
        label: 'Bestellvorschlag Lager',
        icon: Package,
        module: '@/pages/einkauf/bestellvorschlag-lager',
        preferredPath: 'einkauf/bestellvorschlag-lager',
        keywords: ['bestellvorschlag', 'lager', 'mindestbestand'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlag-verkauf',
        label: 'Bestellvorschlag Verkauf',
        icon: ShoppingCart,
        module: '@/pages/einkauf/bestellvorschlag-verkauf',
        preferredPath: 'einkauf/bestellvorschlag-verkauf',
        keywords: ['bestellvorschlag', 'verkauf', 'aufträge'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellvorschlag-rohware',
        label: 'Bestellvorschlag Rohstoff',
        icon: Sprout,
        module: '@/pages/einkauf/bestellvorschlag-rohware',
        preferredPath: 'einkauf/bestellvorschlag-rohware',
        keywords: ['bestellvorschlag', 'rohstoff', 'bedarf', 'rohware'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'bestellungen',
        label: 'Bestellungen',
        icon: FileText,
        module: '@/pages/einkauf/bestellungen-liste',
        preferredPath: 'einkauf/bestellungen',
        keywords: ['bestellungen'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'einkauf-lieferschein-erfassung',
        label: 'Eingehende Belege',
        icon: FileText,
        module: '@/pages/einkauf/lieferschein-erfassung',
        preferredPath: 'einkauf/lieferschein-erfassung',
        keywords: ['eingehende belege', 'einkauf lieferschein', 'wareneingang', 'kreditor'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferschein-frachtauftrag',
        label: 'Lieferschein/Frachtauftrag',
        icon: Truck,
        module: '@/pages/einkauf/lieferschein-frachtauftrag',
        preferredPath: 'einkauf/lieferschein-frachtauftrag',
        keywords: ['lieferschein', 'frachtauftrag'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'frachtauftraege-eingang',
        label: 'Frachtaufträge Eingang',
        icon: Truck,
        module: '@/pages/einkauf/frachtauftraege-eingang',
        preferredPath: 'einkauf/frachtauftraege-eingang',
        keywords: ['frachtaufträge', 'eingang', 'spediteur', 'pauschalfracht'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'wareneingang',
        label: 'Wareneingang',
        icon: Package,
        module: '@/pages/charge/wareneingang',
        keywords: ['wareneingang'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferanten',
        label: 'Lieferanten',
        icon: Users,
        module: '@/pages/einkauf/lieferanten-liste',
        keywords: ['lieferanten'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'warengruppen',
        label: 'Warengruppen',
        icon: Package,
        module: '@/pages/einkauf/warengruppen',
        keywords: ['warengruppen'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'mengeneinheiten',
        label: 'Mengeneinheiten & Gruppen',
        icon: Scale,
        module: '@/pages/stammdaten/mengeneinheiten',
        preferredPath: 'stammdaten/mengeneinheiten',
        keywords: ['mengeneinheit', 'einheitengruppe', 'umrechnung', 'kg', 'tonne'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'zahlungsbedingungen',
        label: 'Zahlungsbedingungen',
        icon: Euro,
        module: '@/pages/einkauf/zahlungsbedingungen',
        preferredPath: 'einkauf/zahlungsbedingungen',
        keywords: ['zahlungsbedingungen', 'skonto', 'zahlungsziel', 'zabd'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'anfragen',
        label: 'Anfragen (RFQ)',
        icon: FileText,
        module: '@/pages/einkauf/anfragen-liste',
        keywords: ['anfragen', 'rfq'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'anfrage-erfassung',
        label: 'Anfrage erfassen',
        icon: FileText,
        module: '@/pages/einkauf/anfrage-erfassung',
        preferredPath: 'einkauf/anfrage-erfassung',
        keywords: ['anfrage', 'rfq', 'erfassen', 'lieferant'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'angebote-einkauf',
        label: 'Angebote',
        icon: FileText,
        module: '@/pages/einkauf/angebote-liste',
        keywords: ['angebote', 'einkauf'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'rechnungseingaenge',
        label: 'Rechnungseingänge',
        icon: Euro,
        module: '@/pages/einkauf/rechnungseingaenge-liste',
        keywords: ['rechnungseingang', 'eingangsrechnung'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'rechnung-eingang-erfassung',
        label: 'Eingangsrechnung erfassen',
        icon: Euro,
        module: '@/pages/einkauf/rechnung-eingang-erfassung',
        preferredPath: 'einkauf/rechnung-eingang-erfassung',
        keywords: ['eingangsrechnung', 'rechnungseingang', 'erfassen', 'kreditor'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'rechnung-abgleich',
        label: 'Rechnungsabgleich',
        icon: Calculator,
        module: '@/pages/einkauf/rechnung-abgleich',
        keywords: ['abgleich', '3-wege'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'retouren',
        label: 'Retouren',
        icon: Truck,
        module: '@/pages/einkauf/retouren',
        keywords: ['retouren', 'rückgabe'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
      {
        id: 'disposition',
        label: 'Disposition',
        icon: Calculator,
        module: '@/pages/disposition/liste',
        keywords: ['disposition'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'commodity-position-matrix',
        label: 'Rohwaren-Positionsmatrix',
        icon: LayoutGrid,
        module: '@/pages/disposition/LstCommodityPositionMatrix',
        preferredPath: 'disposition/position-matrix',
        keywords: ['position', 'matrix', 'long', 'short', 'deckung'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'position-regeln',
        label: 'Position-Regeln',
        icon: Settings,
        module: '@/pages/disposition/FrmPositionRules',
        preferredPath: 'disposition/regeln',
        keywords: ['position', 'regeln', 'toleranz'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'coverage-monitor',
        label: 'Deckungsmonitor',
        icon: AlertCircle,
        module: '@/pages/disposition/FrmCoverageMonitor',
        preferredPath: 'disposition/coverage-monitor',
        keywords: ['coverage', 'deckung', 'lücken'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferantenbewertung',
        label: 'Lieferantenbewertung',
        icon: ShieldCheck,
        module: '@/pages/einkauf/lieferantenbewertung',
        keywords: ['lieferanten', 'bewertung', 'score'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'lieferanten-dokumente',
        label: 'Lieferanten-Dokumente',
        icon: FileText,
        module: '@/pages/einkauf/lieferanten-dokumente',
        keywords: ['supplier', 'dokumente', 'nachweise'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
      {
        id: 'service-entry-sheets',
        label: 'Leistungsnachweise',
        icon: FileText,
        module: '@/pages/einkauf/service-entry-sheets',
        keywords: ['ses', 'service entry', 'leistung'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
      {
        id: 'audit-drilldown',
        label: 'Audit-Analyse',
        icon: Activity,
        module: '@/pages/einkauf/audit-drilldown',
        keywords: ['audit', 'belegkette', 'drilldown'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:read' },
      },
      {
        id: 'edi-portal',
        label: 'EDI-Leitstand',
        icon: Activity,
        module: '@/pages/einkauf/edi-portal',
        keywords: ['edi', 'portal', 'ordner', 'messages'],
        mcp: { businessDomain: 'procurement', scope: 'procurement:write' },
      },
    ],
  },
  {
    id: 'artikel-stammdaten',
    label: 'Artikel-Stammdaten',
    icon: Package,
    mcp: { businessDomain: 'admin', scope: 'admin:read' },
    children: [
      {
        id: 'artikelstamm',
        label: 'Artikelstamm',
        icon: Package,
        module: '@/pages/artikel/liste',
        preferredPath: 'artikel',
        keywords: ['artikel', 'artikelstamm', 'artikel anlegen', 'artikel pflegen', 'stammdaten', 'inaktiv setzen', 'artikelgruppe', 'warengruppe', 'alternative produkte'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'artikel-neu',
        label: 'Artikel neu anlegen',
        icon: Plus,
        module: '@/pages/artikel/stamm',
        preferredPath: 'artikel/neu',
        keywords: ['artikel neu', 'artikel anlegen', 'neuer artikel', 'artikelstamm', 'stammdaten'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'artikel-bestandteile',
        label: 'Artikel-Bestandteile',
        icon: Layers,
        module: '@/pages/stammdaten/artikelbestandteile',
        preferredPath: 'stammdaten/artikelbestandteile',
        keywords: ['bestandteile', 'inhaltsstoffe', 'qualität', 'analyse'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'artikel-stoffstrom',
        label: 'Stoffstrom & THG',
        icon: Layers,
        module: '@/pages/stammdaten/artikel-stoffstrom',
        preferredPath: 'stammdaten/artikel-stoffstrom',
        keywords: ['stoffstrom', 'thg', 'co2', 'nachhaltigkeit', 'iscc', 'red', 'anbauland'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'artikel-verpackung',
        label: 'Artikelverpackung',
        icon: Box,
        module: '@/pages/stammdaten/artikelverpackung',
        preferredPath: 'stammdaten/artikelverpackung',
        keywords: ['verpackung', 'palette', 'karton', 'stück', 'vpk'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'individuelle-artikelnummern',
        label: 'Individuelle Artikelnummern',
        icon: Tag,
        module: '@/pages/stammdaten/individuelle-artikelnummern',
        preferredPath: 'stammdaten/individuelle-artikelnummern',
        keywords: ['individuelle', 'artikelnummer', 'partner', 'kunde', 'lieferant', 'mapping'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
    ],
  },
]
