import {
  Activity,
  ArrowUpDown,
  AlertCircle,
  BarChart3,
  Building2,
  Calendar,
  Calculator,
  Database,
  Euro,
  FileDown,
  FileText,
  FlaskConical,
  Globe,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Mic,
  Package,
  RefreshCw,
  Scale,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sprout,
  Target,
  Tractor,
  Truck,
  Upload,
  UserCog,
  Users,
  Zap,
  Search,
  BookOpen,
  ReceiptText,
} from 'lucide-react'
import type { RawNavItem } from '@/app/navigation/types'
import { ENABLE_PROSPECTING_UI } from '@/features/prospecting/feature-flags'

export const RAW_NAV_SECTIONS: RawNavItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: LayoutDashboard,
    module: '@/pages/start-dashboard',
    preferredPath: '/',
    mcp: { businessDomain: 'core', scope: 'core:read' },
  },
  {
    id: 'workflow',
    label: 'Workflows',
    icon: Zap,
    mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
    children: [
      {
        id: 'workflow-monitoring',
        label: 'Monitoring',
        icon: Activity,
        module: '@/pages/workflow/workflow-monitoring',
        keywords: ['workflow', 'monitoring'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
      {
        id: 'workflow-regeln',
        label: 'Regeln',
        icon: Settings,
        module: '@/pages/workflow/workflow-regeln',
        keywords: ['workflow', 'regeln', 'rules'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:write' },
      },
      {
        id: 'workflow-sandbox',
        label: 'Sandbox',
        icon: FlaskConical,
        module: '@/pages/workflow/workflow-sandbox',
        keywords: ['workflow', 'sandbox', 'simulation', 'preview'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:write' },
      },
      {
        id: 'workflow-approval',
        label: 'Freigaben',
        icon: ShieldCheck,
        module: '@/pages/workflows/approval',
        keywords: ['freigabe', 'approval', 'genehmigung'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:write' },
      },
      {
        id: 'workflow-supervisor',
        label: 'Prozess-Supervisor',
        icon: Activity,
        module: '@/pages/workflows/supervisor',
        keywords: ['supervisor', 'agent', 'prozess', 'agentic', 'ki', 'oversight'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
      {
        id: 'workflow-flow-spine',
        label: 'Flow Spine Studio',
        icon: LayoutGrid,
        module: '@/pages/workflow/flow-spine-studio',
        preferredPath: 'workflow/flow-spine-studio',
        keywords: ['flow spine', 'studio', 'katalog', 'control tower', 'agentic ui', 'prozessraum'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
      {
        id: 'workflow-flow-spine-order-to-cash',
        label: 'Auftrag bis Zahlung',
        icon: ReceiptText,
        module: '@/pages/workflow/flow-spine-order-to-cash',
        preferredPath: 'workflow/flow-spine-order-to-cash',
        keywords: ['flow spine', 'order to cash', 'vertrieb', 'lieferung', 'faktura', 'zahlung'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
      {
        id: 'workflow-flow-spine-procure-to-pay',
        label: 'Bedarf bis Zahlung',
        icon: ShoppingCart,
        module: '@/pages/workflow/flow-spine-procure-to-pay',
        preferredPath: 'workflow/flow-spine-procure-to-pay',
        keywords: ['flow spine', 'procure to pay', 'p2p', 'beschaffung', 'kreditoren', 'prozessraum'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
      {
        id: 'workflow-flow-spine-inventory-to-settlement',
        label: 'Lager bis Abrechnung',
        icon: Package,
        module: '@/pages/workflow/flow-spine-inventory-to-settlement',
        preferredPath: 'workflow/flow-spine-inventory-to-settlement',
        keywords: ['flow spine', 'inventory to settlement', 'lager', 'versand', 'settlement', 'prozessraum'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
      {
        id: 'workflow-flow-spine-harvest-to-settlement',
        label: 'Ernte bis Abrechnung',
        icon: Tractor,
        module: '@/pages/workflow/flow-spine-harvest-to-settlement',
        preferredPath: 'workflow/flow-spine-harvest-to-settlement',
        keywords: ['flow spine', 'harvest to settlement', 'ernte', 'trocknung', 'silo', 'abrechnung'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
      {
        id: 'workflow-flow-spine-contract-to-settlement',
        label: 'Kontrakt bis Abrechnung',
        icon: BookOpen,
        module: '@/pages/workflow/flow-spine-contract-to-settlement',
        preferredPath: 'workflow/flow-spine-contract-to-settlement',
        keywords: ['flow spine', 'contract to settlement', 'kontrakt', 'annahme', 'qualitaet', 'settlement'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
      {
        id: 'workflow-flow-spine-complaint-to-resolution',
        label: 'Reklamation bis Lösung',
        icon: AlertCircle,
        module: '@/pages/workflow/flow-spine-complaint-to-resolution',
        preferredPath: 'workflow/flow-spine-complaint-to-resolution',
        keywords: ['flow spine', 'reklamation', 'complaint', 'crm', 'dms', 'resolution'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
      {
        id: 'workflow-flow-spine-service-to-customer',
        label: 'Service bis Kunde',
        icon: Truck,
        module: '@/pages/workflow/flow-spine-service-to-customer',
        preferredPath: 'workflow/flow-spine-service-to-customer',
        keywords: ['flow spine', 'service to customer', 'field service', 'servicefall', 'einsatz'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
      {
        id: 'workflow-flow-spine-finance-to-close',
        label: 'Finanzen bis Abschluss',
        icon: Calculator,
        module: '@/pages/workflow/flow-spine-finance-to-close',
        preferredPath: 'workflow/flow-spine-finance-to-close',
        keywords: ['flow spine', 'finance to close', 'abschluss', 'buchung', 'ustva', 'reconciliation'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
      {
        id: 'workflow-flow-spine-compliance-to-report',
        label: 'Compliance bis Bericht',
        icon: Leaf,
        module: '@/pages/workflow/flow-spine-compliance-to-report',
        preferredPath: 'workflow/flow-spine-compliance-to-report',
        keywords: ['flow spine', 'compliance to report', 'co2', 'eudr', 'esg', 'reporting'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
      {
        id: 'process-mining-analytics',
        label: 'Prozess-Analyse (Mining)',
        icon: BarChart3,
        module: '@/pages/workflow/process-mining-analytics',
        preferredPath: 'workflow/process-mining-analytics',
        keywords: ['prozess', 'mining', 'analytics', 'bottleneck', 'engpass', 'sla', 'drilldown'],
        mcp: { businessDomain: 'workflow', scope: 'workflow:read' },
      },
    ],
  },
  {
    id: 'admin',
    label: 'Administration',
    icon: Settings,
    mcp: { businessDomain: 'admin', scope: 'admin:read' },
    children: [
      {
        id: 'benutzer',
        label: 'Benutzer',
        icon: Users,
        module: '@/pages/admin/benutzer-liste',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'rollen-verwaltung',
        label: 'Rollen',
        icon: UserCog,
        module: '@/pages/admin/rollen-verwaltung',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'audit-log',
        label: 'Audit-Log',
        icon: FileText,
        module: '@/pages/admin/audit-log',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'report-berechtigungen',
        label: 'Report-Berechtigungen',
        icon: ShieldCheck,
        module: '@/pages/admin/report-berechtigungen',
        preferredPath: 'admin/report-berechtigungen',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'monitoring',
        label: 'Monitoring',
        icon: AlertCircle,
        module: '@/pages/admin/monitoring/alerts',
        preferredPath: 'monitoring/alerts',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'monitoring-regeln',
        label: 'Monitoring-Regeln',
        icon: Settings,
        module: '@/pages/admin/monitoring/regeln',
        preferredPath: 'monitoring/regeln',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'integrationen-quarantaene',
        label: 'Integrationen-Quarantaene',
        icon: AlertCircle,
        module: '@/pages/admin/integrationen-quarantaene',
        preferredPath: 'admin/integrationen-quarantaene',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'compliance-dashboard',
        label: 'Compliance',
        icon: ShieldCheck,
        module: '@/pages/admin/compliance-dashboard',
        preferredPath: 'admin/compliance',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'data-quality',
        label: 'Datenqualität',
        icon: BarChart3,
        module: '@/pages/admin/data-quality',
        preferredPath: 'admin/data-quality',
        keywords: ['datenqualität', 'dublette', 'pflichtfeld', 'referenz', 'mdm'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'command-monitor',
        label: 'Befehlsmonitor',
        icon: Activity,
        module: '@/pages/admin/command-monitor',
        preferredPath: 'admin/command-monitor',
        keywords: ['command', 'idempotenz', 'replay', 'monitor', 'commands', 'robustheit'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'admin-control-center',
        label: 'Kontrollzentrum',
        icon: Zap,
        module: '@/pages/admin/control-center/index',
        preferredPath: 'admin/control-center',
        keywords: ['leitstand', 'kontrollzentrum', 'agenten', 'superglue', 'ops', 'monitoring'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'agent-ops-control-center',
        label: 'Agent Ops',
        icon: Zap,
        module: '@/pages/admin/control-center/agent-ops',
        preferredPath: 'admin/control-center/agent-ops',
        keywords: ['agent ops', 'tickets', 'chain of command', 'kontrolle', 'review'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'superglue-control-center',
        label: 'Superglue Ops',
        icon: Zap,
        module: '@/pages/admin/control-center/superglue',
        preferredPath: 'admin/control-center/superglue',
        keywords: ['superglue', 'connectoren', 'onboarding', 'quarantaene', 'monitoring'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'agenten-integration',
        label: 'Agenten-Integration',
        icon: Zap,
        module: '@/pages/admin/agenten-integration',
        preferredPath: 'admin/agenten-integration',
        keywords: ['legacy', 'agenten', 'mcp', 'openapi', 'perplexity', 'api'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      {
        id: 'ai-approvals',
        label: 'AI-Freigaben',
        icon: ShieldCheck,
        module: '@/pages/admin/ai-approvals',
        preferredPath: 'admin/ai-approvals',
        keywords: ['ai', 'freigabe', 'agent', 'human-in-the-loop'],
        mcp: { businessDomain: 'admin', scope: 'admin:write' },
      },
      {
        id: 'voice-channel',
        label: 'Voice-Kanal',
        icon: Mic,
        module: '@/pages/admin/voice-channel',
        preferredPath: 'admin/voice-channel',
        keywords: ['voice', 'sprache', 'sprachbefehl', 'ki', 'usability', 'mikrofon'],
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
      ...(ENABLE_PROSPECTING_UI
        ? [
            {
              id: 'gap-pipeline',
              label: 'GAP-Pipeline',
              icon: BarChart3,
              module: '@/pages/admin/GapPipelineConsole',
              preferredPath: 'admin/gap-pipeline',
              keywords: ['gap', 'pipeline', 'prospecting', 'import'],
              mcp: { businessDomain: 'admin', scope: 'admin:write' },
            },
          ]
        : []),
      {
        id: 'system-einstellungen',
        label: 'System',
        icon: Settings,
        module: '@/pages/einstellungen/system',
        preferredPath: 'einstellungen/system',
        mcp: { businessDomain: 'admin', scope: 'admin:read' },
      },
    ],
  },
  {
    id: 'wissen',
    label: 'Wissensbasis',
    icon: BookOpen,
    module: '@/pages/wissen/wissensbasis',
    preferredPath: 'wissen/wissensbasis',
    keywords: ['wissen', 'knowledge', 'dokumente', 'handbuch', 'richtlinien', 'ki', 'agent'],
    mcp: { businessDomain: 'wissen', scope: 'knowledge:read' },
  },
  {
    id: 'kundenportal',
    label: 'Kundenportal',
    icon: Globe,
    path: '/portal',
    keywords: ['portal', 'kunde', 'landwirt', 'shop', 'bestellung', 'futterbestellung', 'verträge'],
    mcp: { businessDomain: 'sales', scope: 'sales:read' },
  },
]
