import {
  Activity,
  ArrowUpDown,
  AlertCircle,
  BarChart3,
  Building2,
  Calendar,
  Calculator,
  Database,
  Euro,
  FileDown,
  FileText,
  FlaskConical,
  Globe,
  Hash,
  LayoutDashboard,
  Link2,
  LayoutGrid,
  Leaf,
  Package,
  Receipt,
  RefreshCw,
  Scale,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sprout,
  Target,
  Tractor,
  Truck,
  Upload,
  UserCog,
  Users,
  Zap,
  Search,
  Banknote,
  CalendarCheck,
  CalendarClock,
  PackageOpen,
} from 'lucide-react'
import type { RawNavItem } from '@/app/navigation/types'

export const RAW_NAV_SECTIONS: RawNavItem[] = [
  {
    id: 'fibu',
    label: 'Finanzbuchhaltung',
    icon: Euro,
    mcp: { businessDomain: 'finance', scope: 'finance:read' },
    children: [
      {
        id: 'hauptbuch',
        label: 'Hauptbuch',
        icon: FileText,
        module: '@/pages/fibu/hauptbuch',
        keywords: ['hauptbuch'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'debitoren',
        label: 'Debitoren',
        icon: Users,
        module: '@/pages/fibu/debitoren',
        keywords: ['debitoren'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'kreditoren',
        label: 'Kreditoren',
        icon: Users,
        module: '@/pages/fibu/kreditoren',
        keywords: ['kreditoren'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'buchungsjournal',
        label: 'Buchungsjournal',
        icon: FileText,
        module: '@/pages/fibu/buchungsjournal',
        keywords: ['buchungsjournal'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'kontenplan',
        label: 'Kontenplan',
        icon: FileText,
        module: '@/pages/fibu/kontenplan',
        keywords: ['kontenplan'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'erloeskennziffern',
        label: 'Erlöskennziffern',
        icon: Hash,
        module: '@/pages/fibu/erloeskennziffern',
        preferredPath: 'fibu/erloeskennziffern',
        keywords: ['erloeskennziffer', 'ekz', 'stammdaten'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'erloeskontenzuordnung',
        label: 'Erlöskontenzuordnung',
        icon: Link2,
        module: '@/pages/fibu/erloeskontenzuordnung',
        preferredPath: 'fibu/erloeskontenzuordnung',
        keywords: ['ekzz', 'erloeskontenzuordnung', 'lookup', 'kontenzuordnung'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'forderungsgruppen',
        label: 'Forderungsgruppen',
        icon: Users,
        module: '@/pages/fibu/forderungsgruppen',
        preferredPath: 'fibu/forderungsgruppen',
        keywords: ['forg', 'forderungsgruppe', 'bestandskonto'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'periodische-buchungen',
        label: 'Periodische Buchungen',
        icon: Calendar,
        module: '@/pages/fibu/periodische-buchungen',
        preferredPath: 'fibu/periodische-buchungen',
        keywords: ['wza', 'periodische buchung', 'wiederkehrend'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'geschaeftsjahre',
        label: 'Geschäftsjahre [JAHR]',
        icon: Calendar,
        module: '@/pages/fibu/geschaeftsjahre',
        preferredPath: 'fibu/geschaeftsjahre',
        keywords: ['geschäftsjahr', 'fibu-periode', 'perioden', 'wirtschaftsjahr', 'jahr'],
        mcp: { businessDomain: 'fibu', scope: 'fibu:read' },
      },
      {
        id: 'zahlungsmeldungen',
        label: 'Zahlungsmeldungen [KASSZAME]',
        icon: Receipt,
        module: '@/pages/fibu/zahlungsmeldungen',
        preferredPath: 'fibu/zahlungsmeldungen',
        keywords: ['zahlungsmeldung', 'kasszame', 'zahlungseingang', 'auszifferung'],
        mcp: { businessDomain: 'fibu', scope: 'fibu:read' },
      },
      {
        id: 'fibu-stammdaten',
        label: 'Zusatzstammdaten',
        icon: Settings,
        module: '@/pages/fibu/stammdaten',
        preferredPath: 'fibu/stammdaten',
        keywords: ['zahlungsformular', 'fizaf', 'zinsgruppe', 'leergutart', 'pfand', 'palette'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'hausbankenstamm',
        label: 'Hausbankenstamm [BNKH]',
        icon: Building2,
        module: '@/pages/stammdaten/hausbanken',
        preferredPath: 'stammdaten/hausbanken',
        keywords: ['hausbank', 'bnkh', 'iban', 'bic', 'sepa', 'erechnung', 'bankverbindung'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'bilanz',
        label: 'Bilanz',
        icon: BarChart3,
        module: '@/pages/fibu/bilanz',
        keywords: ['bilanz'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'guv',
        label: 'GuV',
        icon: BarChart3,
        module: '@/pages/fibu/guv',
        keywords: ['guv'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'bwa',
        label: 'BWA',
        icon: BarChart3,
        module: '@/pages/fibu/bwa',
        keywords: ['bwa'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'anlagen',
        label: 'Anlagenbuchhaltung',
        icon: Building2,
        module: '@/pages/fibu/anlagen',
        keywords: ['anlagen'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'op-verwaltung',
        label: 'OP-Verwaltung',
        icon: Euro,
        module: '@/pages/fibu/op-verwaltung',
        keywords: ['op', 'verwaltung'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'op-skonto-auszifferung',
        label: 'OP Skonto-Auszifferung',
        icon: Euro,
        module: '@/pages/fibu/op-skonto-auszifferung',
        preferredPath: 'fibu/op-skonto-auszifferung',
        keywords: ['op', 'skonto', 'auszifferung', 'zahlungseingang', 'ausgleich'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'offene-posten',
        label: 'Offene Posten',
        icon: Euro,
        module: '@/pages/fibu/offene-posten',
        keywords: ['offene posten', 'op', 'forderungen'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'op-cockpit-aging',
        label: 'OP-Cockpit (Aging)',
        icon: Euro,
        module: '@/pages/finance/offene-posten-cockpit',
        preferredPath: 'finance/offene-posten-cockpit',
        keywords: ['op', 'offene posten', 'aging', 'fälligkeit', 'überfällig', 'mahnstufe', 'mahnwesen', 'skonto', 'debitoren', 'kreditoren'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'mahnlauf',
        label: 'Mahnlauf',
        icon: Euro,
        module: '@/pages/finance/mahnlauf',
        preferredPath: 'finance/mahnlauf',
        keywords: ['mahnlauf', 'mahnung', 'mahnwesen', 'mahnstufe', 'eskalation', 'überfällig', 'debitoren', 'mahngebühr', 'verzugszinsen'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'zahlungseingang',
        label: 'Zahlungseingang / Auszifferung',
        icon: Banknote,
        module: '@/pages/finance/zahlungseingang',
        preferredPath: 'finance/zahlungseingang',
        keywords: ['zahlungseingang', 'auszifferung', 'ausziffern', 'zahlung', 'skonto', 'op', 'offene posten', 'teilzahlung', 'debitoren'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'periodenabschluss',
        label: 'Periodenabschluss',
        icon: CalendarCheck,
        module: '@/pages/finance/periodenabschluss',
        preferredPath: 'finance/periodenabschluss',
        keywords: ['periode', 'periodenabschluss', 'abschluss', 'monatsabschluss', 'sperre', 'buchungsperiode', 'storno-konsistenz', 'fibu'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'datev-export',
        label: 'DATEV-Export',
        icon: FileDown,
        module: '@/pages/finance/datev-export',
        preferredPath: 'finance/datev-export',
        keywords: ['datev', 'export', 'buchungsstapel', 'csv', 'steuerberater', 'fibu', 'offene posten', 'extf'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'abschluss-cockpit',
        label: 'Abschluss-Cockpit',
        icon: ShieldCheck,
        module: '@/pages/fibu/abschluss-cockpit',
        preferredPath: 'fibu/abschluss-cockpit',
        keywords: ['abschluss', 'cockpit', 'periodenabschluss'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'zahlungslaeufe',
        label: 'Zahlungsläufe',
        icon: Euro,
        module: '@/pages/fibu/zahlungslaeufe',
        keywords: ['zahlungsläufe', 'zahlung'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'zahlungseingaenge',
        label: 'Zahlungseingänge & Matching',
        icon: Euro,
        module: '@/pages/finance/payment-matching',
        preferredPath: 'finance/payments',
        keywords: ['zahlungseingang', 'bankimport', 'matching', 'op-zuordnung'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'bank-stamm',
        label: 'Bankkonten (Bankstamm)',
        icon: Building2,
        module: '@/pages/finance/bank-stamm',
        preferredPath: 'finance/bank-stamm',
        keywords: ['bank', 'bankkonto', 'bankstamm', 'iban', 'gegenkonto'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'op-debitoren-finance',
        label: 'OP Debitoren',
        icon: Euro,
        module: '@/pages/finance/op-debitoren',
        preferredPath: 'finance/op-debitoren',
        keywords: ['op', 'debitoren', 'ausgleich', 'forderungen'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'op-kreditoren-finance',
        label: 'OP Kreditoren',
        icon: Euro,
        module: '@/pages/finance/op-kreditoren',
        preferredPath: 'finance/op-kreditoren',
        keywords: ['op', 'kreditoren', 'ausgleich', 'verbindlichkeiten'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'skonto-optimizer',
        label: 'Skonto-Optimierung (KI)',
        icon: Zap,
        module: '@/pages/finance/skonto-optimizer',
        preferredPath: 'finance/skonto-optimizer',
        keywords: ['skonto', 'optimizer', 'ki', 'agent', 'zahlung', 'fälligkeit', 'liquidität'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'nebenbuch-abstimmung',
        label: 'Nebenbuch-Abstimmung',
        icon: BarChart3,
        module: '@/pages/finance/nebenbuch-abstimmung',
        preferredPath: 'finance/nebenbuch-abstimmung',
        keywords: ['nebenbuch', 'abstimmung', 'debitoren', 'kreditoren', 'abschluss'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'kostenstellenrechnung',
        label: 'Kostenstellen',
        icon: Calculator,
        module: '@/pages/fibu/kostenstellenrechnung',
        keywords: ['kostenstellen', 'controlling'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'ustva',
        label: 'USt.-Voranmeldung',
        icon: FileText,
        module: '@/pages/export/umsatzsteuervoranmeldung',
        preferredPath: 'export/ustva',
        keywords: ['ustva'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'audit-trail-finance',
        label: 'Audit-Trail (GoBD)',
        icon: ShieldCheck,
        module: '@/pages/finance/audit-trail',
        keywords: ['audit', 'gobd', 'trail', 'hash'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'docflow-nachweisraum',
        label: 'Nachweisraum (DMS/GoBD)',
        icon: ShieldCheck,
        module: '@/pages/docflow/nachweisraum',
        preferredPath: 'docflow/nachweisraum',
        keywords: ['nachweis', 'nachweisraum', 'dms', 'gobd', 'dokument', 'artefakt', 'hash', 'revisionssicher', 'vorgangskette', 'beleg', 'archiv'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'docflow-artefakt-freigabe',
        label: 'Artefakt-Upload & Freigabe',
        icon: ShieldCheck,
        module: '@/pages/docflow/artefakt-freigabe',
        preferredPath: 'docflow/artefakt-freigabe',
        keywords: ['artefakt', 'upload', 'freigabe', 'versionierung', 'dms', 'gobd', 'sha-256', 'revisionssicher', 'archivieren', 'dokument'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'docflow-wiedervorlagen',
        label: 'Wiedervorlagen & Bescheide',
        icon: CalendarClock,
        module: '@/pages/docflow/wiedervorlagen',
        preferredPath: 'docflow/wiedervorlagen',
        keywords: ['wiedervorlage', 'bescheid', 'rückmeldung', 'frist', 'vorgang', 'dms', 'gobd', 'worklist', 'überfällig', 'dokument'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'docflow-gobd-export',
        label: 'GoBD-Export',
        icon: PackageOpen,
        module: '@/pages/docflow/gobd-export',
        preferredPath: 'docflow/gobd-export',
        keywords: ['gobd', 'export', 'exportpaket', 'manifest', 'prüfsumme', 'revisionssicher', 'paperless', 'dms', 'archiv', 'dokument'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'periodensteuerung',
        label: 'Periodensteuerung',
        icon: Calendar,
        module: '@/pages/finance/periods',
        preferredPath: 'finance/periods',
        keywords: ['perioden', 'sperre', 'abschluss', 'buchungsperiode'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'wechselkurse',
        label: 'Wechselkurse',
        icon: RefreshCw,
        module: '@/pages/finance/wechselkurse',
        keywords: ['wechselkurs', 'devisen', 'fremdwährung', 'ezb', 'kurs'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'buchungsvorlagen',
        label: 'Buchungsvorlagen',
        icon: FileText,
        module: '@/pages/finance/buchungsvorlagen',
        keywords: ['buchungsvorlage', 'vorlage', 'schema', 'automatisch', 'wiederkehrend'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'buchungsimport',
        label: 'Massen-Import',
        icon: Upload,
        module: '@/pages/finance/buchungsimport',
        keywords: ['buchungsimport', 'import', 'csv', 'massenbuchung', 'datev'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'uebernahme-tagesabschluss-pos',
        label: 'Übernahme Buchungen Tagesabschluss POS',
        icon: ShoppingCart,
        module: '@/pages/pos/tagesabschluss-enhanced',
        preferredPath: 'pos/tagesabschluss',
        keywords: ['übernahme', 'tagesabschluss', 'pos', 'kasse', 'fibu', 'buchung'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'buchungsuebernahme-connectors',
        label: 'Buchungsübernahme Connectors',
        icon: Zap,
        module: '@/pages/fibu/buchungsuebernahme-connectors',
        preferredPath: 'fibu/buchungsuebernahme-connectors',
        keywords: ['buchungsübernahme', 'connectors', 'lohn', 'anlagen', 'fibu'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'buchhaltungsuebersicht',
        label: 'Buchhaltungsübersicht',
        icon: BarChart3,
        module: '@/pages/fibu/buchhaltungsuebersicht',
        keywords: ['buchhaltungsübersicht', 'bilanz', 'guv', 'auswertung', 'fibu'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'monatswerte',
        label: 'Monatswerte für mehrere Monate',
        icon: BarChart3,
        module: '@/pages/fibu/monatswerte',
        keywords: ['monatswerte', 'bwa', 'mehrere monate', 'fibu', 'auswertung'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'uebernahme-kasse',
        label: 'Übernahme Kasse',
        icon: Database,
        module: '@/pages/pos/uebernahme-kasse',
        keywords: ['übernahme', 'kasse', 'sqlite', 'bewegungsdaten', 'serviceerp'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'ubergabe-fibu',
        label: 'Übergabe an FIBU',
        icon: FileDown,
        module: '@/pages/fibu/schnittstelle-fibu',
        keywords: ['übergabe', 'fibu', 'schnittstelle', 'buchungsübergabe', 'asc'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'schnittstelle-fibu',
        label: 'Schnittstelle FIBU',
        icon: FileDown,
        module: '@/pages/fibu/schnittstelle-fibu',
        keywords: ['schnittstelle', 'fibu', 'buchungsübergabe', 'export', 'asc'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'schnittstellen-center',
        label: 'Schnittstellen-Center',
        icon: LayoutDashboard,
        module: '@/pages/fibu/schnittstellen-center',
        keywords: ['schnittstellen', 'center', 'connectoren', 'datev', 'sepa', 'export', 'import'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'lohn-connector',
        label: 'Lohn-Connector',
        icon: Building2,
        module: '@/pages/fibu/lohn-connector',
        keywords: ['lohn', 'lexware', 'connector', 'lohnbuchungen'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'anlagen-suite',
        label: 'VALEO Suite Anlagen (Asset Ledger)',
        icon: LayoutGrid,
        module: '@/pages/fibu/anlagen-suite',
        keywords: ['anlagen', 'asset ledger', 'anlagenbuchhaltung', 'afa', 'abscheidung'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'atlas',
        label: 'ATLAS (Zoll)',
        icon: FileDown,
        module: '@/pages/fibu/atlas',
        keywords: ['atlas', 'zoll', 'zollanmeldung', 'ausfuhr', 'eu-übermittlung'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'elster-online',
        label: 'ELSTER (Online)',
        icon: FileText,
        module: '@/pages/fibu/elster-online',
        keywords: ['elster', 'ustva', 'lohnsteuer', 'einkommensteuer', 'finanzamt'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'fibu-zahlungsvorschlaege',
        label: 'Zahlungsvorschläge',
        icon: FileText,
        module: '@/pages/fibu/zahlungsvorschlaege',
        preferredPath: 'fibu/zahlungsvorschlaege',
        keywords: ['zahlungsvorschlag', 'kreditor', 'zahlung', 'fälligkeit'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'fibu-zahlungseingaenge',
        label: 'Zahlungseingänge (Detail)',
        icon: FileText,
        module: '@/pages/fibu/zahlungseingaenge',
        preferredPath: 'fibu/zahlungseingaenge',
        keywords: ['zahlungseingang', 'debitor', 'bank', 'matching'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'fibu-verbindlichkeiten',
        label: 'Verbindlichkeiten',
        icon: FileText,
        module: '@/pages/fibu/verbindlichkeiten',
        preferredPath: 'fibu/verbindlichkeiten',
        keywords: ['verbindlichkeiten', 'kreditor', 'offene posten'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'fibu-kreditlinien',
        label: 'Kreditlinien',
        icon: FileText,
        module: '@/pages/fibu/kreditlinien',
        preferredPath: 'fibu/kreditlinien',
        keywords: ['kreditlinie', 'limit', 'kredit', 'debitor'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'fibu-sicherheiten',
        label: 'Sicherheiten',
        icon: FileText,
        module: '@/pages/fibu/sicherheiten',
        preferredPath: 'fibu/sicherheiten',
        keywords: ['sicherheit', 'bürgschaft', 'pfand', 'kredit'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'quadriga-connector',
        label: 'Quadriga-Connector',
        icon: FileText,
        module: '@/pages/fibu/quadriga-connector',
        preferredPath: 'fibu/quadriga-connector',
        keywords: ['quadriga', 'connector', 'schnittstelle', 'fibu'],
        mcp: { businessDomain: 'finance', scope: 'finance:admin' },
      },
    ],
  },
  {
    id: 'controlling',
    label: 'Controlling',
    icon: BarChart3,
    mcp: { businessDomain: 'finance', scope: 'finance:read' },
    children: [
      {
        id: 'plan-ist',
        label: 'Plan/Ist-Vergleich',
        icon: BarChart3,
        module: '@/pages/controlling/plan-ist',
        keywords: ['plan', 'ist', 'controlling'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'benchmark-cockpit',
        label: 'Branchenbenchmark',
        icon: BarChart3,
        module: '@/pages/controlling/benchmark-cockpit',
        preferredPath: 'controlling/benchmark-cockpit',
        keywords: ['benchmark', 'branche', 'genossenschaft', 'vergleich'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'kpi-verwaltung',
        label: 'KPI-Verwaltung',
        icon: Settings,
        module: '@/pages/controlling/kpi-verwaltung',
        keywords: ['kpi', 'controlling', 'dashboard'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'dashboard-verwaltung',
        label: 'Dashboard-Verwaltung',
        icon: LayoutDashboard,
        module: '@/pages/controlling/dashboard-verwaltung',
        keywords: ['dashboard', 'controlling', 'widgets'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'widget-verwaltung',
        label: 'Widget-Verwaltung',
        icon: Settings,
        module: '@/pages/controlling/widget-verwaltung',
        keywords: ['widget', 'dashboard', 'controlling'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'timeseries-erfassung',
        label: 'Timeseries-Erfassung',
        icon: BarChart3,
        module: '@/pages/controlling/timeseries-erfassung',
        keywords: ['timeseries', 'kpi', 'controlling'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'massnahmen',
        label: 'Massnahmen',
        icon: FileText,
        module: '@/pages/controlling/massnahmen',
        keywords: ['massnahmen', 'actions', 'controlling'],
        mcp: { businessDomain: 'finance', scope: 'finance:write' },
      },
      {
        id: 'deckungsbeitrag',
        label: 'Deckungsbeitrag',
        icon: Calculator,
        module: '@/pages/reports/deckungsbeitrag',
        keywords: ['deckungsbeitrag', 'db'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'liquiditaet',
        label: 'Liquiditätsplanung',
        icon: Euro,
        module: '@/pages/finanzplanung/liquiditaet',
        keywords: ['liquidität', 'cashflow'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
      {
        id: 'executive-dashboard',
        label: 'Geschäftsführung',
        icon: LayoutDashboard,
        module: '@/pages/management/executive-dashboard',
        keywords: ['executive', 'geschäftsführung', 'management'],
        mcp: { businessDomain: 'finance', scope: 'finance:read' },
      },
    ],
  },
]
