import {
  Activity,
  ArrowUpDown,
  AlertCircle,
  BarChart3,
  Building2,
  Calendar,
  Calculator,
  Database,
  Euro,
  FileDown,
  FileText,
  FlaskConical,
  Globe,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Package,
  QrCode,
  RefreshCw,
  Scale,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Sprout,
  Tag,
  Target,
  Tractor,
  Truck,
  Upload,
  UserCog,
  Smartphone,
  Users,
  Waypoints,
  Wheat,
  Zap,
  Search,
  Microscope,
  GitBranch,
  Monitor,
} from 'lucide-react'
import type { RawNavItem } from '@/app/navigation/types'

export const RAW_NAV_SECTIONS: RawNavItem[] = [
  {
    id: 'lager',
    label: 'Lager & Bestände',
    icon: Package,
    mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
    children: [
      {
        id: 'bestandsuebersicht',
        label: 'Bestandsübersicht',
        icon: Package,
        module: '@/pages/lager/bestandsuebersicht',
        keywords: ['bestandsübersicht'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'einlagerung',
        label: 'Einlagerung',
        icon: Truck,
        module: '@/pages/lager/einlagerung',
        keywords: ['einlagerung'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'auslagerung',
        label: 'Auslagerung',
        icon: Truck,
        module: '@/pages/lager/auslagerung',
        keywords: ['auslagerung'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'inventur',
        label: 'Inventur',
        icon: Scale,
        module: '@/pages/lager/inventur',
        keywords: ['inventur'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'permanente-inventur',
        label: 'Permanente Inventur (PIV)',
        icon: Scale,
        module: '@/pages/lager/permanente-inventur',
        preferredPath: 'lager/permanente-inventur',
        keywords: ['permanente', 'inventur', 'piv', 'zählung', 'differenz', 'bestand'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:write' },
      },
      {
        id: 'bestandskorrektur',
        label: 'Bestandskorrektur',
        icon: RefreshCw,
        module: '@/pages/lager/bestandskorrektur',
        keywords: ['bestandskorrektur', 'schwund', 'bruch', 'mhd', 'korrektur'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:write' },
      },
      {
        id: 'lagerbewegungen',
        label: 'Lagerbewegungen',
        icon: ArrowUpDown,
        module: '@/pages/lager/lagerbewegungen',
        keywords: ['lagerbewegungen', 'buchungen', 'stock movements'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'partiestamm',
        label: 'Partiestamm',
        icon: Tag,
        module: '@/pages/lager/partiestamm',
        preferredPath: 'lager/partiestamm',
        keywords: ['partie', 'partiestamm', 'charge', 'lot', 'pgr'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'rueckverfolgbarkeit',
        label: 'Rückverfolgbarkeit',
        icon: GitBranch,
        module: '@/pages/lager/rueckverfolgbarkeit',
        preferredPath: 'lager/rueckverfolgbarkeit',
        keywords: ['rückverfolgbarkeit', 'rueckverfolgbarkeit', 'traceability', 'genealogie', 'kette', 'wiegung', 'annahme', 'lager', 'abrechnung', 'wiegeschein', 'schwund', 'partie', 'charge'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'gs1-scanner',
        label: 'GS1 Barcode Workbench',
        icon: QrCode,
        module: '@/pages/lager/gs1-scanner',
        keywords: ['gs1', 'barcode', 'sscc', 'ean', 'scanner', 'label', 'etikett'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'lagerplaetze',
        label: 'Lagerplätze',
        icon: Database,
        module: '@/pages/lager/lagerplaetze',
        preferredPath: 'lager/lagerplaetze',
        keywords: ['lagerplatz', 'lagerort', 'regal', 'fach'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'materialfluss-agrar',
        label: 'Materialfluss (Agrar)',
        icon: Waypoints,
        module: '@/pages/lager/materialfluss',
        preferredPath: 'lager/materialfluss',
        keywords: ['materialfluss', 'silo', 'silozelle', 'förderung', 'mmx', 'wm-agri'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'materialfluss-visualisierung',
        label: 'Materialfluss — Visualisierung',
        icon: LayoutGrid,
        module: '@/pages/lager/materialfluss-visualisierung',
        preferredPath: 'lager/materialfluss-visualisierung',
        keywords: ['materialfluss', 'visualisierung', 'hofplan', 'layout', 'silos', 'react-flow', 'folkerts'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'silo-uebersicht',
        label: 'Silo-Übersicht (Bird-View)',
        icon: LayoutGrid,
        module: '@/pages/lager/silo-uebersicht',
        preferredPath: 'lager/silo-uebersicht',
        keywords: ['silo', 'übersicht', 'bird-view', 'kapazität', 'qs-status', 'bestand', 'map', 'karte'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'silo-mobil',
        label: 'Silo-Terminal (Mobil)',
        icon: Smartphone,
        module: '@/pages/lager/silo-mobil',
        preferredPath: 'lager/silo-mobil',
        keywords: ['silo', 'mobil', 'terminal', 'waage', 'hallenterminal', 'lot-link', 'transfer', 'spülcharge'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:write' },
      },
      {
        id: 'qs-leitstand',
        label: 'QS-Leitstand (Silo)',
        icon: ShieldCheck,
        module: '@/pages/lager/qs-leitstand',
        preferredPath: 'lager/qs-leitstand',
        keywords: ['qs', 'freigabe', 'sperre', 'leitstand', 'labor', 'silo-lot', 'gmp', 'vlog'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:write' },
      },
      {
        id: 'kommissionierung',
        label: 'Kommissionierung',
        icon: ShoppingCart,
        module: '@/pages/lager/kommissionierung',
        preferredPath: 'lager/kommissionierung',
        keywords: ['kommissionierung', 'pick', 'fefo', 'warenausgang', 'lieferschein', 'pick-liste'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:write' },
      },
      {
        id: 'bestandsbewertung',
        label: 'Bestandsbewertung',
        icon: BarChart3,
        module: '@/pages/lager/bestandsbewertung',
        preferredPath: 'lager/bestandsbewertung',
        keywords: ['bestandsbewertung', 'einstandspreis', 'fifo', 'durchschnittspreis', 'lagerwert', 'bewertung'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'lager-terminal',
        label: 'Lager-Terminal',
        icon: Zap,
        module: '@/pages/lager/terminal',
        preferredPath: 'lager/terminal',
        keywords: ['terminal', 'mobil', 'scanner', 'lager'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:write' },
      },
      {
        id: 'massebilanz',
        label: 'Massebilanz',
        icon: Scale,
        module: '@/pages/lager/massebilanz',
        preferredPath: 'lager/massebilanz',
        keywords: ['massebilanz', 'masseabgleich', 'gewicht', 'lagerbestand'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
    ],
  },
  {
    id: 'agrar',
    label: 'Agrar & Warenwirtschaft',
    icon: Sprout,
    featureKey: 'agrar',
    mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
    children: [
      {
        id: 'milchvieh-crosssell',
        label: 'Milchvieh Cross-Sell',
        icon: Wheat,
        module: '@/pages/agrar/milchvieh-crosssell',
        preferredPath: 'agrar/milchvieh-crosssell',
        keywords: ['milchvieh', 'cross-sell', 'hygiene', 'kraftfutter', 'zellzahl', 'potenzial'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'milchvieh-karte',
        label: 'Milchvieh-Karte',
        icon: Sprout,
        module: '@/pages/agrar/milchvieh-karte',
        preferredPath: 'agrar/milchvieh-karte',
        keywords: ['milchvieh', 'karte', 'map', 'betriebe', 'crm', 'poi'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'psm',
        label: 'Pflanzenschutz',
        icon: Leaf,
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
        children: [
          {
            id: 'psm-liste',
            label: 'PSM-Stammdaten',
            icon: Leaf,
            module: '@/pages/agrar/psm/stamm',
            preferredPath: 'agrar/psm/stamm',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'psm-applikation',
            label: 'Applikation',
            icon: Leaf,
            module: '@/pages/agrar/pflanzenschutz/applikation',
            preferredPath: 'agrar/pflanzenschutz/applikation',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'psm-abgabedokumentation',
            label: 'Abgabedokumentation',
            icon: FileText,
            module: '@/pages/agrar/psm/abgabedokumentation',
            preferredPath: 'agrar/psm/abgabedokumentation',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'psm-wasserschutz',
            label: 'Wasserschutz',
            icon: Shield,
            module: '@/pages/agrar/psm/wasserschutz',
            preferredPath: 'agrar/psm/wasserschutz',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'psm-auflagen-manager',
            label: 'Auflagen-Manager',
            icon: ShieldCheck,
            module: '@/pages/agrar/psm/auflagen-manager',
            preferredPath: 'agrar/psm/auflagen-manager',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'psm-beratung',
            label: 'Beratung',
            icon: Leaf,
            module: '@/pages/agrar/psm/beratung',
            preferredPath: 'agrar/psm/beratung',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'psm-resistenz',
            label: 'Resistenzmanagement',
            icon: Leaf,
            module: '@/pages/agrar/psm/resistenz',
            preferredPath: 'agrar/psm/resistenz',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'psm-sachkunde-register',
            label: 'Sachkunde-Register',
            icon: FileText,
            module: '@/pages/agrar/psm/sachkunde-register',
            preferredPath: 'agrar/psm/sachkunde-register',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
        ],
      },
      {
        id: 'duenger',
        label: 'Düngung',
        icon: Sprout,
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
        children: [
          {
            id: 'duenger-liste',
            label: 'Dünger-Übersicht',
            icon: Sprout,
            module: '@/pages/agrar/duenger/liste',
            preferredPath: 'agrar/duenger/liste',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'duengung-planung',
            label: 'Düngungsplanung',
            icon: Calendar,
            module: '@/pages/agrar/duengung/planung',
            preferredPath: 'agrar/duengung/planung',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'duenger-bedarfsrechner',
            label: 'Bedarfsrechner',
            icon: Calculator,
            module: '@/pages/agrar/duenger/bedarfsrechner',
            preferredPath: 'agrar/duenger/bedarfsrechner',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'duenger-mischungen',
            label: 'Mischungen',
            icon: Sprout,
            module: '@/pages/agrar/duenger/mischungen',
            preferredPath: 'agrar/duenger/mischungen',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
        ],
      },
      {
        id: 'saatgut',
        label: 'Saatgut',
        icon: Leaf,
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
        children: [
          {
            id: 'saatgut-liste',
            label: 'Saatgut-Übersicht',
            icon: Leaf,
            module: '@/pages/agrar/saatgut/liste',
            preferredPath: 'agrar/saatgut/liste',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'saatgut-bestellung',
            label: 'Bestellung',
            icon: ShoppingCart,
            module: '@/pages/agrar/saatgut/bestellung',
            preferredPath: 'agrar/saatgut/bestellung',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'saatgut-sortenregister',
            label: 'Sortenregister',
            icon: FileText,
            module: '@/pages/agrar/saatgut/sortenregister',
            preferredPath: 'agrar/saatgut/sortenregister',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
        ],
      },
      {
        id: 'aussaat',
        label: 'Aussaat',
        icon: Sprout,
        module: '@/pages/agrar/aussaat/liste',
        preferredPath: 'agrar/aussaat/liste',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'kulturpflanzen',
        label: 'Kulturpflanzen',
        icon: Leaf,
        module: '@/pages/agrar/kulturpflanzen/liste',
        preferredPath: 'agrar/kulturpflanzen/liste',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'maschinenauslastung',
        label: 'Maschinenauslastung',
        icon: Tractor,
        module: '@/pages/agrar/maschinenauslastung',
        preferredPath: 'agrar/maschinenauslastung',
        keywords: ['maschinen', 'auslastung', 'fuhrpark', 'wartung'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'wetter',
        label: 'Wetter & Prognose',
        icon: Globe,
        module: '@/pages/agrar/wetter/prognose',
        preferredPath: 'agrar/wetter/prognose',
        keywords: ['wetter', 'prognose', 'dwd', 'regenradar'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'bodenproben',
        label: 'Bodenproben',
        icon: Scale,
        module: '@/pages/agrar/bodenproben/liste',
        preferredPath: 'agrar/bodenproben',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'ernte',
        label: 'Ernteplanung',
        icon: Tractor,
        module: '@/pages/agrar/ernte/liste',
        preferredPath: 'agrar/ernte',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'ernte-annahme',
        label: 'Ernte-Annahme',
        icon: Tractor,
        module: '@/pages/agrar/ernte-annahme-erfassung',
        preferredPath: 'agrar/ernte-annahme-erfassung',
        keywords: ['ernte', 'annahme', 'erfassung'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
      },
      {
        id: 'erntefenster-konfig',
        label: 'Erntefenster-Konfiguration',
        icon: Calendar,
        module: '@/pages/agrar/erntefenster-konfig',
        preferredPath: 'agrar/erntefenster-konfig',
        keywords: ['erntefenster', 'kampagne', 'saisonal', 'vorlage'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
      },
      {
        id: 'nawaro',
        label: 'NaWaRo',
        icon: Leaf,
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
        children: [
          {
            id: 'nawaro-mitteilung-drucken',
            label: 'Mitteilung drucken',
            icon: FileText,
            module: '@/pages/nawaro/mitteilung-drucken',
            preferredPath: 'nawaro/mitteilung-drucken',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'nawaro-vertraege',
            label: 'Vertraege',
            icon: FileText,
            module: '@/pages/nawaro/vertraege',
            preferredPath: 'nawaro/vertraege',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'nawaro-anbauflaechen',
            label: 'Anbauflaechen',
            icon: FileText,
            module: '@/pages/nawaro/anbauflaechen',
            preferredPath: 'nawaro/anbauflaechen',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'nawaro-raps-profil',
            label: 'Raps-Profil',
            icon: FileText,
            module: '@/pages/nawaro/raps-profil',
            preferredPath: 'nawaro/raps-profil',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
        ],
      },
      {
        id: 'feldbuch',
        label: 'Feldbuch',
        icon: FileText,
        module: '@/pages/agrar/feldbuch/schlagkartei',
        preferredPath: 'agrar/feldbuch/schlagkartei',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'saatzucht',
        label: 'Saatzucht',
        icon: Leaf,
        module: '@/pages/agrar/saatzucht',
        preferredPath: 'agrar/saatzucht',
        keywords: ['saatzucht', 'partie', 'zertifikat', 'generation'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'vermehrungsvertraege',
        label: 'Vermehrungsverträge',
        icon: Leaf,
        module: '@/pages/agrar/vermehrungsvertraege',
        preferredPath: 'agrar/vermehrungsvertraege',
        keywords: ['vermehrungsvertrag', 'saatzucht', 'vermehrer', 'kategorie'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'zinsabrechnung',
        label: 'Zinsabrechnung',
        icon: Euro,
        module: '@/pages/agrar/zinsabrechnung',
        preferredPath: 'agrar/zinsabrechnung',
        keywords: ['zins', 'abrechnung', 'kontrakt', 'zinssatz'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'sammelabrechnung',
        label: 'Sammelabrechnung',
        icon: FileText,
        module: '@/pages/agrar/sammelabrechnung',
        preferredPath: 'agrar/sammelabrechnung',
        keywords: ['sammelabrechnung', 'rohware', 'abrechnung'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
      },
      {
        id: 'annahmen-qualitaet-nachtrag',
        label: 'Qualitäts-Nachtrag Annahmen',
        icon: FileText,
        module: '@/pages/agrar/annahmen-qualitaet-nachtrag',
        preferredPath: 'agrar/annahmen-qualitaet-nachtrag',
        keywords: ['qualität', 'nachtrag', 'laborbuch', 'annahme', 'feuchte', 'hektolitergewicht', 'besatz', 'unterbrochen'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
      },
      {
        id: 'rohwarengruppen',
        label: 'Rohwarengruppen [RWG]',
        icon: Wheat,
        module: '@/pages/agrar/rohwarengruppen',
        preferredPath: 'agrar/rohwarengruppen',
        keywords: ['rohwarengruppe', 'rwg', 'rohware', 'abrechnungsschema', 'rohwarenabrechnung'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'futtermittel',
        label: 'Futtermittel',
        icon: Package,
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
        children: [
          {
            id: 'einzelfuttermittel',
            label: 'Einzelfuttermittel',
            icon: Package,
            module: '@/pages/futtermittel/einzelfuttermittel-liste',
            preferredPath: 'futtermittel/einzelfuttermittel-liste',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'mischfuttermittel',
            label: 'Mischfuttermittel',
            icon: Package,
            module: '@/pages/futtermittel/mischfuttermittel-liste',
            preferredPath: 'futtermittel/mischfuttermittel-liste',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'futtermittel-wareneingang',
            label: 'Wareneingang',
            icon: Truck,
            module: '@/pages/futtermittel/futtermittel-wareneingang',
            preferredPath: 'futtermittel/futtermittel-wareneingang',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'futtermittel-qualitaet',
            label: 'Qualitätskontrolle',
            icon: Activity,
            module: '@/pages/futtermittel/futtermittel-qualitaetskontrolle',
            preferredPath: 'futtermittel/futtermittel-qualitaetskontrolle',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'futtermittel-statistik',
            label: 'Statistik',
            icon: BarChart3,
            module: '@/pages/futtermittel/futtermittel-statistik',
            preferredPath: 'futtermittel/futtermittel-statistik',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'rationsoptimierung',
            label: 'Rationsoptimierung',
            icon: Calculator,
            module: '@/pages/futtermittel/rationsoptimierung',
            preferredPath: 'futtermittel/rationsoptimierung',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'rationseditor',
            label: 'Rationseditor',
            icon: FlaskConical,
            module: '@/pages/futtermittel/rationseditor',
            preferredPath: 'futtermittel/rationseditor',
            keywords: ['ration', 'editor', 'bewertung', 'komponenten'],
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'rationsvergleich',
            label: 'Rationsvergleich',
            icon: GitBranch,
            module: '@/pages/futtermittel/rationsvergleich',
            preferredPath: 'futtermittel/rationsvergleich',
            keywords: ['ration', 'vergleich', 'varianten'],
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'futtermittel-beratung',
            label: 'Beratungsfälle',
            icon: Users,
            module: '@/pages/futtermittel/beratung',
            preferredPath: 'futtermittel/beratung',
            keywords: ['beratung', 'fall', 'massnahmen', 'beobachtung'],
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'futtermittel-integrationsmonitor',
            label: 'Integrationsmonitor',
            icon: Monitor,
            module: '@/pages/futtermittel/integrationsmonitor',
            preferredPath: 'futtermittel/integrationsmonitor',
            keywords: ['integration', 'import', 'quarantaene', 'monitor'],
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'fuetterungsdokumentation-mobil',
            label: 'Jetzt füttern (mobil)',
            icon: Smartphone,
            module: '@/pages/futtermittel/fuetterungsdokumentation-mobil',
            preferredPath: 'futtermittel/fuetterungsdokumentation-mobil',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'rations-schnittstellen-import',
            label: 'Schnittstellen-Import',
            icon: Upload,
            module: '@/pages/futtermittel/rations-schnittstellen-import',
            preferredPath: 'futtermittel/rations-schnittstellen-import',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'grundfutteranalysen',
            label: 'Grundfutter-Analysen',
            icon: Microscope,
            module: '@/pages/futtermittel/grundfutteranalysen',
            preferredPath: 'futtermittel/grundfutteranalysen',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'rations-zugang',
            label: 'Datenschutz / Zugangsverwaltung',
            icon: Shield,
            module: '@/pages/futtermittel/rations-zugang',
            preferredPath: 'futtermittel/rations-zugang',
            mcp: { businessDomain: 'agrar', scope: 'agrar:admin' },
          },
        ],
      },
    ],
  },
  {
    id: 'annahme',
    label: 'Annahme & Waage',
    icon: Truck,
    mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
    children: [
      {
        id: 'annahme-qr',
        label: 'QR-Scanner',
        icon: QrCode,
        module: '@/pages/annahme/qr-scanner',
        path: '/annahme/qr-scanner',
        keywords: ['qr', 'handy', 'mobil', 'scan', 'qr-scanner'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'rohware-annahme',
        label: 'Rohware-Annahme',
        icon: Package,
        module: '@/pages/annahme/rohware',
        path: '/annahme/rohware',
        keywords: ['rohware', 'annahme', 'lagerung', 'eingang'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
      {
        id: 'warteschlange',
        label: 'Warteschlange',
        icon: Truck,
        module: '@/pages/annahme/warteschlange',
        path: '/annahme/warteschlange',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'hofliste',
        label: 'Hofliste',
        icon: Scale,
        module: '@/pages/waage/hofliste',
        path: '/waage/hofliste',
        keywords: ['hofliste', 'hof', 'yard'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'waage-liste',
        label: 'Waagen',
        icon: Scale,
        module: '@/pages/waage/liste',
        path: '/waage/liste',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'wiegungen',
        label: 'Wiegungen',
        icon: FileText,
        module: '@/pages/waage/wiegungen',
        path: '/waage/wiegungen',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'waagen-vorlagen',
        label: 'Waagenvorlagen',
        icon: FileText,
        module: '@/pages/waage/vorlagen',
        path: '/waage/vorlagen',
        keywords: ['vorlagen', 'waagenvorlagen'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'annahme-qualitaets-check',
        label: 'Qualitäts-Check',
        icon: FlaskConical,
        module: '@/pages/annahme/qualitaets-check',
        preferredPath: 'annahme/qualitaets-check',
        keywords: ['qualität', 'check', 'probe', 'annahme'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
      {
        id: 'annahme-lkw-registrierung',
        label: 'LKW-Registrierung',
        icon: Truck,
        module: '@/pages/annahme/lkw-registrierung',
        preferredPath: 'annahme/lkw-registrierung',
        keywords: ['lkw', 'registrierung', 'annahme', 'einfahrt'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
      {
        id: 'annahme-abrechnung',
        label: 'Abrechnung',
        icon: FileText,
        module: '@/pages/annahme/abrechnung',
        preferredPath: 'annahme/abrechnung',
        keywords: ['abrechnung', 'annahme', 'rohware'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'annahme-klaerung',
        label: 'Klärung / Gesperrt',
        icon: AlertCircle,
        module: '@/pages/annahme/klaerung-gesperrt',
        preferredPath: 'annahme/klaerung-gesperrt',
        keywords: ['klärung', 'gesperrt', 'sperre', 'annahme'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
    ],
  },
  {
    id: 'quality',
    label: 'Qualität & Compliance',
    icon: ShieldCheck,
    mcp: { businessDomain: 'quality', scope: 'quality:read' },
    children: [
      {
        id: 'qm-dokumente',
        label: 'QM-Dokumente',
        icon: FileText,
        module: '@/pages/document',
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
      {
        id: 'audit-trails',
        label: 'Audit Trails',
        icon: ShieldCheck,
        module: '@/pages/admin/audit-log',
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
      {
        id: 'compliance',
        label: 'Compliance Cockpit',
        icon: ShieldCheck,
        module: '@/pages/admin/compliance-dashboard',
        preferredPath: 'admin/compliance',
        keywords: ['compliance'],
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
      {
        id: 'labor-auftraege',
        label: 'Laboraufträge',
        icon: FlaskConical,
        module: '@/pages/qualitaet/labor-auftrag',
        preferredPath: 'qualitaet/labor-auftrag',
        keywords: ['labor', 'auftrag', 'probe', 'analyse'],
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
      {
        id: 'reklamationen',
        label: 'Reklamationen',
        icon: AlertCircle,
        module: '@/pages/qualitaet/reklamationen',
        preferredPath: 'qualitaet/reklamationen',
        keywords: ['reklamation', 'beschwerde', 'mängel', 'rückgabe'],
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
    ],
  },
  {
    id: 'compliance',
    label: 'Compliance',
    icon: ShieldCheck,
    mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
    children: [
      {
        id: 'policies',
        label: 'Richtlinien',
        icon: ShieldCheck,
        module: '@/pages/policy-manager',
        preferredPath: 'policies',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'zulassungen',
        label: 'Zulassungen',
        icon: FileText,
        module: '@/pages/compliance/zulassungen-register',
        path: '/compliance/zulassungen-register',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'export-pruefprotokoll',
        label: 'Export-Protokoll',
        icon: FileText,
        module: '@/pages/compliance/export-pruefprotokoll',
        path: '/compliance/export-pruefprotokoll',
        keywords: ['export', 'gefahrstoff', 'naehrstoff', 'trace'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'meldewesen',
        label: 'Meldewesen',
        icon: FileText,
        module: '@/pages/compliance/meldewesen-konsole',
        path: '/compliance/meldewesen-konsole',
        keywords: ['meldewesen', 'intrastat', 'mvo', 'eudr'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'eudr',
        label: 'EUDR-Compliance',
        icon: Leaf,
        module: '@/pages/nachhaltigkeit/eudr-compliance',
        path: '/nachhaltigkeit/eudr-compliance',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'esg-report',
        label: 'ESG/CO2-Bericht',
        icon: BarChart3,
        module: '@/pages/nachhaltigkeit/esg-report',
        path: '/nachhaltigkeit/esg-report',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'co2-bilanz',
        label: 'CO₂-Bilanz',
        icon: Leaf,
        module: '@/pages/nachhaltigkeit/co2-bilanz',
        preferredPath: 'nachhaltigkeit/co2-bilanz',
        keywords: ['co2', 'kohlenstoff', 'emissionen', 'klimabilanz'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'biodiversitaet',
        label: 'Biodiversität',
        icon: Leaf,
        module: '@/pages/nachhaltigkeit/biodiversitaet',
        preferredPath: 'nachhaltigkeit/biodiversitaet',
        keywords: ['biodiversität', 'artenvielfalt', 'naturschutz', 'fläche'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'labor',
        label: 'Labor',
        icon: FileText,
        module: '@/pages/qualitaet/labor-liste',
        path: '/qualitaet/labor-liste',
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
      {
        id: 'ausnahmen',
        label: 'Betriebs-Ausnahmen (KI)',
        icon: AlertCircle,
        module: '@/pages/qualitaet/ausnahmen',
        preferredPath: 'qualitaet/ausnahmen',
        keywords: ['ausnahmen', 'eskalation', 'exception', 'ki', 'agent', 'priorisierung'],
        mcp: { businessDomain: 'quality', scope: 'quality:write' },
      },
      {
        id: 'zertifikate',
        label: 'Zertifikate',
        icon: ShieldCheck,
        module: '@/pages/zertifikate/liste',
        path: '/zertifikate/liste',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'gelangensbestaetigung',
        label: 'Gelangensbestätigung §17a',
        icon: ShieldCheck,
        module: '@/pages/compliance/gelangensbestaetigung',
        path: '/compliance/gelangensbestaetigung',
        keywords: ['gelangensbestätigung', 'umsatzsteuer', 'innergemeinschaftlich', 'lieferung'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'sanktionspruefung',
        label: 'Sanktionsprüfung',
        icon: ShieldCheck,
        module: '@/pages/compliance/sanktionspruefung',
        path: '/compliance/sanktionspruefung',
        keywords: ['sanktion', 'prüfung', 'eu', 'ofac', 'liste'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'lksg',
        label: 'LKSG Lieferanten-Risiko',
        icon: ShieldCheck,
        module: '@/pages/compliance/lksg',
        path: '/compliance/lksg',
        keywords: ['lksg', 'lieferkette', 'risiko', 'lieferant', 'sorgfalt'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'intrastat',
        label: 'Intrastat-Meldungen',
        icon: FileText,
        module: '@/pages/compliance/intrastat',
        path: '/compliance/intrastat',
        keywords: ['intrastat', 'eu', 'meldung', 'statistik', 'warenverkehr'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'pcn-liste',
        label: 'PCN-Meldungen',
        icon: FileText,
        module: '@/pages/compliance/pcn-liste',
        preferredPath: 'compliance/pcn-liste',
        keywords: ['pcn', 'meldung', 'produkt', 'echa', 'chemikalien'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'pcn-ufi',
        label: 'UFI-Kennzeichnung',
        icon: FileText,
        module: '@/pages/compliance/pcn-ufi',
        preferredPath: 'compliance/pcn-ufi',
        keywords: ['ufi', 'pcn', 'kennzeichnung', 'echa'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'qs-checkliste',
        label: 'QS-Checkliste',
        icon: ShieldCheck,
        module: '@/pages/compliance/qs-checkliste',
        preferredPath: 'compliance/qs-checkliste',
        keywords: ['qs', 'checkliste', 'qualitätssicherung', 'audit'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'cross-compliance',
        label: 'Cross-Compliance',
        icon: ShieldCheck,
        module: '@/pages/compliance/cross-compliance',
        preferredPath: 'compliance/cross-compliance',
        keywords: ['cross', 'compliance', 'eu', 'förderung', 'auflagen'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'vvvo-register',
        label: 'VVVO-Register',
        icon: FileText,
        module: '@/pages/compliance/vvvo-register',
        preferredPath: 'compliance/vvvo-register',
        keywords: ['vvvo', 'tierseuchenrecht', 'register', 'tierzucht'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'sachkunde-register',
        label: 'Sachkunde-Register',
        icon: ShieldCheck,
        module: '@/pages/compliance/sachkunde-register',
        preferredPath: 'compliance/sachkunde-register',
        keywords: ['sachkunde', 'register', 'zertifikat', 'qualifikation'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'enni-meldungen',
        label: 'ENNI-Meldungen',
        icon: FileText,
        module: '@/pages/compliance/enni-meldungen',
        preferredPath: 'compliance/enni-meldungen',
        keywords: ['enni', 'meldung', 'energiesteuer', 'nachhaltigkeitsnachweis'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'saatgut-nachbau',
        label: 'Saatgut-Nachbau',
        icon: Leaf,
        module: '@/pages/compliance/saatgut-nachbau',
        preferredPath: 'compliance/saatgut-nachbau',
        keywords: ['saatgut', 'nachbau', 'sorte', 'lizenz'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'bvl-umsatzmeldung',
        label: 'BVL-Umsatzmeldung',
        icon: FileText,
        module: '@/pages/compliance/bvl-umsatzmeldung',
        preferredPath: 'compliance/bvl-umsatzmeldung',
        keywords: ['bvl', 'umsatzmeldung', 'pflanzenschutzmittel', 'statistik'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
    ],
  },
  {
    id: 'logistik',
    label: 'Logistik',
    icon: Truck,
    mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
    children: [
      {
        id: 'tour-fracht-arbeitsraum',
        label: 'Tour & Fracht (Dispo)',
        icon: LayoutGrid,
        module: '@/pages/logistik/tour-fracht-arbeitsraum',
        preferredPath: 'logistik/tour-fracht-arbeitsraum',
        keywords: ['dispo', 'arbeitsraum', 'kombiniert', 'fracht', 'tour'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'tourenplanung',
        label: 'Tourenplanung',
        icon: Truck,
        module: '@/pages/logistik/tourenplanung',
        preferredPath: 'logistik/tourenplanung',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'frachtbriefe',
        label: 'Frachtbriefe',
        icon: Target,
        module: '@/pages/logistik/frachtbriefe',
        preferredPath: 'logistik/frachtbriefe',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'fuhrpark',
        label: 'Fuhrpark',
        icon: Truck,
        module: '@/pages/fuhrpark/uebersicht',
        preferredPath: 'fuhrpark/uebersicht',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
        children: [
          {
            id: 'fuhrpark-dashboard',
            label: 'Übersicht',
            icon: BarChart3,
            module: '@/pages/fuhrpark/uebersicht',
            preferredPath: 'fuhrpark/uebersicht',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'fuhrpark-fahrzeuge',
            label: 'Fahrzeuge',
            icon: Truck,
            module: '@/pages/fuhrpark/fahrzeuge',
            preferredPath: 'fuhrpark/fahrzeuge',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'fuhrpark-stammdaten',
            label: 'Stammdaten',
            icon: Settings,
            module: '@/pages/fuhrpark/fuhrpark-stammdaten',
            preferredPath: 'fuhrpark/fuhrpark-stammdaten',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'fuhrpark-rechnungen',
            label: 'Rechnungen',
            icon: FileText,
            module: '@/pages/fuhrpark/fuhrpark-rechnungen',
            preferredPath: 'fuhrpark/fuhrpark-rechnungen',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'fuhrpark-auswertungen',
            label: 'Auswertungen',
            icon: BarChart3,
            module: '@/pages/fuhrpark/fuhrpark-auswertung-kosten-pro-fahrzeug',
            preferredPath: 'fuhrpark/fuhrpark-auswertung-kosten-pro-fahrzeug',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'fuhrpark-ausgehende-belege-dokumente',
            label: 'Ausgehende Belege & Dokumente',
            icon: FileText,
            module: '@/pages/fuhrpark/ausgehende-belege-dokumente',
            preferredPath: 'fuhrpark/ausgehende-belege-dokumente',
            keywords: ['belege', 'dokumente', 'versand', 'druck'],
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'fuhrpark-vertiefung',
            label: 'Vertiefung & Analyse',
            icon: Activity,
            module: '@/pages/fuhrpark/fahrzeug-vertiefung',
            preferredPath: 'fuhrpark/fahrzeug-vertiefung',
            keywords: ['statushistorie', 'schadensfälle', 'bußgeld', 'wartung', 'leasing', 'rückgabe', 'vorhersage'],
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
        ],
      },
      {
        id: 'versandprofile',
        label: 'Versandprofile & Avise',
        icon: Send,
        module: '@/pages/logistik/versandprofile',
        preferredPath: 'logistik/versandprofile',
        keywords: ['versandprofil', 'smtp', 'lieferavis', 'avise', 'liefervoranmeldung'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'frachttabellen',
        label: 'Frachttabellen [FRA]',
        icon: Truck,
        module: '@/pages/logistik/frachttabellen',
        preferredPath: 'logistik/frachttabellen',
        keywords: ['frachttabelle', 'fra', 'frachtsatz', 'frachtklasse', 'frachtgruppe'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'strecke',
        label: 'Strecke',
        icon: Truck,
        module: '@/pages/strecke/menu',
        preferredPath: 'strecke/menu',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
        children: [
          {
            id: 'strecke-menu',
            label: 'Menue',
            icon: Truck,
            module: '@/pages/strecke/menu',
            preferredPath: 'strecke/menu',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'strecke-streckengeschaeft',
            label: 'Streckengeschaeft',
            icon: FileText,
            module: '@/pages/strecke/streckengeschaeft',
            preferredPath: 'strecke/streckengeschaeft',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'strecke-disposition',
            label: 'Strecken-Disposition',
            icon: Truck,
            module: '@/pages/strecke/disposition',
            preferredPath: 'strecke/disposition',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'strecke-vorlaeufig',
            label: 'Vorlaeufige Streckengeschaefte',
            icon: FileText,
            module: '@/pages/strecke/vorlaeufige-streckengeschaefte',
            preferredPath: 'strecke/vorlaeufige-streckengeschaefte',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'strecke-dokumente-drucken',
            label: 'Strecken-Dokumente drucken',
            icon: FileText,
            module: '@/pages/strecke/dokumente-drucken',
            preferredPath: 'strecke/dokumente-drucken',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'strecke-qualitaets-abweichung',
            label: 'Qualitaets-Abweichung',
            icon: AlertCircle,
            module: '@/pages/strecke/qualitaets-abweichung',
            preferredPath: 'strecke/qualitaets-abweichung',
            mcp: { businessDomain: 'quality', scope: 'quality:read' },
          },
          {
            id: 'strecke-fracht-preise',
            label: 'Speditionen / Fracht-Preise',
            icon: Euro,
            module: '@/pages/strecke/speditionen-fracht-preise',
            preferredPath: 'strecke/speditionen-fracht-preise',
            keywords: ['fracht', 'preise', 'plz', 'spedition'],
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'strecke-nawaro-vertraege-pruefen',
            label: 'NaWaRo-Vertraege pruefen',
            icon: ShieldCheck,
            module: '@/pages/strecke/nawaro-vertraege-pruefen',
            preferredPath: 'strecke/nawaro-vertraege-pruefen',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'strecke-nawaro-uebersicht',
            label: 'NaWaRo-Uebersicht',
            icon: BarChart3,
            module: '@/pages/strecke/nawaro-uebersicht',
            preferredPath: 'strecke/nawaro-uebersicht',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'strecke-nawaro-uebersicht-drucken',
            label: 'NaWaRo-Uebersicht drucken',
            icon: FileText,
            module: '@/pages/strecke/nawaro-uebersicht-drucken',
            preferredPath: 'strecke/nawaro-uebersicht-drucken',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'strecke-nawaro-lieferungen',
            label: 'NaWaRo-Lieferungen',
            icon: Truck,
            module: '@/pages/strecke/nawaro-lieferungen',
            preferredPath: 'strecke/nawaro-lieferungen',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'strecke-nawaro-ernterklaerung-drucken',
            label: 'NaWaRo-Ernterklaerung drucken',
            icon: FileText,
            module: '@/pages/strecke/nawaro-ernterklaerung-drucken',
            preferredPath: 'strecke/nawaro-ernterklaerung-drucken',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
        ],
      },
    ],
  },
  {
    id: 'versand',
    label: 'Versand',
    icon: Truck,
    mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
    children: [
      {
        id: 'versand-paket-etikett',
        label: 'Paket-Etikett',
        icon: FileText,
        module: '@/pages/versand/paket-etikett',
        preferredPath: 'versand/paket-etikett',
        keywords: ['paket', 'etikett', 'label', 'versand'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
      {
        id: 'versand-frachtdokumente',
        label: 'Frachtdokumente',
        icon: FileText,
        module: '@/pages/versand/frachtdokumente',
        preferredPath: 'versand/frachtdokumente',
        keywords: ['fracht', 'dokumente', 'frachtbrief', 'versand'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
      {
        id: 'versand-avis',
        label: 'Versand-Avis',
        icon: Truck,
        module: '@/pages/versand/versand-avis',
        preferredPath: 'versand/versand-avis',
        keywords: ['avis', 'versand', 'ankündigung'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
    ],
  },
  {
    id: 'produktion',
    label: 'Produktion',
    icon: Settings,
    mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
    children: [
      {
        id: 'produktions-dokumente-drucken',
        label: 'Produktions-Dokumente drucken',
        icon: FileText,
        module: '@/pages/produktion/produktions-dokumente-drucken',
        preferredPath: 'produktion/produktions-dokumente-drucken',
        keywords: ['produktion', 'dokumente', 'drucken', 'produkt'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
      {
        id: 'rezepturgruppen',
        label: 'Rezepturgruppen [REZG]',
        icon: FlaskConical,
        module: '@/pages/produktion/rezepturgruppen',
        preferredPath: 'produktion/rezepturgruppen',
        keywords: ['rezepturgruppe', 'rezg', 'tierart', 'nutzungsrichtung', 'mischfutter'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
    ],
  },
  {
    id: 'pos',
    label: 'POS & Filialen',
    icon: Euro,
    mcp: { businessDomain: 'pos', scope: 'pos:read' },
    children: [
      {
        id: 'pos-terminal',
        label: 'Kassen-Terminal',
        icon: Euro,
        module: '@/pages/pos/terminal',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
      {
        id: 'tse-journal',
        label: 'TSE-Journal',
        icon: FileText,
        module: '@/pages/pos/tse-journal',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
      {
        id: 'tagesabschluss',
        label: 'Tagesabschluss',
        icon: Calculator,
        module: '@/pages/pos/tagesabschluss-enhanced',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
      {
        id: 'gift-cards',
        label: 'Geschenkkarten',
        icon: Euro,
        module: '@/pages/pos/gift-cards',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
      {
        id: 'rabatte',
        label: 'Rabatte',
        icon: Euro,
        module: '@/pages/pos/rabatte',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
      {
        id: 'pos-promotionen',
        label: 'Promotionen',
        icon: Tag,
        module: '@/pages/pos/promotionen',
        preferredPath: 'pos/promotionen',
        keywords: ['promotionen', 'aktionen', 'rabatt', 'pos'],
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
    ],
  },
  {
    id: 'personal',
    label: 'Personal',
    icon: Users,
    mcp: { businessDomain: 'hr', scope: 'hr:read' },
    children: [
      {
        id: 'mitarbeiter-liste',
        label: 'Mitarbeiter',
        icon: Users,
        module: '@/pages/personal/mitarbeiter-liste',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'zeiterfassung',
        label: 'Zeiterfassung',
        icon: Calendar,
        module: '@/pages/personal/zeiterfassung',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'stundenzettel',
        label: 'Stundenzettel',
        icon: FileText,
        module: '@/pages/personal/stundenzettel-liste',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'schulungen',
        label: 'Schulungen',
        icon: UserCog,
        module: '@/pages/personal/schulungen',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'qualifikationen',
        label: 'Qualifikationen',
        icon: UserCog,
        module: '@/pages/personal/qualifikationen',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'onboarding',
        label: 'Onboarding',
        icon: Users,
        module: '@/pages/personal/onboarding',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'hrm-operations-gates',
        label: 'HRM-Betriebsfreigaben',
        icon: ShieldCheck,
        module: '@/pages/personal/hrm-operations-gates',
        mcp: { businessDomain: 'hr', scope: 'hr:write' },
      },
      {
        id: 'schichtplan',
        label: 'Schichtplan',
        icon: Calendar,
        module: '@/pages/schichtplan/liste',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'organigramm',
        label: 'Organigramm',
        icon: Building2,
        module: '@/pages/personal/organigramm',
        preferredPath: 'personal/organigramm',
        keywords: ['organigramm', 'organisation', 'abteilungen', 'struktur'],
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'bewerbungen',
        label: 'Bewerbungen',
        icon: UserCog,
        module: '@/pages/personal/bewerbungen',
        preferredPath: 'personal/bewerbungen',
        keywords: ['bewerbung', 'rekrutierung', 'stelle', 'kandidat'],
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
    ],
  },
  {
    id: 'system',
    label: 'System & Betrieb',
    icon: Monitor,
    mcp: { businessDomain: 'system', scope: 'system:read' },
    children: [
      {
        id: 'mde-inbox',
        label: 'MDE-Eingangskorb',
        icon: Smartphone,
        module: '@/pages/schnittstelle/mde-inbox',
        preferredPath: 'schnittstelle/mde-inbox',
        keywords: ['mde', 'mobile datenerfassung', 'schnittstelle', 'quarantaene', 'import'],
        mcp: { businessDomain: 'system', scope: 'system:read' },
      },
      {
        id: 'workflow-leitstand',
        label: 'Workflow-Prozessleitstand',
        icon: Monitor,
        module: '@/pages/workflow/leitstand',
        preferredPath: 'workflow/leitstand',
        keywords: ['workflow', 'prozess', 'leitstand', 'event', 'replay', 'blocker', 'gate'],
        mcp: { businessDomain: 'system', scope: 'system:read' },
      },
    ],
  },
]
