import {
  Activity,
  ArrowUpDown,
  AlertCircle,
  BarChart3,
  Building2,
  Calendar,
  Calculator,
  Database,
  Euro,
  FileDown,
  FileText,
  FlaskConical,
  Globe,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Package,
  QrCode,
  RefreshCw,
  Scale,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Sprout,
  Target,
  Tractor,
  Truck,
  Upload,
  UserCog,
  Users,
  Zap,
  Search,
} from 'lucide-react'
import type { RawNavItem } from '@/app/navigation/types'

export const RAW_NAV_SECTIONS: RawNavItem[] = [
  {
    id: 'lager',
    label: 'Lager & Bestände',
    icon: Package,
    mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
    children: [
      {
        id: 'bestandsuebersicht',
        label: 'Bestandsübersicht',
        icon: Package,
        module: '@/pages/lager/bestandsuebersicht',
        keywords: ['bestandsübersicht'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'einlagerung',
        label: 'Einlagerung',
        icon: Truck,
        module: '@/pages/lager/einlagerung',
        keywords: ['einlagerung'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'auslagerung',
        label: 'Auslagerung',
        icon: Truck,
        module: '@/pages/lager/auslagerung',
        keywords: ['auslagerung'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'inventur',
        label: 'Inventur',
        icon: Scale,
        module: '@/pages/lager/inventur',
        keywords: ['inventur'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
      {
        id: 'bestandskorrektur',
        label: 'Bestandskorrektur',
        icon: RefreshCw,
        module: '@/pages/lager/bestandskorrektur',
        keywords: ['bestandskorrektur', 'schwund', 'bruch', 'mhd', 'korrektur'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:write' },
      },
      {
        id: 'lagerbewegungen',
        label: 'Lagerbewegungen',
        icon: ArrowUpDown,
        module: '@/pages/lager/lagerbewegungen',
        keywords: ['lagerbewegungen', 'buchungen', 'stock movements'],
        mcp: { businessDomain: 'inventory', scope: 'inventory:read' },
      },
    ],
  },
  {
    id: 'agrar',
    label: 'Agrar & Warenwirtschaft',
    icon: Sprout,
    featureKey: 'agrar',
    mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
    children: [
      {
        id: 'psm',
        label: 'Pflanzenschutz',
        icon: Leaf,
        module: '@/pages/agrar/psm/liste',
        preferredPath: 'agrar/psm',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'duenger',
        label: 'Dünger',
        icon: Sprout,
        module: '@/pages/agrar/duenger-liste',
        preferredPath: 'agrar/duenger-liste',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'saatgut',
        label: 'Saatgut',
        icon: Leaf,
        module: '@/pages/agrar/saatgut-liste',
        preferredPath: 'agrar/saatgut-liste',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'bodenproben',
        label: 'Bodenproben',
        icon: Scale,
        module: '@/pages/agrar/bodenproben/liste',
        preferredPath: 'agrar/bodenproben',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'ernte',
        label: 'Ernteplanung',
        icon: Tractor,
        module: '@/pages/agrar/ernte/liste',
        preferredPath: 'agrar/ernte',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'ernte-annahme',
        label: 'Ernte-Annahme',
        icon: Tractor,
        module: '@/pages/agrar/ernte-annahme-erfassung',
        preferredPath: 'agrar/ernte-annahme-erfassung',
        keywords: ['ernte', 'annahme', 'erfassung'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
      },
      {
        id: 'erntefenster-konfig',
        label: 'Erntefenster-Konfiguration',
        icon: Calendar,
        module: '@/pages/agrar/erntefenster-konfig',
        preferredPath: 'agrar/erntefenster-konfig',
        keywords: ['erntefenster', 'kampagne', 'saisonal', 'vorlage'],
        mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
      },
      {
        id: 'nawaro',
        label: 'NaWaRo',
        icon: Leaf,
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
        children: [
          {
            id: 'nawaro-mitteilung-drucken',
            label: 'Mitteilung drucken',
            icon: FileText,
            module: '@/pages/nawaro/mitteilung-drucken',
            preferredPath: 'nawaro/mitteilung-drucken',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'nawaro-vertraege',
            label: 'Vertraege',
            icon: FileText,
            module: '@/pages/nawaro/vertraege',
            preferredPath: 'nawaro/vertraege',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'nawaro-anbauflaechen',
            label: 'Anbauflaechen',
            icon: FileText,
            module: '@/pages/nawaro/anbauflaechen',
            preferredPath: 'nawaro/anbauflaechen',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'nawaro-raps-profil',
            label: 'Raps-Profil',
            icon: FileText,
            module: '@/pages/nawaro/raps-profil',
            preferredPath: 'nawaro/raps-profil',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
        ],
      },
      {
        id: 'feldbuch',
        label: 'Feldbuch',
        icon: FileText,
        module: '@/pages/agrar/feldbuch/schlagkartei',
        preferredPath: 'agrar/feldbuch/schlagkartei',
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
      },
      {
        id: 'futtermittel',
        label: 'Futtermittel',
        icon: Package,
        mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
        children: [
          {
            id: 'einzelfuttermittel',
            label: 'Einzelfuttermittel',
            icon: Package,
            module: '@/pages/futtermittel/einzelfuttermittel-liste',
            preferredPath: 'futtermittel/einzelfuttermittel-liste',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'mischfuttermittel',
            label: 'Mischfuttermittel',
            icon: Package,
            module: '@/pages/futtermittel/mischfuttermittel-liste',
            preferredPath: 'futtermittel/mischfuttermittel-liste',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'futtermittel-wareneingang',
            label: 'Wareneingang',
            icon: Truck,
            module: '@/pages/futtermittel/futtermittel-wareneingang',
            preferredPath: 'futtermittel/futtermittel-wareneingang',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
          {
            id: 'futtermittel-qualitaet',
            label: 'Qualitätskontrolle',
            icon: Activity,
            module: '@/pages/futtermittel/futtermittel-qualitaetskontrolle',
            preferredPath: 'futtermittel/futtermittel-qualitaetskontrolle',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'futtermittel-statistik',
            label: 'Statistik',
            icon: BarChart3,
            module: '@/pages/futtermittel/futtermittel-statistik',
            preferredPath: 'futtermittel/futtermittel-statistik',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'rationsoptimierung',
            label: 'Rationsoptimierung',
            icon: Calculator,
            module: '@/pages/futtermittel/rationsoptimierung',
            preferredPath: 'futtermittel/rationsoptimierung',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
        ],
      },
    ],
  },
  {
    id: 'annahme',
    label: 'Annahme & Waage',
    icon: Truck,
    mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
    children: [
      {
        id: 'annahme-qr',
        label: 'QR-Scanner',
        icon: QrCode,
        module: '@/pages/annahme/qr-scanner',
        path: '/annahme/qr-scanner',
        keywords: ['qr', 'handy', 'mobil', 'scan', 'qr-scanner'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'rohware-annahme',
        label: 'Rohware-Annahme',
        icon: Package,
        module: '@/pages/annahme/rohware',
        path: '/annahme/rohware',
        keywords: ['rohware', 'annahme', 'lagerung', 'eingang'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
      {
        id: 'warteschlange',
        label: 'Warteschlange',
        icon: Truck,
        module: '@/pages/annahme/warteschlange',
        path: '/annahme/warteschlange',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'hofliste',
        label: 'Hofliste',
        icon: Scale,
        module: '@/pages/waage/hofliste',
        path: '/waage/hofliste',
        keywords: ['hofliste', 'hof', 'yard'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'waage-liste',
        label: 'Waagen',
        icon: Scale,
        module: '@/pages/waage/liste',
        path: '/waage/liste',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'wiegungen',
        label: 'Wiegungen',
        icon: FileText,
        module: '@/pages/waage/wiegungen',
        path: '/waage/wiegungen',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
    ],
  },
  {
    id: 'quality',
    label: 'Qualität & Compliance',
    icon: ShieldCheck,
    mcp: { businessDomain: 'quality', scope: 'quality:read' },
    children: [
      {
        id: 'qm-dokumente',
        label: 'QM-Dokumente',
        icon: FileText,
        module: '@/pages/document',
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
      {
        id: 'audit-trails',
        label: 'Audit Trails',
        icon: ShieldCheck,
        module: '@/pages/admin/audit-log',
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
      {
        id: 'compliance',
        label: 'Compliance Cockpit',
        icon: ShieldCheck,
        module: '@/pages/admin/compliance-dashboard',
        preferredPath: 'admin/compliance',
        keywords: ['compliance'],
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
    ],
  },
  {
    id: 'compliance',
    label: 'Compliance',
    icon: ShieldCheck,
    mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
    children: [
      {
        id: 'policies',
        label: 'Richtlinien',
        icon: ShieldCheck,
        module: '@/pages/policy-manager',
        preferredPath: 'policies',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'zulassungen',
        label: 'Zulassungen',
        icon: FileText,
        module: '@/pages/compliance/zulassungen-register',
        path: '/compliance/zulassungen-register',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'export-pruefprotokoll',
        label: 'Export-Protokoll',
        icon: FileText,
        module: '@/pages/compliance/export-pruefprotokoll',
        path: '/compliance/export-pruefprotokoll',
        keywords: ['export', 'gefahrstoff', 'naehrstoff', 'trace'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'meldewesen',
        label: 'Meldewesen',
        icon: FileText,
        module: '@/pages/compliance/meldewesen-konsole',
        path: '/compliance/meldewesen-konsole',
        keywords: ['meldewesen', 'intrastat', 'mvo', 'eudr'],
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'eudr',
        label: 'EUDR-Compliance',
        icon: Leaf,
        module: '@/pages/nachhaltigkeit/eudr-compliance',
        path: '/nachhaltigkeit/eudr-compliance',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'esg-report',
        label: 'ESG/CO2-Bericht',
        icon: BarChart3,
        module: '@/pages/nachhaltigkeit/esg-report',
        path: '/nachhaltigkeit/esg-report',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
      {
        id: 'labor',
        label: 'Labor',
        icon: FileText,
        module: '@/pages/qualitaet/labor-liste',
        path: '/qualitaet/labor-liste',
        mcp: { businessDomain: 'quality', scope: 'quality:read' },
      },
      {
        id: 'ausnahmen',
        label: 'Betriebs-Ausnahmen (KI)',
        icon: AlertCircle,
        module: '@/pages/qualitaet/ausnahmen',
        preferredPath: 'qualitaet/ausnahmen',
        keywords: ['ausnahmen', 'eskalation', 'exception', 'ki', 'agent', 'priorisierung'],
        mcp: { businessDomain: 'quality', scope: 'quality:write' },
      },
      {
        id: 'zertifikate',
        label: 'Zertifikate',
        icon: ShieldCheck,
        module: '@/pages/zertifikate/liste',
        path: '/zertifikate/liste',
        mcp: { businessDomain: 'compliance', scope: 'compliance:read' },
      },
    ],
  },
  {
    id: 'logistik',
    label: 'Logistik',
    icon: Truck,
    mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
    children: [
      {
        id: 'tourenplanung',
        label: 'Tourenplanung',
        icon: Truck,
        module: '@/pages/logistik/tourenplanung',
        preferredPath: 'logistik/tourenplanung',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'frachtbriefe',
        label: 'Frachtbriefe',
        icon: Target,
        module: '@/pages/logistik/frachtbriefe',
        preferredPath: 'logistik/frachtbriefe',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
      },
      {
        id: 'fuhrpark',
        label: 'Fuhrpark',
        icon: Truck,
        module: '@/pages/fuhrpark/uebersicht',
        preferredPath: 'fuhrpark/uebersicht',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
        children: [
          {
            id: 'fuhrpark-dashboard',
            label: 'Übersicht',
            icon: BarChart3,
            module: '@/pages/fuhrpark/uebersicht',
            preferredPath: 'fuhrpark/uebersicht',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'fuhrpark-fahrzeuge',
            label: 'Fahrzeuge',
            icon: Truck,
            module: '@/pages/fuhrpark/fahrzeuge',
            preferredPath: 'fuhrpark/fahrzeuge',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'fuhrpark-stammdaten',
            label: 'Stammdaten',
            icon: Settings,
            module: '@/pages/fuhrpark/fuhrpark-stammdaten',
            preferredPath: 'fuhrpark/fuhrpark-stammdaten',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'fuhrpark-rechnungen',
            label: 'Rechnungen',
            icon: FileText,
            module: '@/pages/fuhrpark/fuhrpark-rechnungen',
            preferredPath: 'fuhrpark/fuhrpark-rechnungen',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'fuhrpark-auswertungen',
            label: 'Auswertungen',
            icon: BarChart3,
            module: '@/pages/fuhrpark/fuhrpark-auswertung-kosten-pro-fahrzeug',
            preferredPath: 'fuhrpark/fuhrpark-auswertung-kosten-pro-fahrzeug',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'fuhrpark-ausgehende-belege-dokumente',
            label: 'Ausgehende Belege & Dokumente',
            icon: FileText,
            module: '@/pages/fuhrpark/ausgehende-belege-dokumente',
            preferredPath: 'fuhrpark/ausgehende-belege-dokumente',
            keywords: ['belege', 'dokumente', 'versand', 'druck'],
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
        ],
      },
      {
        id: 'strecke',
        label: 'Strecke',
        icon: Truck,
        module: '@/pages/strecke/menu',
        preferredPath: 'strecke/menu',
        mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
        children: [
          {
            id: 'strecke-menu',
            label: 'Menue',
            icon: Truck,
            module: '@/pages/strecke/menu',
            preferredPath: 'strecke/menu',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'strecke-streckengeschaeft',
            label: 'Streckengeschaeft',
            icon: FileText,
            module: '@/pages/strecke/streckengeschaeft',
            preferredPath: 'strecke/streckengeschaeft',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'strecke-disposition',
            label: 'Strecken-Disposition',
            icon: Truck,
            module: '@/pages/strecke/disposition',
            preferredPath: 'strecke/disposition',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'strecke-vorlaeufig',
            label: 'Vorlaeufige Streckengeschaefte',
            icon: FileText,
            module: '@/pages/strecke/vorlaeufige-streckengeschaefte',
            preferredPath: 'strecke/vorlaeufige-streckengeschaefte',
            mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
          },
          {
            id: 'strecke-dokumente-drucken',
            label: 'Strecken-Dokumente drucken',
            icon: FileText,
            module: '@/pages/strecke/dokumente-drucken',
            preferredPath: 'strecke/dokumente-drucken',
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'strecke-qualitaets-abweichung',
            label: 'Qualitaets-Abweichung',
            icon: AlertCircle,
            module: '@/pages/strecke/qualitaets-abweichung',
            preferredPath: 'strecke/qualitaets-abweichung',
            mcp: { businessDomain: 'quality', scope: 'quality:read' },
          },
          {
            id: 'strecke-fracht-preise',
            label: 'Speditionen / Fracht-Preise',
            icon: Euro,
            module: '@/pages/strecke/speditionen-fracht-preise',
            preferredPath: 'strecke/speditionen-fracht-preise',
            keywords: ['fracht', 'preise', 'plz', 'spedition'],
            mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
          },
          {
            id: 'strecke-nawaro-vertraege-pruefen',
            label: 'NaWaRo-Vertraege pruefen',
            icon: ShieldCheck,
            module: '@/pages/strecke/nawaro-vertraege-pruefen',
            preferredPath: 'strecke/nawaro-vertraege-pruefen',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'strecke-nawaro-uebersicht',
            label: 'NaWaRo-Uebersicht',
            icon: BarChart3,
            module: '@/pages/strecke/nawaro-uebersicht',
            preferredPath: 'strecke/nawaro-uebersicht',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'strecke-nawaro-uebersicht-drucken',
            label: 'NaWaRo-Uebersicht drucken',
            icon: FileText,
            module: '@/pages/strecke/nawaro-uebersicht-drucken',
            preferredPath: 'strecke/nawaro-uebersicht-drucken',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'strecke-nawaro-lieferungen',
            label: 'NaWaRo-Lieferungen',
            icon: Truck,
            module: '@/pages/strecke/nawaro-lieferungen',
            preferredPath: 'strecke/nawaro-lieferungen',
            mcp: { businessDomain: 'agrar', scope: 'agrar:read' },
          },
          {
            id: 'strecke-nawaro-ernterklaerung-drucken',
            label: 'NaWaRo-Ernterklaerung drucken',
            icon: FileText,
            module: '@/pages/strecke/nawaro-ernterklaerung-drucken',
            preferredPath: 'strecke/nawaro-ernterklaerung-drucken',
            mcp: { businessDomain: 'agrar', scope: 'agrar:write' },
          },
        ],
      },
    ],
  },
  {
    id: 'versand',
    label: 'Versand',
    icon: Truck,
    mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
    children: [
      {
        id: 'versand-paket-etikett',
        label: 'Paket-Etikett',
        icon: FileText,
        module: '@/pages/versand/paket-etikett',
        preferredPath: 'versand/paket-etikett',
        keywords: ['paket', 'etikett', 'label', 'versand'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
      {
        id: 'versand-frachtdokumente',
        label: 'Frachtdokumente',
        icon: FileText,
        module: '@/pages/versand/frachtdokumente',
        preferredPath: 'versand/frachtdokumente',
        keywords: ['fracht', 'dokumente', 'frachtbrief', 'versand'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
      {
        id: 'versand-avis',
        label: 'Versand-Avis',
        icon: Truck,
        module: '@/pages/versand/versand-avis',
        preferredPath: 'versand/versand-avis',
        keywords: ['avis', 'versand', 'ankündigung'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
    ],
  },
  {
    id: 'produktion',
    label: 'Produktion',
    icon: Settings,
    mcp: { businessDomain: 'logistics', scope: 'logistics:read' },
    children: [
      {
        id: 'produktions-dokumente-drucken',
        label: 'Produktions-Dokumente drucken',
        icon: FileText,
        module: '@/pages/produktion/produktions-dokumente-drucken',
        preferredPath: 'produktion/produktions-dokumente-drucken',
        keywords: ['produktion', 'dokumente', 'drucken', 'produkt'],
        mcp: { businessDomain: 'logistics', scope: 'logistics:write' },
      },
    ],
  },
  {
    id: 'pos',
    label: 'POS & Filialen',
    icon: Euro,
    mcp: { businessDomain: 'pos', scope: 'pos:read' },
    children: [
      {
        id: 'pos-terminal',
        label: 'Kassen-Terminal',
        icon: Euro,
        module: '@/pages/pos/terminal',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
      {
        id: 'tse-journal',
        label: 'TSE-Journal',
        icon: FileText,
        module: '@/pages/pos/tse-journal',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
      {
        id: 'tagesabschluss',
        label: 'Tagesabschluss',
        icon: Calculator,
        module: '@/pages/pos/tagesabschluss-enhanced',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
      {
        id: 'gift-cards',
        label: 'Geschenkkarten',
        icon: Euro,
        module: '@/pages/pos/gift-cards',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
      {
        id: 'rabatte',
        label: 'Rabatte',
        icon: Euro,
        module: '@/pages/pos/rabatte',
        mcp: { businessDomain: 'pos', scope: 'pos:read' },
      },
    ],
  },
  {
    id: 'personal',
    label: 'Personal',
    icon: Users,
    mcp: { businessDomain: 'hr', scope: 'hr:read' },
    children: [
      {
        id: 'mitarbeiter-liste',
        label: 'Mitarbeiter',
        icon: Users,
        module: '@/pages/personal/mitarbeiter-liste',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'zeiterfassung',
        label: 'Zeiterfassung',
        icon: Calendar,
        module: '@/pages/personal/zeiterfassung',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'stundenzettel',
        label: 'Stundenzettel',
        icon: FileText,
        module: '@/pages/personal/stundenzettel-liste',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'schulungen',
        label: 'Schulungen',
        icon: UserCog,
        module: '@/pages/personal/schulungen',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'qualifikationen',
        label: 'Qualifikationen',
        icon: UserCog,
        module: '@/pages/personal/qualifikationen',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'onboarding',
        label: 'Onboarding',
        icon: Users,
        module: '@/pages/personal/onboarding',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
      {
        id: 'schichtplan',
        label: 'Schichtplan',
        icon: Calendar,
        module: '@/pages/schichtplan/liste',
        mcp: { businessDomain: 'hr', scope: 'hr:read' },
      },
    ],
  },
]
